begin;

-- ==========================================================================
-- Descarte de machos — lançado no fechamento do turno (não hora a hora):
-- descarte normalmente só é percebido depois do sopro (retirada, manuseio,
-- estufa), então um total por caixa/macho no fechamento é mais realista do
-- que tentar atribuir a uma hora específica. Um registro por
-- (turno, máquina, macho); "machos estimados" (sopros × machos_por_sopro)
-- menos isso vira o "líquido".
-- ==========================================================================
alter table public.turnos_producao_macharia
  add column if not exists rascunho_descartes jsonb not null default '[]'::jsonb;

create table if not exists public.descartes_producao_macharia (
  id bigint generated by default as identity primary key,
  turno_producao_id bigint not null references public.turnos_producao_macharia(id),
  linha_maquina_id bigint not null references public.linhas_maquinas_producao(id),
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  macho_id bigint not null references public.machos_macharia(id),
  quantidade_descartada integer not null default 0 check (quantidade_descartada >= 0),
  observacao text,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  unique (turno_producao_id, linha_maquina_id, macho_id)
);

create index if not exists descartes_macharia_turno_idx
  on public.descartes_producao_macharia(turno_producao_id);
create index if not exists descartes_macharia_data_turno_idx
  on public.descartes_producao_macharia(data_operacional desc, turno);

drop trigger if exists validar_area_descarte_macharia on public.descartes_producao_macharia;
create trigger validar_area_descarte_macharia before insert or update on public.descartes_producao_macharia
for each row execute function public.validar_acesso_producao_macharia();

alter table public.descartes_producao_macharia enable row level security;

drop policy if exists descartes_macharia_select on public.descartes_producao_macharia;
create policy descartes_macharia_select on public.descartes_producao_macharia for select to authenticated using(
  public.usuario_tem_permissao_producao_macharia('producao_macharia.visualizar')
  and public.usuario_pode_acessar_area_codigo('MACHARIA'));
drop policy if exists descartes_macharia_insert on public.descartes_producao_macharia;
create policy descartes_macharia_insert on public.descartes_producao_macharia for insert to authenticated with check(
  criado_por=auth.uid() and public.usuario_tem_permissao_producao_macharia('producao_macharia.lancar'));
drop policy if exists descartes_macharia_update on public.descartes_producao_macharia;
create policy descartes_macharia_update on public.descartes_producao_macharia for update to authenticated using(
  public.usuario_tem_permissao_producao_macharia('producao_macharia.editar'))
with check(public.usuario_tem_permissao_producao_macharia('producao_macharia.editar'));
grant select,insert,update on public.descartes_producao_macharia to authenticated;

grant usage,select on sequence public.descartes_producao_macharia_id_seq to authenticated;

-- ==========================================================================
-- RPCs (assinaturas mudam — precisam de drop antes do create or replace)
-- ==========================================================================
drop function if exists public.salvar_rascunho_turno_producao_macharia(date,text,jsonb,jsonb,bigint);

create or replace function public.salvar_rascunho_turno_producao_macharia(
  p_data_operacional date,
  p_turno text,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb,
  p_descartes jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_macharia%rowtype;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de macharia.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_typeof(coalesce(p_producoes,'[]'::jsonb))<>'array' or jsonb_typeof(coalesce(p_paradas,'[]'::jsonb))<>'array'
    or jsonb_typeof(coalesce(p_descartes,'[]'::jsonb))<>'array' then
    raise exception 'Rascunho inválido.';
  end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))>500 or jsonb_array_length(coalesce(p_paradas,'[]'::jsonb))>200
    or jsonb_array_length(coalesce(p_descartes,'[]'::jsonb))>200 then
    raise exception 'O rascunho excede o limite de linhas.';
  end if;

  insert into public.turnos_producao_macharia(data_operacional,turno,status,criado_por)
  values(p_data_operacional,p_turno,'ABERTO',auth.uid())
  on conflict(data_operacional,turno) do nothing;

  select * into v_turno from public.turnos_producao_macharia
  where data_operacional=p_data_operacional and turno=p_turno for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if (p_versao is null and v_turno.versao<>0) or (p_versao is not null and p_versao<>v_turno.versao) then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  update public.turnos_producao_macharia set
    rascunho_producoes=coalesce(p_producoes,'[]'::jsonb),
    rascunho_paradas=coalesce(p_paradas,'[]'::jsonb),
    rascunho_descartes=coalesce(p_descartes,'[]'::jsonb),
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id
  returning * into v_turno;

  return jsonb_build_object('id',v_turno.id,'versao',v_turno.versao,'atualizado_por',v_turno.atualizado_por,'atualizado_em',v_turno.atualizado_em);
end;
$$;
revoke all on function public.salvar_rascunho_turno_producao_macharia(date,text,jsonb,jsonb,jsonb,bigint) from public,anon;
grant execute on function public.salvar_rascunho_turno_producao_macharia(date,text,jsonb,jsonb,jsonb,bigint) to authenticated;

drop function if exists public.fechar_turno_producao_macharia(date,text,jsonb,jsonb,bigint);

create or replace function public.fechar_turno_producao_macharia(
  p_data_operacional date,
  p_turno text,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb,
  p_descartes jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_macharia%rowtype;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.lancar') then
    raise exception 'Usuário sem permissão para fechar o turno.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos um lançamento de sopro.'; end if;

  insert into public.turnos_producao_macharia(data_operacional,turno,status,criado_por)
  values(p_data_operacional,p_turno,'ABERTO',auth.uid())
  on conflict(data_operacional,turno) do nothing;

  select * into v_turno from public.turnos_producao_macharia
  where data_operacional=p_data_operacional and turno=p_turno for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if p_versao is not null and p_versao<>v_turno.versao then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_macharia(turno_producao_id,linha_maquina_id,estacao,data_operacional,turno,horario_previsto,macho_id,quantidade_sopros,criado_por)
  select v_turno.id,item.linha_id,item.estacao,p_data_operacional,p_turno,item.horario_previsto,item.macho_id,item.quantidade_sopros,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(linha_id bigint,estacao integer,horario_previsto timestamptz,macho_id bigint,quantidade_sopros integer)
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id and item.estacao between 1 and linha.numero_estacoes
  join public.machos_macharia macho on macho.id=item.macho_id and macho.status='APROVADO'
  where coalesce(item.quantidade_sopros,0)>=0 and item.horario_previsto is not null;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Um ou mais lançamentos são inválidos (máquina, estação ou macho).'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_macharia(turno_producao_id,linha_maquina_id,data_operacional,turno,categoria_id,setor_responsavel_id,motivo,inicio,fim,duracao_minutos,observacao,criado_por)
  select v_turno.id,item.linha_id,p_data_operacional,p_turno,item.categoria_id,item.setor_id,categoria.nome,item.inicio,item.fim,round(extract(epoch from(item.fim-item.inicio))/60)::integer,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(linha_id bigint,inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,observacao text)
  join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio and item.setor_id is not null;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais paradas possuem dados ou horários inválidos.'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_descartes,'[]'::jsonb));
  insert into public.descartes_producao_macharia(turno_producao_id,linha_maquina_id,data_operacional,turno,macho_id,quantidade_descartada,observacao,criado_por)
  select v_turno.id,item.linha_id,p_data_operacional,p_turno,item.macho_id,item.quantidade_descartada,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_descartes,'[]'::jsonb)) as item(linha_id bigint,macho_id bigint,quantidade_descartada integer,observacao text)
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id
  join public.machos_macharia macho on macho.id=item.macho_id
  where coalesce(item.quantidade_descartada,0)>0;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Um ou mais descartes possuem máquina ou macho inválidos.'; end if;

  update public.turnos_producao_macharia set
    status='FECHADO',fechado_por=auth.uid(),fechado_em=now(),
    rascunho_producoes='[]'::jsonb,rascunho_paradas='[]'::jsonb,rascunho_descartes='[]'::jsonb,
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id;
  return v_turno.id;
end;
$$;
revoke all on function public.fechar_turno_producao_macharia(date,text,jsonb,jsonb,jsonb,bigint) from public,anon;
grant execute on function public.fechar_turno_producao_macharia(date,text,jsonb,jsonb,jsonb,bigint) to authenticated;

drop function if exists public.editar_turno_producao_macharia(bigint,jsonb,jsonb);

create or replace function public.editar_turno_producao_macharia(
  p_turno_id bigint,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb,
  p_descartes jsonb default '[]'::jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_macharia%rowtype;
  v_anteriores jsonb;
  v_novos jsonb;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.editar') then
    raise exception 'Usuário sem permissão para editar turnos fechados.';
  end if;
  select * into v_turno from public.turnos_producao_macharia where id=p_turno_id and status='FECHADO' for update;
  if not found then raise exception 'Turno fechado não encontrado.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos um lançamento de sopro.'; end if;

  select jsonb_build_object(
    'productions',coalesce((select jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,estacao,horario_previsto) from public.registros_producao_macharia registro where turno_producao_id=p_turno_id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(parada)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,inicio) from public.paradas_producao_macharia parada where turno_producao_id=p_turno_id),'[]'::jsonb),
    'discards',coalesce((select jsonb_agg(to_jsonb(descarte)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,macho_id) from public.descartes_producao_macharia descarte where turno_producao_id=p_turno_id),'[]'::jsonb)
  ) into v_anteriores;

  delete from public.registros_producao_macharia where turno_producao_id=p_turno_id;
  delete from public.paradas_producao_macharia where turno_producao_id=p_turno_id;
  delete from public.descartes_producao_macharia where turno_producao_id=p_turno_id;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_macharia(turno_producao_id,linha_maquina_id,estacao,data_operacional,turno,horario_previsto,macho_id,quantidade_sopros,criado_por)
  select v_turno.id,item.linha_id,item.estacao,v_turno.data_operacional,v_turno.turno,item.horario_previsto,item.macho_id,item.quantidade_sopros,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(linha_id bigint,estacao integer,horario_previsto timestamptz,macho_id bigint,quantidade_sopros integer)
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id and item.estacao between 1 and linha.numero_estacoes
  join public.machos_macharia macho on macho.id=item.macho_id and macho.status='APROVADO'
  where coalesce(item.quantidade_sopros,0)>=0 and item.horario_previsto is not null;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Um ou mais lançamentos são inválidos (máquina, estação ou macho).'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_macharia(turno_producao_id,linha_maquina_id,data_operacional,turno,categoria_id,setor_responsavel_id,motivo,inicio,fim,duracao_minutos,observacao,criado_por)
  select v_turno.id,item.linha_id,v_turno.data_operacional,v_turno.turno,item.categoria_id,item.setor_id,categoria.nome,item.inicio,item.fim,round(extract(epoch from(item.fim-item.inicio))/60)::integer,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,linha_id bigint,observacao text)
  join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio and item.setor_id is not null;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais paradas possuem dados ou horários inválidos.'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_descartes,'[]'::jsonb));
  insert into public.descartes_producao_macharia(turno_producao_id,linha_maquina_id,data_operacional,turno,macho_id,quantidade_descartada,observacao,criado_por)
  select v_turno.id,item.linha_id,v_turno.data_operacional,v_turno.turno,item.macho_id,item.quantidade_descartada,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_descartes,'[]'::jsonb)) as item(linha_id bigint,macho_id bigint,quantidade_descartada integer,observacao text)
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id
  join public.machos_macharia macho on macho.id=item.macho_id
  where coalesce(item.quantidade_descartada,0)>0;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Um ou mais descartes possuem máquina ou macho inválidos.'; end if;

  select jsonb_build_object(
    'productions',coalesce((select jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,estacao,horario_previsto) from public.registros_producao_macharia registro where turno_producao_id=p_turno_id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(parada)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,inicio) from public.paradas_producao_macharia parada where turno_producao_id=p_turno_id),'[]'::jsonb),
    'discards',coalesce((select jsonb_agg(to_jsonb(descarte)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,macho_id) from public.descartes_producao_macharia descarte where turno_producao_id=p_turno_id),'[]'::jsonb)
  ) into v_novos;

  if v_anteriores=v_novos then raise exception 'Nenhuma alteração foi identificada.'; end if;

  update public.turnos_producao_macharia set atualizado_por=auth.uid(),atualizado_em=now() where id=v_turno.id;

  insert into public.historico_edicoes_turno_macharia(
    turno_producao_id,descricao,dados_anteriores,dados_novos,alterado_por
  ) values (
    p_turno_id,'os apontamentos do turno',v_anteriores,v_novos,auth.uid()
  );
  return p_turno_id;
end;
$$;
grant execute on function public.editar_turno_producao_macharia(bigint,jsonb,jsonb,jsonb) to authenticated;

create or replace function public.excluir_turno_producao_macharia(p_turno_id bigint)
returns void language plpgsql security definer
set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.excluir_turno') then
    raise exception 'Usuário sem permissão para excluir turnos de macharia.';
  end if;
  if not exists(select 1 from public.turnos_producao_macharia where id=p_turno_id and status='FECHADO') then
    raise exception 'Turno fechado não encontrado.';
  end if;
  delete from public.descartes_producao_macharia where turno_producao_id=p_turno_id;
  delete from public.paradas_producao_macharia where turno_producao_id=p_turno_id;
  delete from public.registros_producao_macharia where turno_producao_id=p_turno_id;
  delete from public.historico_edicoes_turno_macharia where turno_producao_id=p_turno_id;
  delete from public.turnos_producao_macharia where id=p_turno_id;
end;
$$;
grant execute on function public.excluir_turno_producao_macharia(bigint) to authenticated;

notify pgrst,'reload schema';

commit;
