begin;

alter table public.itens_checklist
 add column if not exists chave_especificacao text,
 add column if not exists fonte_limite_tipo text check(fonte_limite_tipo in('FICHA_TECNICA','INSTRUCAO_TRABALHO','FIXO')),
 add column if not exists fonte_limite_id bigint,
 add column if not exists fonte_limite_revisao text,
 add column if not exists fonte_limite_pagina integer;

alter table public.medicoes_checklist
 add column if not exists fonte_limite_tipo text,
 add column if not exists fonte_limite_id bigint,
 add column if not exists fonte_limite_codigo text,
 add column if not exists fonte_limite_revisao text,
 add column if not exists fonte_limite_pagina integer;

update public.itens_checklist item set chave_especificacao=m.chave,
 fonte_limite_tipo=case when item.valor_minimo is not null or item.valor_maximo is not null then 'FIXO' else item.fonte_limite_tipo end
from (values
 ('M02','04','COMPRESSIBILIDADE'),('V02','01','TEMPERATURA_OCU55'),
 ('V03','01','INOCULANTE_FAIXA'),('V03','05','INOCULANTE_RESULTADO'),
 ('F03','01','TEMPERATURA_FORNO'),('F03','02','CARBONO_EQUIVALENTE'),
 ('F04','03','CURVA_SINTERIZACAO_TEMPERATURA'),('F04','04','CURVA_SINTERIZACAO_CORRENTE'),
 ('F04','05','ISOLACAO_FORNO'),('MA03','01','DOSAGEM_AREIA'),
 ('MA03','02','DOSAGEM_RESINA_I'),('MA03','03','DOSAGEM_RESINA_II'),
 ('MA03','04','DOSAGEM_OXIDO_FERRO'),('MA04','03','TEMPERATURA_ESTUFA'),
 ('MA04','04','VELOCIDADE_ESTUFA'),('MA05','03','DENSIDADE_TINTA'),
 ('A02','04','AMPERAGEM_JATOS_1_2'),('A02','05','MIX_GRANALHA'),
 ('A03','04','AMPERAGEM_JATO_3')
) m(modelo,codigo,chave)
join public.modelos_checklist modelo on modelo.codigo=m.modelo
where item.modelo_id=modelo.id and item.codigo=m.codigo;

create table if not exists public.instrucoes_trabalho(
 id bigint generated by default as identity primary key,
 codigo text not null unique,
 titulo text not null,
 area_id bigint references public.areas_checklist(id),
 ativo boolean not null default true,
 criado_em timestamptz not null default now()
);

create table if not exists public.revisoes_instrucao_trabalho(
 id bigint generated by default as identity primary key,
 instrucao_id bigint not null references public.instrucoes_trabalho(id),
 revisao text not null,
 caminho_arquivo text not null,
 hash_arquivo text,
 status text not null default 'RASCUNHO' check(status in(
  'RASCUNHO','PENDENTE_APROVACAO','REJEITADA','VIGENTE','OBSOLETA')),
 etapa_aprovacao text check(etapa_aprovacao in('ENGENHARIA','PRODUCAO')),
 observacao text,
 elaborado_por uuid not null default auth.uid() references public.usuarios(id),
 criado_em timestamptz not null default now(),
 submetido_em timestamptz,
 vigente_em timestamptz,
 unique(instrucao_id,revisao),
 unique(hash_arquivo)
);

create table if not exists public.especificacoes_instrucao_trabalho(
 id bigint generated by default as identity primary key,
 revisao_id bigint not null references public.revisoes_instrucao_trabalho(id) on delete cascade,
 chave_parametro text not null,
 descricao text not null,
 produto_id bigint references public.produtos(id),
 equipamento text,
 valor_minimo numeric,
 valor_alvo numeric,
 valor_maximo numeric,
 unidade text,
 frequencia_minutos integer check(frequencia_minutos is null or frequencia_minutos>0),
 pagina integer check(pagina is null or pagina>0),
 trecho_origem text,
 criticidade text not null default 'NORMAL' check(criticidade in('NORMAL','CRITICA')),
 plano_reacao text,
 conferido boolean not null default false,
 unique(revisao_id,chave_parametro,produto_id,equipamento)
);

create table if not exists public.aprovacoes_instrucao_trabalho(
 id bigint generated by default as identity primary key,
 revisao_id bigint not null references public.revisoes_instrucao_trabalho(id) on delete cascade,
 etapa text not null check(etapa in('ENGENHARIA','PRODUCAO')),
 status text not null check(status in('PENDENTE','APROVADA','REJEITADA')),
 usuario_id uuid references public.usuarios(id),
 observacao text,
 decidido_em timestamptz,
 unique(revisao_id,etapa)
);

create index if not exists especificacoes_it_busca_idx on public.especificacoes_instrucao_trabalho(chave_parametro,equipamento,produto_id);

create or replace function public.registrar_fonte_medicao_checklist()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare item public.itens_checklist; doc_codigo text;
begin
 select * into item from public.itens_checklist where id=new.item_id;
 if item.fonte_limite_tipo='INSTRUCAO_TRABALHO' then
  select instrucao.codigo into doc_codigo from public.especificacoes_instrucao_trabalho spec
  join public.revisoes_instrucao_trabalho revisao on revisao.id=spec.revisao_id
  join public.instrucoes_trabalho instrucao on instrucao.id=revisao.instrucao_id
  where spec.id=item.fonte_limite_id;
 end if;
 new.fonte_limite_tipo:=item.fonte_limite_tipo;
 new.fonte_limite_id:=item.fonte_limite_id;
 new.fonte_limite_codigo:=doc_codigo;
 new.fonte_limite_revisao:=item.fonte_limite_revisao;
 new.fonte_limite_pagina:=item.fonte_limite_pagina;
 return new;
end $$;
drop trigger if exists medicoes_checklist_fonte_trigger on public.medicoes_checklist;
create trigger medicoes_checklist_fonte_trigger before insert on public.medicoes_checklist
for each row execute function public.registrar_fonte_medicao_checklist();

alter table public.instrucoes_trabalho enable row level security;
alter table public.revisoes_instrucao_trabalho enable row level security;
alter table public.especificacoes_instrucao_trabalho enable row level security;
alter table public.aprovacoes_instrucao_trabalho enable row level security;

create policy instrucoes_it_select on public.instrucoes_trabalho for select to authenticated using(public.usuario_tem_permissao_ficha('ficha.visualizar'));
create policy revisoes_it_select on public.revisoes_instrucao_trabalho for select to authenticated using(public.usuario_tem_permissao_ficha('ficha.visualizar'));
create policy especificacoes_it_select on public.especificacoes_instrucao_trabalho for select to authenticated using(public.usuario_tem_permissao_ficha('ficha.visualizar'));
create policy aprovacoes_it_select on public.aprovacoes_instrucao_trabalho for select to authenticated using(public.usuario_tem_permissao_ficha('ficha.visualizar'));

grant select on public.instrucoes_trabalho,public.revisoes_instrucao_trabalho,
 public.especificacoes_instrucao_trabalho,public.aprovacoes_instrucao_trabalho to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.salvar_revisao_instrucao_trabalho(
 p_codigo text,p_titulo text,p_area_id bigint,p_revisao text,p_caminho_arquivo text,
 p_hash_arquivo text,p_observacao text,p_especificacoes jsonb
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_instrucao_id bigint; v_revisao_id bigint; e jsonb;
begin
 if not (public.usuario_tem_permissao_ficha('ficha.criar') or public.usuario_tem_permissao_ficha('ficha.editar_rascunho')) then raise exception 'Usuário sem permissão para gerenciar IT.'; end if;
 if nullif(trim(p_codigo),'') is null or nullif(trim(p_revisao),'') is null or nullif(trim(p_caminho_arquivo),'') is null then
  raise exception 'Código, revisão e caminho do PDF são obrigatórios.';
 end if;
 if p_hash_arquivo is not null and exists(select 1 from public.revisoes_instrucao_trabalho where hash_arquivo=p_hash_arquivo) then
  raise exception 'Este mesmo arquivo PDF já foi cadastrado.';
 end if;
 insert into public.instrucoes_trabalho(codigo,titulo,area_id) values(upper(trim(p_codigo)),trim(p_titulo),p_area_id)
 on conflict(codigo) do update set titulo=excluded.titulo,area_id=excluded.area_id,ativo=true returning id into v_instrucao_id;
 insert into public.revisoes_instrucao_trabalho(instrucao_id,revisao,caminho_arquivo,hash_arquivo,observacao)
 values(v_instrucao_id,trim(p_revisao),trim(p_caminho_arquivo),nullif(trim(p_hash_arquivo),''),nullif(trim(p_observacao),'')) returning id into v_revisao_id;
 for e in select value from jsonb_array_elements(coalesce(p_especificacoes,'[]'::jsonb)) loop
  insert into public.especificacoes_instrucao_trabalho(revisao_id,chave_parametro,descricao,produto_id,equipamento,
   valor_minimo,valor_alvo,valor_maximo,unidade,frequencia_minutos,pagina,trecho_origem,criticidade,plano_reacao,conferido)
  values(v_revisao_id,upper(trim(e->>'chave_parametro')),trim(e->>'descricao'),nullif(e->>'produto_id','')::bigint,
   nullif(trim(e->>'equipamento'),''),nullif(e->>'valor_minimo','')::numeric,nullif(e->>'valor_alvo','')::numeric,
   nullif(e->>'valor_maximo','')::numeric,nullif(trim(e->>'unidade'),''),nullif(e->>'frequencia_minutos','')::integer,
   nullif(e->>'pagina','')::integer,nullif(trim(e->>'trecho_origem'),''),coalesce(nullif(e->>'criticidade',''),'NORMAL'),
   nullif(trim(e->>'plano_reacao'),''),coalesce((e->>'conferido')::boolean,false));
 end loop;
 return v_revisao_id;
end $$;

create or replace function public.enviar_instrucao_aprovacao(p_revisao_id bigint)
returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 if not (public.usuario_tem_permissao_ficha('ficha.criar') or public.usuario_tem_permissao_ficha('ficha.editar_rascunho')) then raise exception 'Usuário sem permissão.'; end if;
 if exists(select 1 from public.especificacoes_instrucao_trabalho where revisao_id=p_revisao_id and not conferido) then
  raise exception 'Todas as especificações devem ser conferidas antes do envio.';
 end if;
 update public.revisoes_instrucao_trabalho set status='PENDENTE_APROVACAO',etapa_aprovacao='ENGENHARIA',submetido_em=now()
 where id=p_revisao_id and status in('RASCUNHO','REJEITADA');
 if not found then raise exception 'A revisão não pode ser enviada nesta situação.'; end if;
 insert into public.aprovacoes_instrucao_trabalho(revisao_id,etapa,status) values(p_revisao_id,'ENGENHARIA','PENDENTE')
 on conflict(revisao_id,etapa) do update set status='PENDENTE',usuario_id=null,observacao=null,decidido_em=null;
 delete from public.aprovacoes_instrucao_trabalho where revisao_id=p_revisao_id and etapa='PRODUCAO';
 return p_revisao_id;
end $$;

create or replace function public.decidir_instrucao_trabalho(p_revisao_id bigint,p_resultado text,p_observacao text)
returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare r public.revisoes_instrucao_trabalho; permissao text; aprovador_engenharia uuid;
begin
 if p_resultado not in('APROVADA','REJEITADA') then raise exception 'Decisão inválida.'; end if;
 if p_resultado='REJEITADA' and nullif(trim(p_observacao),'') is null then raise exception 'Informe a justificativa.'; end if;
 select * into r from public.revisoes_instrucao_trabalho where id=p_revisao_id and status='PENDENTE_APROVACAO' for update;
 if r.id is null then raise exception 'A IT não está aguardando aprovação.'; end if;
 permissao:=case r.etapa_aprovacao when 'ENGENHARIA' then 'ficha.aprovar_engenharia' else 'ficha.aprovar_producao' end;
 if not public.usuario_tem_permissao_ficha(permissao) then raise exception 'Usuário sem permissão para esta etapa.'; end if;
 select usuario_id into aprovador_engenharia from public.aprovacoes_instrucao_trabalho where revisao_id=r.id and etapa='ENGENHARIA' and status='APROVADA';
 if r.etapa_aprovacao='PRODUCAO' and aprovador_engenharia=auth.uid() then raise exception 'Engenharia e Produção devem ser aprovadas por pessoas diferentes.'; end if;
 update public.aprovacoes_instrucao_trabalho set status=p_resultado,usuario_id=auth.uid(),observacao=nullif(trim(p_observacao),''),decidido_em=now()
 where revisao_id=r.id and etapa=r.etapa_aprovacao;
 if p_resultado='REJEITADA' then
  update public.revisoes_instrucao_trabalho set status='REJEITADA',etapa_aprovacao=null where id=r.id;
 elsif r.etapa_aprovacao='ENGENHARIA' then
  update public.revisoes_instrucao_trabalho set etapa_aprovacao='PRODUCAO' where id=r.id;
  insert into public.aprovacoes_instrucao_trabalho(revisao_id,etapa,status) values(r.id,'PRODUCAO','PENDENTE');
 else
  update public.revisoes_instrucao_trabalho old set status='OBSOLETA' from public.revisoes_instrucao_trabalho current
   where current.id=r.id and old.instrucao_id=current.instrucao_id and old.id<>current.id and old.status='VIGENTE';
  update public.revisoes_instrucao_trabalho set status='VIGENTE',etapa_aprovacao=null,vigente_em=now() where id=r.id;
  update public.itens_checklist item set
   valor_minimo=spec.valor_minimo,valor_alvo=spec.valor_alvo,valor_maximo=spec.valor_maximo,
   unidade=coalesce(spec.unidade,item.unidade),fonte_limite_tipo='INSTRUCAO_TRABALHO',
   fonte_limite_id=spec.id,fonte_limite_revisao=r.revisao,fonte_limite_pagina=spec.pagina
  from public.especificacoes_instrucao_trabalho spec
  where spec.revisao_id=r.id and spec.conferido and item.chave_especificacao=spec.chave_parametro
   and spec.produto_id is null and spec.equipamento is null
   and coalesce(item.fonte_limite_tipo,'INSTRUCAO_TRABALHO')<>'FICHA_TECNICA';
 end if;
 return r.id;
end $$;

create or replace function public.resolver_limite_instrucao_trabalho(p_chave text,p_produto_id bigint default null,p_equipamento text default null)
returns table(especificacao_id bigint,valor_minimo numeric,valor_alvo numeric,valor_maximo numeric,unidade text,
 fonte_codigo text,fonte_revisao text,fonte_pagina integer) language sql stable security definer set search_path=pg_catalog,public as $$
 select e.id,e.valor_minimo,e.valor_alvo,e.valor_maximo,e.unidade,i.codigo,r.revisao,e.pagina
 from public.especificacoes_instrucao_trabalho e join public.revisoes_instrucao_trabalho r on r.id=e.revisao_id
 join public.instrucoes_trabalho i on i.id=r.instrucao_id
 where r.status='VIGENTE' and e.conferido and e.chave_parametro=upper(trim(p_chave))
  and (e.produto_id is null or e.produto_id=p_produto_id)
  and (e.equipamento is null or upper(e.equipamento)=upper(p_equipamento))
 order by (e.produto_id is not null) desc,(e.equipamento is not null) desc,r.vigente_em desc limit 1
$$;

revoke all on function public.salvar_revisao_instrucao_trabalho(text,text,bigint,text,text,text,text,jsonb) from public,anon;
revoke all on function public.enviar_instrucao_aprovacao(bigint) from public,anon;
revoke all on function public.decidir_instrucao_trabalho(bigint,text,text) from public,anon;
grant execute on function public.salvar_revisao_instrucao_trabalho(text,text,bigint,text,text,text,text,jsonb) to authenticated;
grant execute on function public.enviar_instrucao_aprovacao(bigint),public.decidir_instrucao_trabalho(bigint,text,text),
 public.resolver_limite_instrucao_trabalho(text,bigint,text) to authenticated;

commit;
