begin;

-- Retirada de metal do Holding em panela — cada linha é uma panela retirada
-- de uma corrida do Holding, a caminho do vazamento. Sequencial reinicia a
-- cada corrida do Holding (pedido explícito). Status já nasce com todo o
-- ciclo de vida futuro (vazamento/rejeição/retorno — etapas seguintes do
-- roadmap), mas por enquanto só 'SAIDA_HOLDING' é produzido.
create table public.panelas_holding (
  id bigint generated by default as identity primary key,
  holding_corrida_id bigint not null references public.corridas_fusao(id),
  sequencial integer not null,
  produto_id bigint references public.produtos(id),
  hora_retirada timestamptz not null,
  peso_kg numeric not null check (peso_kg > 0),
  temperatura_c numeric,
  carbono_equivalente numeric,
  fesimg_liga1_kg numeric,
  fesimg_liga4_kg numeric,
  inoculante_kg numeric,
  silicio_kg numeric,
  grafite_kg numeric,
  sucata_cobertura_kg numeric,
  status text not null default 'SAIDA_HOLDING' check (status in (
    'SAIDA_HOLDING','EM_TRANSITO','RECEBIDA_VAZAMENTO','EM_VAZAMENTO','VAZADA',
    'REJEITADA','RETORNO_PENDENTE','RETORNADA'
  )),
  criado_por uuid references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  unique (holding_corrida_id, sequencial)
);

create index panelas_holding_corrida_idx on public.panelas_holding(holding_corrida_id);

alter table public.panelas_holding enable row level security;

-- Mesmo padrão das outras tabelas do módulo: leitura liberada pra quem tem
-- sessão (a tela já filtra pelas permissões de Fusão), escrita só via RPC.
create policy panelas_holding_select on public.panelas_holding
  for select to authenticated using (auth.uid() is not null);

grant select on public.panelas_holding to authenticated;

-- Cria a panela herdando da última panela válida (não rejeitada) desse
-- mesmo Holding — busca no banco, não depende do front ter os dados em
-- cache. Peso e hora são sempre da retirada atual (nunca herdados).
create or replace function public.criar_panela_holding(
  p_holding_corrida_id bigint, p_peso_kg numeric, p_hora_retirada timestamptz
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_corrida record;
  v_forno record;
  v_ultima record;
  v_sequencia integer;
  v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if coalesce(p_peso_kg, 0) <= 0 then raise exception 'Informe um peso maior que zero.'; end if;
  if p_hora_retirada is null then raise exception 'Informe o horário da retirada.'; end if;

  select * into v_corrida from public.corridas_fusao where id = p_holding_corrida_id for update;
  if not found then raise exception 'Corrida do Holding não encontrada.'; end if;
  if v_corrida.status <> 'ABERTA' then raise exception 'A corrida do Holding precisa estar aberta.'; end if;

  select * into v_forno from public.fornos_fusao where id = v_corrida.forno_id;
  if v_forno.tipo <> 'HOLDING' then raise exception 'Esta corrida não é de um Holding.'; end if;

  select coalesce(max(sequencial), 0) + 1 into v_sequencia
  from public.panelas_holding where holding_corrida_id = p_holding_corrida_id;

  select panela.* into v_ultima
  from public.panelas_holding panela
  join public.corridas_fusao corrida on corrida.id = panela.holding_corrida_id
  where corrida.forno_id = v_forno.id and panela.status <> 'REJEITADA'
  order by panela.criado_em desc limit 1;

  insert into public.panelas_holding(
    holding_corrida_id, sequencial, produto_id, hora_retirada, peso_kg,
    temperatura_c, carbono_equivalente, fesimg_liga1_kg, fesimg_liga4_kg,
    inoculante_kg, silicio_kg, grafite_kg, sucata_cobertura_kg, criado_por
  ) values (
    p_holding_corrida_id, v_sequencia, v_corrida.produto_id, p_hora_retirada, p_peso_kg,
    v_ultima.temperatura_c, v_ultima.carbono_equivalente, v_ultima.fesimg_liga1_kg, v_ultima.fesimg_liga4_kg,
    v_ultima.inoculante_kg, v_ultima.silicio_kg, v_ultima.grafite_kg, v_ultima.sucata_cobertura_kg, auth.uid()
  ) returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.criar_panela_holding(bigint,numeric,timestamptz) from public, anon;
grant execute on function public.criar_panela_holding(bigint,numeric,timestamptz) to authenticated;

-- Edição célula a célula (clica e altera) — campo vem de uma lista fixa,
-- sem SQL dinâmico livre.
create or replace function public.atualizar_campo_panela_holding(
  p_panela_id bigint, p_campo text, p_valor numeric
) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if not exists(select 1 from public.panelas_holding where id = p_panela_id) then
    raise exception 'Panela não encontrada.';
  end if;
  if p_campo not in (
    'peso_kg','temperatura_c','carbono_equivalente','fesimg_liga1_kg','fesimg_liga4_kg',
    'inoculante_kg','silicio_kg','grafite_kg','sucata_cobertura_kg'
  ) then
    raise exception 'Campo inválido.';
  end if;
  if p_campo = 'peso_kg' and coalesce(p_valor, 0) <= 0 then
    raise exception 'Peso precisa ser maior que zero.';
  end if;
  execute format('update public.panelas_holding set %I = $1, atualizado_por = auth.uid(), atualizado_em = now() where id = $2', p_campo)
    using p_valor, p_panela_id;
end;
$$;

revoke all on function public.atualizar_campo_panela_holding(bigint,text,numeric) from public, anon;
grant execute on function public.atualizar_campo_panela_holding(bigint,text,numeric) to authenticated;

create or replace function public.atualizar_hora_retirada_panela_holding(
  p_panela_id bigint, p_hora_retirada timestamptz
) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if p_hora_retirada is null then raise exception 'Informe o horário da retirada.'; end if;
  if not exists(select 1 from public.panelas_holding where id = p_panela_id) then
    raise exception 'Panela não encontrada.';
  end if;
  update public.panelas_holding set hora_retirada = p_hora_retirada, atualizado_por = auth.uid(), atualizado_em = now()
  where id = p_panela_id;
end;
$$;

revoke all on function public.atualizar_hora_retirada_panela_holding(bigint,timestamptz) from public, anon;
grant execute on function public.atualizar_hora_retirada_panela_holding(bigint,timestamptz) to authenticated;

-- Panela retirada já saiu fisicamente do Holding — abate o saldo do forno
-- na hora (mesmo padrão de escória/lingote/ajuste).
create or replace function public.volume_atual_forno_fusao(p_forno_id bigint)
returns numeric language sql stable set search_path = pg_catalog, public as $$
  select
    coalesce((
      select sum(item.quantidade_realizada_kg)
      from public.corridas_fusao_carga_itens item
      join public.corridas_fusao corrida on corrida.id = item.corrida_id
      where corrida.forno_id = p_forno_id
    ), 0)
    + coalesce((
      select sum(transferencia.quantidade_kg)
      from public.transferencias_fusao transferencia
      join public.corridas_fusao destino on destino.id = transferencia.corrida_destino_id
      where destino.forno_id = p_forno_id
    ), 0)
    - coalesce((
      select sum(transferencia.quantidade_kg)
      from public.transferencias_fusao transferencia
      join public.corridas_fusao origem on origem.id = transferencia.corrida_origem_id
      where origem.forno_id = p_forno_id
    ), 0)
    - coalesce((
      select sum(coalesce(corrida.escoria_kg, 0) + coalesce(corrida.lingote_kg, 0) + coalesce(corrida.ajuste_kg, 0))
      from public.corridas_fusao corrida
      where corrida.forno_id = p_forno_id
    ), 0)
    - coalesce((
      select sum(panela.peso_kg)
      from public.panelas_holding panela
      join public.corridas_fusao corrida on corrida.id = panela.holding_corrida_id
      where corrida.forno_id = p_forno_id
    ), 0);
$$;

notify pgrst, 'reload schema';

commit;
