begin;

-- ==========================================================================
-- Função de checagem de permissão do módulo (mesmo corpo usado em todos os
-- domínios de produção — ver usuario_tem_permissao_producao_acabamento).
-- Criada aqui pois a RPC de aval abaixo já depende dela; a migration seguinte
-- (turnos/registros de Macharia) reaproveita a mesma função.
-- ==========================================================================
create or replace function public.usuario_tem_permissao_producao_macharia(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select user_permission.permitido
     from public.usuario_permissoes user_permission
     join public.permissoes permission on permission.id=user_permission.permissao_id
     where user_permission.usuario_id=auth.uid()
       and permission.codigo=p_codigo limit 1),
    exists(select 1 from public.usuario_perfis user_profile
      join public.perfil_permissoes profile_permission
        on profile_permission.perfil_id=user_profile.perfil_id
      join public.permissoes permission
        on permission.id=profile_permission.permissao_id
      where user_profile.usuario_id=auth.uid() and permission.codigo=p_codigo)
  );
$$;
grant execute on function public.usuario_tem_permissao_producao_macharia(text) to authenticated;

-- ==========================================================================
-- Permissão de aval (Produção). Cadastro/edição reaproveita "produto.editar",
-- que já existe (Engenharia já tem essa permissão hoje).
-- ==========================================================================
insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'PRODUCAO',true from (values
  ('producao_macharia.avaliar_ficha_macho','Avaliar ficha de macho','Aprova ou reprova composições de macho propostas pela Engenharia.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id from public.perfis profile
cross join public.permissoes permission
where (upper(profile.codigo) in ('ADMIN','ADMINISTRADOR','GERENTE_PRODUCAO','COORDENADOR_PRODUCAO')
  or upper(profile.nome)='ADMINISTRADOR')
and permission.codigo='producao_macharia.avaliar_ficha_macho'
and not exists(select 1 from public.perfil_permissoes relation
  where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

-- ==========================================================================
-- Tabelas
-- ==========================================================================
-- "Caixa"/"Macho" ficam como texto livre: a planilha de referência mostra que
-- o mesmo rótulo (ex. "CX1") se repete em produtos sem nenhuma relação entre
-- si — não existe um catálogo físico de caixas a normalizar.
create table if not exists public.machos_macharia (
  id bigint generated by default as identity primary key,
  caixa text not null check (length(trim(caixa)) > 0),
  macho text not null check (length(trim(macho)) > 0),
  machos_por_sopro integer not null check (machos_por_sopro > 0),
  peso_macho_kg numeric check (peso_macho_kg > 0),
  kg_areia_por_sopro numeric check (kg_areia_por_sopro >= 0),
  sopro_por_hora numeric check (sopro_por_hora > 0),
  status text not null default 'RASCUNHO' check (status in ('RASCUNHO','APROVADO','REPROVADO')),
  ativo boolean not null default true,
  substitui_id bigint references public.machos_macharia(id),
  motivo_reprovacao text,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  avaliado_por uuid references public.usuarios(id),
  avaliado_em timestamptz
);

create index if not exists machos_macharia_status_idx
  on public.machos_macharia(status) where ativo;

-- Vínculo N:N: um macho pode alimentar mais de um produto final (o mesmo
-- macho sai de uma caixa e serve, por exemplo, tanto MS0103 quanto MS0105).
-- "Machos por peça" pertence a este vínculo, não ao macho em si.
create table if not exists public.machos_macharia_produtos (
  macho_id bigint not null references public.machos_macharia(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  machos_por_peca integer not null check (machos_por_peca > 0),
  primary key (macho_id, produto_id)
);

alter table public.machos_macharia enable row level security;
alter table public.machos_macharia_produtos enable row level security;

-- Catálogo compartilhado (mesmo padrão de tempos_ciclo_padrao): leitura aberta
-- a qualquer autenticado; toda escrita passa pelas RPCs abaixo (security
-- definer), que aplicam a regra de rascunho/aval — por isso não há policy de
-- insert/update/delete aqui.
drop policy if exists machos_macharia_select on public.machos_macharia;
create policy machos_macharia_select on public.machos_macharia
for select to authenticated using (auth.uid() is not null);
grant select on public.machos_macharia to authenticated;

drop policy if exists machos_macharia_produtos_select on public.machos_macharia_produtos;
create policy machos_macharia_produtos_select on public.machos_macharia_produtos
for select to authenticated using (auth.uid() is not null);
grant select on public.machos_macharia_produtos to authenticated;

grant usage,select on sequence public.machos_macharia_id_seq to authenticated;

-- ==========================================================================
-- RPCs
-- ==========================================================================
create or replace function public.salvar_ficha_macho(
  p_id bigint default null,
  p_caixa text default null,
  p_macho text default null,
  p_machos_por_sopro integer default null,
  p_peso_macho_kg numeric default null,
  p_kg_areia_por_sopro numeric default null,
  p_sopro_por_hora numeric default null,
  p_produtos jsonb default '[]'::jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_existente public.machos_macharia%rowtype;
  v_macho_id bigint;
  v_esperado integer;
  v_vinculado integer;
begin
  if not public.usuario_tem_permissao_produto('produto.editar') then
    raise exception 'Usuário sem permissão para editar a ficha de macho.';
  end if;
  if nullif(trim(coalesce(p_caixa,'')),'') is null or nullif(trim(coalesce(p_macho,'')),'') is null then
    raise exception 'Informe a caixa e o macho.';
  end if;
  if coalesce(p_machos_por_sopro,0)<=0 then raise exception 'Informe a quantidade de machos por sopro.'; end if;

  if p_id is not null then
    select * into v_existente from public.machos_macharia where id=p_id for update;
    if not found then raise exception 'Ficha de macho não encontrada.'; end if;
  end if;

  if v_existente.id is not null and v_existente.status='APROVADO' then
    -- Editar uma ficha vigente não sobrescreve: nasce uma nova versão em
    -- rascunho, e a vigente continua valendo até a nova ser avaliada.
    insert into public.machos_macharia(
      caixa,macho,machos_por_sopro,peso_macho_kg,kg_areia_por_sopro,sopro_por_hora,
      status,ativo,substitui_id,criado_por
    ) values (
      trim(p_caixa),trim(p_macho),p_machos_por_sopro,p_peso_macho_kg,p_kg_areia_por_sopro,p_sopro_por_hora,
      'RASCUNHO',false,v_existente.id,auth.uid()
    ) returning id into v_macho_id;
  elsif v_existente.id is not null then
    update public.machos_macharia set
      caixa=trim(p_caixa),macho=trim(p_macho),machos_por_sopro=p_machos_por_sopro,
      peso_macho_kg=p_peso_macho_kg,kg_areia_por_sopro=p_kg_areia_por_sopro,sopro_por_hora=p_sopro_por_hora,
      status='RASCUNHO',motivo_reprovacao=null,avaliado_por=null,avaliado_em=null
    where id=v_existente.id
    returning id into v_macho_id;
  else
    insert into public.machos_macharia(
      caixa,macho,machos_por_sopro,peso_macho_kg,kg_areia_por_sopro,sopro_por_hora,status,ativo,criado_por
    ) values (
      trim(p_caixa),trim(p_macho),p_machos_por_sopro,p_peso_macho_kg,p_kg_areia_por_sopro,p_sopro_por_hora,
      'RASCUNHO',false,auth.uid()
    ) returning id into v_macho_id;
  end if;

  delete from public.machos_macharia_produtos where macho_id=v_macho_id;
  v_esperado:=jsonb_array_length(coalesce(p_produtos,'[]'::jsonb));
  insert into public.machos_macharia_produtos(macho_id,produto_id,machos_por_peca)
  select v_macho_id,produto.id,item.machos_por_peca
  from jsonb_to_recordset(coalesce(p_produtos,'[]'::jsonb)) as item(produto_codigo text,machos_por_peca integer)
  join public.produtos produto on upper(trim(produto.codigo))=upper(trim(item.produto_codigo))
  where coalesce(item.machos_por_peca,0)>0;
  get diagnostics v_vinculado=row_count;
  if v_vinculado<>v_esperado then raise exception 'Um ou mais produtos informados são inválidos.'; end if;

  return v_macho_id;
end;
$$;
revoke all on function public.salvar_ficha_macho(bigint,text,text,integer,numeric,numeric,numeric,jsonb) from public,anon;
grant execute on function public.salvar_ficha_macho(bigint,text,text,integer,numeric,numeric,numeric,jsonb) to authenticated;

create or replace function public.avaliar_ficha_macho(
  p_id bigint,
  p_decisao text,
  p_justificativa text default null
) returns void
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_ficha public.machos_macharia%rowtype;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.avaliar_ficha_macho') then
    raise exception 'Usuário sem permissão para avaliar fichas de macho.';
  end if;
  if p_decisao not in ('APROVADO','REPROVADO') then raise exception 'Decisão inválida.'; end if;
  select * into v_ficha from public.machos_macharia where id=p_id and status='RASCUNHO' for update;
  if not found then raise exception 'Ficha em rascunho não encontrada.'; end if;

  if p_decisao='REPROVADO' then
    if nullif(trim(coalesce(p_justificativa,'')),'') is null then
      raise exception 'Informe o motivo da reprovação.';
    end if;
    update public.machos_macharia set
      status='REPROVADO',ativo=false,motivo_reprovacao=trim(p_justificativa),
      avaliado_por=auth.uid(),avaliado_em=now()
    where id=p_id;
    return;
  end if;

  if v_ficha.substitui_id is not null then
    update public.machos_macharia set ativo=false where id=v_ficha.substitui_id;
  end if;
  update public.machos_macharia set
    status='APROVADO',ativo=true,motivo_reprovacao=null,
    avaliado_por=auth.uid(),avaliado_em=now()
  where id=p_id;
end;
$$;
revoke all on function public.avaliar_ficha_macho(bigint,text,text) from public,anon;
grant execute on function public.avaliar_ficha_macho(bigint,text,text) to authenticated;

create or replace function public.importar_machos_macharia(p_linhas jsonb)
returns integer
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_linha record;
  v_existente public.machos_macharia%rowtype;
  v_macho_id bigint;
  v_esperado integer;
  v_vinculado integer;
  v_total integer:=0;
begin
  if not public.usuario_tem_permissao_produto('produto.editar') then
    raise exception 'Usuário sem permissão para editar a ficha de macho.';
  end if;
  if jsonb_typeof(coalesce(p_linhas,'[]'::jsonb))<>'array' then raise exception 'Importação inválida.'; end if;

  for v_linha in
    select * from jsonb_to_recordset(p_linhas) as item(
      caixa text,macho text,machos_por_sopro integer,peso_macho_kg numeric,
      kg_areia_por_sopro numeric,sopro_por_hora numeric,produtos jsonb
    )
  loop
    if nullif(trim(coalesce(v_linha.caixa,'')),'') is null or nullif(trim(coalesce(v_linha.macho,'')),'') is null
      or coalesce(v_linha.machos_por_sopro,0)<=0 then
      raise exception 'Linha de importação inválida (caixa/macho/machos por sopro).';
    end if;

    select * into v_existente from public.machos_macharia
    where status='APROVADO' and upper(trim(caixa))=upper(trim(v_linha.caixa)) and upper(trim(macho))=upper(trim(v_linha.macho))
    order by criado_em desc limit 1;

    if v_existente.id is not null then
      insert into public.machos_macharia(
        caixa,macho,machos_por_sopro,peso_macho_kg,kg_areia_por_sopro,sopro_por_hora,
        status,ativo,substitui_id,criado_por
      ) values (
        trim(v_linha.caixa),trim(v_linha.macho),v_linha.machos_por_sopro,v_linha.peso_macho_kg,
        v_linha.kg_areia_por_sopro,v_linha.sopro_por_hora,'RASCUNHO',false,v_existente.id,auth.uid()
      ) returning id into v_macho_id;
    else
      insert into public.machos_macharia(
        caixa,macho,machos_por_sopro,peso_macho_kg,kg_areia_por_sopro,sopro_por_hora,status,ativo,criado_por
      ) values (
        trim(v_linha.caixa),trim(v_linha.macho),v_linha.machos_por_sopro,v_linha.peso_macho_kg,
        v_linha.kg_areia_por_sopro,v_linha.sopro_por_hora,'RASCUNHO',false,auth.uid()
      ) returning id into v_macho_id;
    end if;

    v_esperado:=jsonb_array_length(coalesce(v_linha.produtos,'[]'::jsonb));
    insert into public.machos_macharia_produtos(macho_id,produto_id,machos_por_peca)
    select v_macho_id,produto.id,item.machos_por_peca
    from jsonb_to_recordset(coalesce(v_linha.produtos,'[]'::jsonb)) as item(produto_codigo text,machos_por_peca integer)
    join public.produtos produto on upper(trim(produto.codigo))=upper(trim(item.produto_codigo))
    where coalesce(item.machos_por_peca,0)>0;
    get diagnostics v_vinculado=row_count;
    if v_vinculado<>v_esperado then
      raise exception 'Produto inválido na linha de importação da caixa %, macho %.',v_linha.caixa,v_linha.macho;
    end if;

    v_total:=v_total+1;
  end loop;

  return v_total;
end;
$$;
revoke all on function public.importar_machos_macharia(jsonb) from public,anon;
grant execute on function public.importar_machos_macharia(jsonb) to authenticated;

notify pgrst,'reload schema';

commit;
