begin;

create table if not exists public.turnos_producao_moldes (
  id bigint generated by default as identity primary key,
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  status text not null default 'ABERTO' check (status in ('ABERTO','FECHADO')),
  fechado_por uuid references public.usuarios(id),
  fechado_em timestamptz,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  unique (data_operacional, turno),
  check ((status='ABERTO' and fechado_em is null) or
         (status='FECHADO' and fechado_em is not null and fechado_por is not null))
);

create table if not exists public.setores_responsaveis_parada (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

insert into public.setores_responsaveis_parada (codigo,nome) values
  ('PRODUCAO','Produção'),
  ('MANUTENCAO','Manutenção'),
  ('QUALIDADE','Qualidade'),
  ('PROCESSOS','Engenharia de Processos'),
  ('FUSAO','Fusão'),
  ('LOGISTICA','Logística'),
  ('PCP','PCP'),
  ('OUTROS','Outros')
on conflict (codigo) do update set nome=excluded.nome;

alter table public.registros_producao_moldes
  add column if not exists turno_producao_id bigint references public.turnos_producao_moldes(id),
  add column if not exists inicio timestamptz,
  add column if not exists fim timestamptz,
  add column if not exists moldes_vazados integer not null default 0 check (moldes_vazados>=0),
  add column if not exists moldes_quebrados integer not null default 0 check (moldes_quebrados>=0),
  add column if not exists pecas_por_molde numeric(12,3) check (pecas_por_molde>=0),
  add column if not exists peso_peca_kg numeric(14,4) check (peso_peca_kg>=0),
  add column if not exists total_pecas numeric(16,3) not null default 0 check (total_pecas>=0),
  add column if not exists toneladas_produzidas numeric(16,6) not null default 0 check (toneladas_produzidas>=0);

alter table public.paradas_producao_moldes
  add column if not exists turno_producao_id bigint references public.turnos_producao_moldes(id),
  add column if not exists setor_responsavel_id bigint references public.setores_responsaveis_parada(id);

drop index if exists public.producao_moldes_registro_natural_idx;

create index if not exists producao_moldes_turno_idx
  on public.registros_producao_moldes(turno_producao_id);
create index if not exists paradas_moldes_turno_idx
  on public.paradas_producao_moldes(turno_producao_id);

alter table public.turnos_producao_moldes enable row level security;
alter table public.setores_responsaveis_parada enable row level security;

create policy turnos_producao_select on public.turnos_producao_moldes
for select to authenticated using (
  public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
create policy setores_parada_select on public.setores_responsaveis_parada
for select to authenticated using (
  public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));

grant select on public.turnos_producao_moldes,
  public.setores_responsaveis_parada to authenticated;
grant usage,select on sequence public.turnos_producao_moldes_id_seq,
  public.setores_responsaveis_parada_id_seq to authenticated;

create or replace function public.fechar_turno_producao_moldes(
  p_data_operacional date,
  p_turno text,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno_id bigint;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_moldes('producao_moldes.lancar') then
    raise exception 'Usuário sem permissão para fechar o turno.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then
    raise exception 'Turno inválido.';
  end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then
    raise exception 'Informe ao menos uma linha de produção.';
  end if;

  insert into public.turnos_producao_moldes
    (data_operacional,turno,status,fechado_por,fechado_em,criado_por)
  values (p_data_operacional,p_turno,'FECHADO',auth.uid(),now(),auth.uid())
  on conflict (data_operacional,turno) do nothing
  returning id into v_turno_id;
  if v_turno_id is null then
    raise exception 'Este turno já foi apontado ou fechado.';
  end if;

  v_esperado := jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_moldes (
    turno_producao_id,data_operacional,turno,produto_id,inicio,fim,
    quantidade_planejada,quantidade_produzida,quantidade_aprovada,quantidade_refugada,
    moldes_vazados,moldes_quebrados,pecas_por_molde,peso_peca_kg,
    total_pecas,toneladas_produzidas,criado_por
  )
  select v_turno_id,p_data_operacional,p_turno,item.produto_id,item.inicio,item.fim,
    0,item.moldes_vazados+item.moldes_quebrados,item.moldes_vazados,item.moldes_quebrados,
    item.moldes_vazados,item.moldes_quebrados,produto.cavidades_molde,produto.peso_peca_kg,
    item.moldes_vazados*produto.cavidades_molde,
    item.moldes_vazados*produto.cavidades_molde*produto.peso_peca_kg/1000,
    auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(
    inicio timestamptz,fim timestamptz,produto_id bigint,
    moldes_vazados integer,moldes_quebrados integer
  ) join public.produtos produto on produto.id=item.produto_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio
    and item.moldes_vazados>=0 and item.moldes_quebrados>=0
    and produto.cavidades_molde is not null and produto.peso_peca_kg is not null;

  get diagnostics v_inserido = row_count;
  if v_inserido <> v_esperado then
    raise exception 'Uma ou mais produções são inválidas ou possuem produto sem peso/cavidades.';
  end if;

  v_esperado := jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_moldes (
    turno_producao_id,data_operacional,turno,categoria_id,setor_responsavel_id,
    motivo,inicio,fim,duracao_minutos,observacao,criado_por
  ) select v_turno_id,p_data_operacional,p_turno,item.categoria_id,item.setor_id,
    categoria.nome,item.inicio,item.fim,
    round(extract(epoch from (item.fim-item.inicio))/60)::integer,
    nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(
    inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,observacao text
  ) join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio
    and item.setor_id is not null;
  get diagnostics v_inserido = row_count;
  if v_inserido <> v_esperado then
    raise exception 'Uma ou mais paradas possuem dados ou horários inválidos.';
  end if;

  return v_turno_id;
end;
$$;

grant execute on function public.fechar_turno_producao_moldes(date,text,jsonb,jsonb)
to authenticated;

commit;
