begin;

create table if not exists public.tipos_ficha (
  codigo text primary key,
  nome text not null,
  descricao text,
  layout_id text not null,
  ordem_exibicao integer not null default 0,
  ativo boolean not null default true
);

alter table public.tipos_ficha enable row level security;

drop policy if exists tipos_ficha_select_authenticated
  on public.tipos_ficha;
create policy tipos_ficha_select_authenticated
  on public.tipos_ficha for select
  to authenticated
  using (auth.uid() is not null);

alter table public.grupos_parametros
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists tipo_layout text not null default 'BLOCOS',
  add column if not exists configuracao_visual jsonb not null default '{}'::jsonb;

alter table public.parametros
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists observacao text,
  add column if not exists critico boolean not null default false,
  add column if not exists caracteristica_especial boolean not null default false,
  add column if not exists destaque_visual text,
  add column if not exists observacao_cliente text,
  add column if not exists configuracao_visual jsonb not null default '{}'::jsonb;

alter table public.valores_parametros
  add column if not exists valor_inicial numeric,
  add column if not exists valor_final numeric,
  add column if not exists nao_aplicavel boolean not null default false;

alter table public.fichas_tecnicas
  add column if not exists elaborado_por_texto text,
  add column if not exists aprovado_engenharia_por_texto text,
  add column if not exists aprovado_processo_por_texto text;

-- Preserva cada regra de status existente e acrescenta somente IMPORTADA.
-- A ampliação é necessária para documentos históricos sem aprovação digital.
do $$
declare
  v_constraint record;
  v_definition text;
begin
  for v_constraint in
    select constraint_definition.conname,
      pg_catalog.pg_get_constraintdef(
        constraint_definition.oid,
        true
      ) as definition
    from pg_catalog.pg_constraint constraint_definition
    join pg_catalog.pg_attribute status_attribute
      on status_attribute.attrelid = constraint_definition.conrelid
      and status_attribute.attname = 'status'
      and status_attribute.attnum =
        any (constraint_definition.conkey)
    where constraint_definition.conrelid =
      'public.fichas_tecnicas'::regclass
      and constraint_definition.contype = 'c'
  loop
    v_definition := substring(
      v_constraint.definition
      from 7
    );

    execute format(
      'alter table public.fichas_tecnicas drop constraint %I',
      v_constraint.conname
    );
    execute format(
      'alter table public.fichas_tecnicas add constraint %I check ((%s) or status = ''IMPORTADA'')',
      v_constraint.conname,
      v_definition
    );
  end loop;
end;
$$;

alter table public.aprovacoes_ficha
  add column if not exists nome_responsavel text,
  add column if not exists observacao text,
  add column if not exists ordem integer not null default 0,
  add column if not exists assinatura_eletronica boolean not null default false;

create table if not exists public.historico_fichas (
  id bigint generated by default as identity primary key,
  ficha_tecnica_id bigint not null
    references public.fichas_tecnicas(id) on delete cascade,
  numero_revisao integer not null,
  data_revisao date,
  descricao text,
  responsavel text,
  usuario_id uuid references public.usuarios(id),
  criado_em timestamptz not null default now(),
  unique (ficha_tecnica_id, numero_revisao)
);

alter table public.historico_fichas enable row level security;

drop policy if exists historico_fichas_select_authenticated
  on public.historico_fichas;
create policy historico_fichas_select_authenticated
  on public.historico_fichas for select
  to authenticated
  using (auth.uid() is not null);

create unique index if not exists grupos_parametros_tipo_codigo_uidx
  on public.grupos_parametros(tipo_ficha, codigo)
  where codigo is not null;
create unique index if not exists parametros_grupo_codigo_uidx
  on public.parametros(grupo_id, codigo)
  where codigo is not null;
create unique index if not exists fichas_produto_tipo_revisao_uidx
  on public.fichas_tecnicas(produto_id, tipo, numero_revisao);

insert into public.tipos_ficha (
  codigo, nome, descricao, layout_id, ordem_exibicao, ativo
) values
  ('MOLDAGEM', 'Moldagem', 'Parâmetros de preparação e produção dos moldes.', 'moldagem_v1', 10, true),
  ('FUSAO_VAZAMENTO', 'Fusão / Vazamento', 'Metalurgia, composição e vazamento.', 'fusao_vazamento_v1', 20, true),
  ('MACHARIA', 'Macharia', 'Produção e controle de machos.', 'macharia_v1', 30, true),
  ('ACABAMENTO', 'Acabamento', 'Operações de acabamento.', 'acabamento_v1', 40, true),
  ('LABORATORIO', 'Laboratório', 'Ensaios e requisitos laboratoriais.', 'laboratorio_v1', 50, true)
on conflict (codigo) do update set
  nome = excluded.nome,
  descricao = excluded.descricao,
  layout_id = excluded.layout_id,
  ordem_exibicao = excluded.ordem_exibicao,
  ativo = excluded.ativo;

do $$
declare
  v_cliente_id bigint;
  v_produto_id bigint;
  v_usuario_id uuid;
  v_ficha_moldagem bigint;
  v_ficha_fusao bigint;
begin
  select id into v_usuario_id
  from public.usuarios
  where status = 'ATIVO'
  order by id
  limit 1;

  if v_usuario_id is null then
    raise exception 'É necessário ao menos um usuário ATIVO para importar as fichas MS0013.';
  end if;

  select id into v_cliente_id
  from public.clientes
  where lower(nome) = lower('Astemo')
  order by id
  limit 1;

  if v_cliente_id is null then
    insert into public.clientes (nome, ativo)
    values ('Astemo', true)
    returning id into v_cliente_id;
  end if;

  select id into v_produto_id
  from public.produtos
  where lower(codigo) = lower('MS0013')
  order by id
  limit 1;

  if v_produto_id is null then
    insert into public.produtos (
      codigo, nome, cliente_id, codigo_cliente, codigo_ferramental,
      peca_seguranca, peso_peca_kg, cavidades_molde, peso_cacho_kg,
      rendimento_metalico_pct, status, criado_por
    ) values (
      'MS0013', 'Tambor de Freio', v_cliente_id, '067HB20',
      'MS0013-PLACA', true, 6.82, 6, 67.55, 60.58, 'ATIVO',
      v_usuario_id
    )
    returning id into v_produto_id;
  else
    update public.produtos
    set nome = coalesce(nullif(nome, ''), 'Tambor de Freio'),
        cliente_id = coalesce(cliente_id, v_cliente_id),
        codigo_cliente = coalesce(nullif(codigo_cliente, ''), '067HB20'),
        codigo_ferramental = coalesce(nullif(codigo_ferramental, ''), 'MS0013-PLACA'),
        peso_peca_kg = coalesce(peso_peca_kg, 6.82),
        cavidades_molde = coalesce(cavidades_molde, 6),
        peso_cacho_kg = coalesce(peso_cacho_kg, 67.55),
        rendimento_metalico_pct = coalesce(rendimento_metalico_pct, 60.58),
        peca_seguranca = coalesce(peca_seguranca, true)
    where id = v_produto_id;
  end if;

  insert into public.fichas_tecnicas (
    produto_id, tipo, codigo_documento, numero_revisao, status,
    vigente, elaborado_por, motivo_revisao, data_emissao,
    elaborado_por_texto, aprovado_engenharia_por_texto,
    aprovado_processo_por_texto
  ) values (
    v_produto_id, 'MOLDAGEM', 'FTMO-0013', 22, 'IMPORTADA',
    true, v_usuario_id, 'Importação controlada da ficha física.', '2026-06-19',
    null, null, null
  )
  on conflict (produto_id, tipo, numero_revisao) do update set
    codigo_documento = excluded.codigo_documento,
    data_emissao = excluded.data_emissao,
    status = 'IMPORTADA',
    vigente = true
  returning id into v_ficha_moldagem;

  insert into public.fichas_tecnicas (
    produto_id, tipo, codigo_documento, numero_revisao, status,
    vigente, elaborado_por, motivo_revisao, data_emissao,
    elaborado_por_texto, aprovado_engenharia_por_texto,
    aprovado_processo_por_texto
  ) values (
    v_produto_id, 'FUSAO_VAZAMENTO', 'FTFV-13', 56, 'IMPORTADA',
    true, v_usuario_id, 'Importação controlada da ficha física.', '2026-07-10',
    'Luiz Philippe', 'David Moreira', null
  )
  on conflict (produto_id, tipo, numero_revisao) do update set
    codigo_documento = excluded.codigo_documento,
    data_emissao = excluded.data_emissao,
    status = 'IMPORTADA',
    vigente = true,
    elaborado_por_texto = 'Luiz Philippe',
    aprovado_engenharia_por_texto = 'David Moreira',
    aprovado_processo_por_texto = null
  returning id into v_ficha_fusao;

  create temporary table seed_grupos (
    tipo text, codigo text, nome text, ordem integer, layout text, descricao text
  ) on commit drop;

  insert into seed_grupos values
    ('MOLDAGEM','MOLD_DADOS_MODELO','DADOS DO MODELO',1,'BLOCOS',null),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','VELOCIDADE DO ASSENTAMENTO DE MACHOS',2,'TABELA',null),
    ('MOLDAGEM','MOLD_CORRECAO_CAMARA','CORREÇÃO DA CÂMARA',3,'TABELA',null),
    ('MOLDAGEM','MOLD_FLUIDO_DESMOLDADOR','FLUIDO DESMOLDADOR',4,'TABELA',null),
    ('MOLDAGEM','MOLD_JATO_AREIA','JATO DE AREIA',5,'TABELA',null),
    ('MOLDAGEM','MOLD_TEMPERATURA','TEMPERATURA',6,'TABELA',null),
    ('MOLDAGEM','MOLD_COMPRESSAO','COMPRIMINDO – COMPRESSÃO DO MOLDE',7,'TABELA',null),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','BOCAL DE SOPRO',8,'TABELA',null),
    ('MOLDAGEM','MOLD_EXTRACAO','EXTRAÇÃO DO MOLDE',9,'TABELA',null),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','SOBREPOSIÇÕES DO DM',10,'TABELA',null),
    ('MOLDAGEM','MOLD_FECHAMENTO','FECHAMENTO DO MOLDE',11,'TABELA',null),
    ('MOLDAGEM','MOLD_SHUTTLE','RESFRIAMENTO DOS MOLDES – SHUTTLE',12,'TABELA',null),
    ('MOLDAGEM','MOLD_TRANSPORTE','TRANSPORTE DO MOLDE',13,'TABELA',null),
    ('MOLDAGEM','MOLD_AJUSTE_MACHOS','AJUSTE DO ASSENTAMENTO DE MACHOS',14,'TABELA',null),
    ('MOLDAGEM','MOLD_RECOMENDACOES','RECOMENDAÇÕES IMPORTANTES',15,'BLOCOS',
      'Espessura do molde: de 480 a 510 mm. Observar trincas laterais após o vazamento. Ajustar parâmetros da máquina. Verificar areia e compactabilidade. Atentar ao preenchimento das cavidades PP e SP. Verificar a completa limpeza do molde.'),
    ('MOLDAGEM','MOLD_HISTORICO','HISTÓRICO DAS REVISÕES',16,'HISTORICO',null),
    ('MOLDAGEM','MOLD_APROVACOES','APROVAÇÕES',17,'APROVACAO',null),
    ('FUSAO_VAZAMENTO','FV_ESPECIFICACOES','ESPECIFICAÇÕES DO PROCESSO',1,'BLOCOS',null),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','MATRIZ E PROPRIEDADES MECÂNICAS',2,'TABELA',null),
    ('FUSAO_VAZAMENTO','FV_FORNO','COMPOSIÇÃO QUÍMICA NO FORNO – ORIENTATIVO',3,'MATRIZ',null),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','COMPOSIÇÃO QUÍMICA DO VAZAMENTO',4,'MATRIZ',null),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','INOCULAÇÃO',5,'TABELA',null),
    ('FUSAO_VAZAMENTO','FV_NODULARIZACAO','NODULARIZAÇÃO / PESO DE METAL',6,'TABELA',null),
    ('FUSAO_VAZAMENTO','FV_TEMPERATURAS','TEMPERATURAS',7,'TABELA',null),
    ('FUSAO_VAZAMENTO','FV_ANALISE_TERMICA','ANÁLISE TÉRMICA',8,'BLOCOS','Valores pendentes de conferência na ficha original.'),
    ('FUSAO_VAZAMENTO','FV_RECOMENDACOES','RECOMENDAÇÕES IMPORTANTES',9,'BLOCOS',
      'O local de medição da temperatura de vazamento deverá ser próximo ao stopper. Valores em vermelho indicam parâmetros críticos ou requisitos específicos do cliente.'),
    ('FUSAO_VAZAMENTO','FV_HISTORICO','HISTÓRICO DAS REVISÕES',10,'HISTORICO',null),
    ('FUSAO_VAZAMENTO','FV_APROVACOES','APROVAÇÕES',11,'APROVACAO',null);

  insert into public.grupos_parametros (
    tipo_ficha, codigo, nome, descricao, ordem_exibicao, ativo, tipo_layout
  )
  select tipo, codigo, nome, descricao, ordem, true, layout
  from seed_grupos
  on conflict (tipo_ficha, codigo) where codigo is not null
  do update set nome=excluded.nome, descricao=excluded.descricao,
    ordem_exibicao=excluded.ordem_exibicao, tipo_layout=excluded.tipo_layout,
    ativo=true;

  create temporary table seed_parametros (
    tipo text, grupo text, codigo text, nome text, unidade text,
    tipo_dado text, faixa boolean, opcoes jsonb, ordem integer,
    valor numeric, minimo numeric, alvo numeric, maximo numeric,
    texto text, booleano boolean, inicial numeric, final numeric,
    nao_aplicavel boolean, observacao text, critico boolean
  ) on commit drop;

  insert into seed_parametros values
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_031_ESPESSURA_PLACA_PP','31 – Espessura da placa modelo PP','mm','NUMERO',false,null,31,70,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_032_ALTURA_MODELO_PP','32 – Altura do modelo PP','mm','NUMERO',false,null,32,100,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_033_ESPESSURA_PLACA_SP','33 – Espessura da placa modelo SP','mm','NUMERO',false,null,33,30,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_034_ALTURA_MODELO_SP','34 – Altura do modelo SP','mm','NUMERO',false,null,34,100,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_035_DISTANCIA_PLACAS','35 – Distância mínima entre placas de aquecimento','mm','NUMERO',false,null,35,300,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_036_ESPESSURA_MASCARA','36 – Espessura da máscara de machos','mm','NUMERO',false,null,36,160,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_037_ALTURA_MACHO_EXTERNA','37 – Altura do macho – máscara externa','mm','NUMERO',false,null,37,55,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_038_ALTURA_MACHO_INTERNA','38 – Altura do macho – máscara interna','mm','NUMERO',false,null,38,25,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_NUMERO_MACHOS','Número de machos por molde',null,'TEXTO',false,null,39,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_FILTRO_CERAMICO','Filtro cerâmico',null,'TEXTO',false,null,40,null,null,null,null,'01 un. 15x75x22 20PPI',null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_DADOS_MODELO','MOLD_MAQUINA','Máquina',null,'TEXTO',false,null,41,null,null,null,null,'DISA',null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_CORRECAO_CAMARA','MOLD_041_CORRECAO_ESPESSURA','41 – Correção da espessura nominal do molde','mm','NUMERO',true,null,41,140,120,null,170,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_CORRECAO_CAMARA','MOLD_042_POSICAO_CAMARA','42 – Correção da posição do molde na câmara','mm','NUMERO',true,null,42,0,-10,null,30,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_CORRECAO_CAMARA','MOLD_043_POSICAO_3A','43 – Correção da posição final da operação 3A','mm','NUMERO',true,null,43,0,-10,null,10,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_JATO_AREIA','MOLD_051_PRESSAO_JATO_AREIA','51 – Pressão do jato de areia','bar','NUMERO',true,null,51,2,2,null,4,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_JATO_AREIA','MOLD_052_TEMPO_JATO','52 – Correção do tempo de jato','s','NUMERO',true,null,52,0,0,null,2,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_JATO_AREIA','MOLD_053_NIVEL_AREIA','53 – Nível de areia no silo','%','NUMERO',true,null,53,90,80,null,95,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_JATO_AREIA','MOLD_057_VALVULAS','57 – Válvulas do jato de areia ativas',null,'NUMERO',false,null,57,2,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_COMPRESSAO','MOLD_061_PRESSAO_COMPRESSAO','61 – Pressão de compressão 3A','bar','NUMERO',true,null,61,1.2,1.4,null,1.4,null,null,null,null,false,'Valor nominal histórico fora da faixa informada.',false),
    ('MOLDAGEM','MOLD_COMPRESSAO','MOLD_062_TEMPO_COMPRESSAO','62 – Tempo de prorrogação de compressão','s','NUMERO',true,null,62,0,0,null,2,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_COMPRESSAO','MOLD_063_COMPRESSIBILIDADE_MIN','63 – Compressibilidade mínima','%','NUMERO',false,null,63,18,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_COMPRESSAO','MOLD_064_COMPRESSIBILIDADE_MAX','64 – Compressibilidade máxima','%','NUMERO',false,null,64,21,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_COMPRESSAO','MOLD_065_COMPRESSAO_SP','65 – Compressão da SP ardida','%','NUMERO',true,null,65,0,0,null,5,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_COMPRESSAO','MOLD_066_VELOCIDADE_COMPRESSAO','66 – Velocidade de compressão','mm/s','NUMERO',true,null,66,150,120,null,150,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_EXTRACAO','MOLD_071_OPERACAO_3AB','71 – Seleção de operação 3AB',null,'LISTA',false,'["3A","3B"]',71,null,null,null,null,'3A',null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_EXTRACAO','MOLD_072_ACELERACAO_PP','72 – Aceleração de extração da PP','mm/s²','NUMERO',true,null,72,500,400,null,500,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_EXTRACAO','MOLD_073_DISTANCIA_PP','73 – Distância de extração da PP','mm','NUMERO',true,null,73,5,5,null,20,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_EXTRACAO','MOLD_075_ACELERACAO_SP','75 – Aceleração de extração da SP','mm/s²','NUMERO',true,null,75,500,400,null,500,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_EXTRACAO','MOLD_076_DISTANCIA_SP','76 – Distância de extração da SP','mm','NUMERO',true,null,76,5,5,null,20,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FECHAMENTO','MOLD_081_FORCA_FECHAMENTO','81 – Força de fechamento','kp','NUMERO',true,null,81,1600,1500,null,2000,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FECHAMENTO','MOLD_082_POSICAO_FECHAMENTO','82 – Correção da posição de fechamento','mm','NUMERO',true,null,82,-13,-20,null,20,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FECHAMENTO','MOLD_083_TEMPO_TENTOR','83 – Tempo prolongado do tentor do molde','s','NUMERO',true,null,83,0,0,null,1,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FECHAMENTO','MOLD_084_PRESSAO_TENTOR','84 – Pressão do tentor do molde','bar','NUMERO',true,null,84,5,3,null,5,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FECHAMENTO','MOLD_085_DESACELERACAO','85 – Desaceleração do fechamento','%','NUMERO',true,null,85,80,40,null,100,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_TRANSPORTE','MOLD_091_POSICAO_ENTREGA','91 – Correção da posição de entrega','mm','NUMERO',true,null,91,0,-10,null,30,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_TRANSPORTE','MOLD_092_ACELERACAO_TRANSPORTE','92 – Aceleração durante o transporte do molde','%','NUMERO',true,null,92,80,70,null,100,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_TRANSPORTE','MOLD_093_DESACELERACAO_TRANSPORTE','93 – Desaceleração durante o transporte do molde','%','NUMERO',true,null,93,80,70,null,100,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_AJUSTE_MACHOS','MOLD_101_MODO_AJUSTE','101 – Seleção do modo de ajuste do macho',null,'LISTA',false,'["CSE"]',101,null,null,null,null,'CSE',null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_AJUSTE_MACHOS','MOLD_102_RETENTORES','102 – Seleção de retentores de núcleo',null,'BOOLEANO',false,null,102,null,null,null,null,null,false,null,null,false,null,false),
    ('MOLDAGEM','MOLD_AJUSTE_MACHOS','MOLD_103_VACUO_SEM_NUCLEOS','103 – Nível de vácuo sem núcleos em máscara de núcleos','%','NUMERO',true,null,103,0,0,null,99.9,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_AJUSTE_MACHOS','MOLD_104_VACUO_COM_NUCLEOS','104 – Nível de vácuo com núcleos em máscara de núcleos','%','NUMERO',true,null,104,0,0,null,99.9,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_111_VELOCIDADE_FRENTE','111 – Velocidade para frente com núcleos – Est. 143','%','NUMERO',true,null,111,80,60,null,80,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_112_VELOCIDADE_DENTRO','112 – Velocidade para dentro com machos – Est. 2','%','NUMERO',true,null,112,80,60,null,80,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_113_POSICAO_AJUSTES','113 – Correção posição dos ajustes macho – Est. 4','mm','NUMERO',true,null,113,-4,-10,null,10,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_114_FORCA_AJUSTE','114 – Força de ajuste de macho – Estágio 4','kp','NUMERO',true,null,114,70,50,null,110,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_115_TEMPO_AJUSTE','115 – Tempo de ajuste de macho – Estágio 4','s','NUMERO',true,null,115,0,0,null,1.5,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_116_AR_EXTRACAO','116 – Ar de extração do macho – Estágio 5',null,'BOOLEANO',false,null,116,null,null,null,null,null,true,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_117_TEMPO_EXTRACAO','117 – Tempo de extração do macho – Estágio 5','s','NUMERO',true,null,117,0,0,null,1.5,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_118_ACELERACAO_DESMOLDAGEM','118 – Aceleração de desmoldagem – Estágio 6','%','NUMERO',true,null,118,80,60,null,80,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_VELOCIDADE_MACHOS','MOLD_119_DISTANCIA_DESMOLDAGEM','119 – Distância de desmoldagem – Estágio 6','mm','NUMERO',true,null,119,0,0,null,50,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FLUIDO_DESMOLDADOR','MOLD_121_FREQUENCIA_SPRAY','121 – Frequência de spray','moldes','NUMERO',true,null,121,1,1,null,3,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FLUIDO_DESMOLDADOR','MOLD_122_TEMPO_SPRAY','122 – Tempo de spray','s','NUMERO',true,null,122,0.3,0.1,null,1,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FLUIDO_DESMOLDADOR','MOLD_123_POSICAO_SP','123 – Posição SP início aplicação desmoldante','mm','NUMERO',true,null,123,1200,1100,null,1300,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FLUIDO_DESMOLDADOR','MOLD_124_BICOS','124 – Ativação dos bicos de borrifação',null,'LISTA',false,'["Frente"]',124,null,null,null,null,'Frente',null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_FLUIDO_DESMOLDADOR','MOLD_125_PRESSAO_AR','125 – Atomizador pressão do ar','bar','NUMERO',true,null,125,3,2,null,5,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_TEMPERATURA','MOLD_131_TEMPERATURA_MOLDE_PP','131 – Temperatura do molde PP','°C','NUMERO',true,null,131,50,50,null,60,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_TEMPERATURA','MOLD_132_TEMPERATURA_MOLDE_SP','132 – Temperatura do molde SP','°C','NUMERO',true,null,132,50,50,null,60,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_141_SOPRO_SP_3_FRENTE','141 – Sopro SP na operação 3 frente iniciar/parar','mm','NUMERO',false,null,141,null,null,null,null,null,null,1000,1950,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_142_SOPRO_SP_3_INFERIOR','142 – Sopro SP na operação 3 inferior iniciar/parar','mm','NUMERO',false,null,142,null,null,null,null,null,null,1000,1950,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_143_SOPRO_SP_5_FRENTE','143 – Sopro SP na operação 5 frente iniciar/parar','mm','NUMERO',false,null,143,null,null,null,null,null,null,1950,1000,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_144_SOPRO_SP_5_INFERIOR','144 – Sopro SP na operação 5 inferior iniciar/parar','mm','NUMERO',false,null,144,null,null,null,null,null,null,1950,1000,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_145_SOPRO_TOPO','145 – Sopro no topo da SP na operação 3',null,'BOOLEANO',false,null,145,null,null,null,null,null,true,null,null,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_146_SOPRO_FRENTE','146 – Sopro na frente do molde na operação 4A',null,'BOOLEANO',false,null,146,null,null,null,null,null,true,null,null,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_147_SOPRO_SUPERFICIE','147 – Sopro na superfície do molde e nos machos',null,'LISTA',false,'["Dentro e fora"]',147,null,null,null,null,'Dentro e fora',null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_BOCAL_SOPRO','MOLD_148_SOPRO_LATERAL','148 – Sopro lateral superior do molde iniciar/parar','mm','NUMERO',false,null,148,null,null,null,null,null,null,1000,1950,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_151_SOBREPOSICAO_3B_4A','151 – Sobreposição operações 3B e 4A do DM',null,'BOOLEANO',false,null,151,null,null,null,null,null,true,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_152_SOBREPOSICAO_4_5','152 – Sobreposição operações 4 e 5 do DM',null,'BOOLEANO',false,null,152,null,null,null,null,null,true,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_153_SOBREPOSICAO_5_4','153 – Sobreposição operações 5 e 4 do DM',null,'BOOLEANO',false,null,153,null,null,null,null,null,true,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_154_VELOCIDADE_CAMES','154 – Velocidade das cames – operações 3 e 6 DM',null,'NUMERO',false,null,154,50,null,null,null,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_155_SOBREPOSICAO_3_6','155 – Sobreposição operações 3 e 6 DM + CSE',null,'BOOLEANO',false,null,155,null,null,null,null,null,false,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_156_SOBREPOSICAO_1_2_3','156 – Sobreposição operações 1 e 2 + 3 do CSE',null,'BOOLEANO',false,null,156,null,null,null,null,null,false,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SOBREPOSICOES','MOLD_157_SOBREPOSICAO_6_7B','157 – Sobreposição operações 6 e 7B do CSE',null,'BOOLEANO',false,null,157,null,null,null,null,null,false,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SHUTTLE','MOLD_201_TEMPO_CICLO_PMC','201 – Tempo de ciclo PMC','s','NUMERO',true,null,201,9,null,null,15,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SHUTTLE','MOLD_202_CURSO_PMC','202 – Curso do PMC','mm','NUMERO',true,null,202,2100,2100,null,2100,null,null,null,null,false,null,false),
    ('MOLDAGEM','MOLD_SHUTTLE','MOLD_TEMPO_SHUTTLE','Tempo de permanência dos moldes no Shuttle','min','NUMERO',false,null,203,40,null,null,null,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_ESPECIFICACOES','FV_TIPO_MATERIAL','Tipo de material',null,'TEXTO',false,null,1,null,null,null,null,'Cinzento',null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_ESPECIFICACOES','FV_NORMA_CLIENTE','Norma do cliente',null,'TEXTO',false,null,2,null,null,null,null,'FC250D',null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_ESPECIFICACOES','FV_NORMA_EQUIVALENTE','Norma equivalente',null,'TEXTO',false,null,3,null,null,null,null,'C25',null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_PERLITA','Perlita','%','NUMERO',true,null,1,null,95,null,null,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_FERRITA','Ferrita','%','NUMERO',true,null,2,null,null,null,5,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_CARBONETOS','Carbonetos','%','NUMERO',true,null,3,null,null,null,5,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_GRAFITA_TIPO','Grafita – tipo',null,'TEXTO',false,null,4,null,null,null,null,'A ≥ 80%; B + D ≤ 20%',null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_GRAFITA_TAMANHO','Grafita – tamanho',null,'TEXTO',false,null,5,null,null,null,null,'3 a 6',null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_RESISTENCIA_TRACAO','Limite de resistência à tração mínimo','MPa','NUMERO',false,null,6,250,null,null,null,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_DUREZA','Dureza','HB','NUMERO',true,null,7,null,187,null,250,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_LIMITE_ESCOAMENTO','Limite de escoamento mínimo',null,'TEXTO',false,null,8,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_MATRIZ','FV_ALONGAMENTO','Alongamento mínimo','%','TEXTO',false,null,9,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_C','C','%','NUMERO',true,null,1,null,3.40,null,3.55,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_SI','Si','%','NUMERO',true,null,2,null,2.15,null,2.25,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_MN','Mn','%','NUMERO',true,null,3,null,0.50,null,0.55,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_P','P','%','NUMERO',true,null,4,null,null,null,0.096,null,null,null,null,false,'Requisito crítico.',true),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_S','S','%','NUMERO',true,null,5,null,0.015,null,0.020,null,null,null,null,false,'Requisito crítico.',true),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_MG','Mg','%','TEXTO',false,null,6,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_CR','Cr','%','NUMERO',true,null,7,null,0.30,null,0.35,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_AL','Al','%','TEXTO',false,null,8,null,null,null,null,null,null,null,null,false,'Valor pendente de conferência na ficha original.',false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_CU','Cu','%','NUMERO',true,null,9,null,0.25,null,0.30,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_SN','Sn','%','NUMERO',true,null,10,null,null,null,0.03,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_TI','Ti','%','NUMERO',true,null,11,null,null,null,0.025,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_PB','Pb','%','NUMERO',true,null,12,null,null,null,0.02,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_CEQ','Ceq','%','NUMERO',true,null,13,null,4.13,null,4.30,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_CE_LIQUIDO','CE Líquido','%','NUMERO',true,null,14,null,4.13,null,4.20,null,null,null,null,false,'Requisito crítico.',true),
    ('FUSAO_VAZAMENTO','FV_FORNO','FV_FORNO_MO','Mo','%','TEXTO',false,null,15,null,null,null,null,null,null,null,null,false,'Valor pendente de conferência na ficha original.',false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_C','C','%','NUMERO',true,null,1,null,3.35,null,3.50,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_SI','Si','%','NUMERO',true,null,2,null,2.20,null,2.35,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_MN','Mn','%','NUMERO',true,null,3,null,0.50,null,0.55,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_P','P','%','NUMERO',true,null,4,null,null,null,0.096,null,null,null,null,false,'Requisito crítico.',true),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_S','S','%','NUMERO',true,null,5,null,0.015,null,0.020,null,null,null,null,false,'Requisito crítico.',true),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_MG','Mg','%','TEXTO',false,null,6,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_CR','Cr','%','NUMERO',true,null,7,null,0.30,null,0.35,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_AL','Al','%','TEXTO',false,null,8,null,null,null,null,null,null,null,null,false,'Valor pendente de conferência na ficha original.',false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_CU','Cu','%','NUMERO',true,null,9,null,0.25,null,0.30,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_SN','Sn','%','NUMERO',true,null,10,null,null,null,0.03,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_TI','Ti','%','NUMERO',true,null,11,null,null,null,0.025,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_PB','Pb','%','NUMERO',true,null,12,null,null,null,0.02,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_CEQ','Ceq','%','NUMERO',true,null,13,null,4.05,null,4.30,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_CE_LIQUIDO','CE Líquido','%','NUMERO',true,null,14,null,4.10,null,4.20,null,null,null,null,false,'Requisito crítico.',true),
    ('FUSAO_VAZAMENTO','FV_VAZAMENTO','FV_VAZ_MO','Mo','%','TEXTO',false,null,15,null,null,null,null,null,null,null,null,false,'Valor pendente de conferência na ficha original.',false),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','FV_PRE_INOCULACAO','Pré-inoculação – Panela de transferência','%','NUMERO',true,null,1,null,0.20,null,0.30,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','FV_POS_INOCULACAO','Pós-inoculação – Vazamento','%','NUMERO',true,null,2,null,0.15,null,0.20,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','FV_POS_NOMINAL','Pós-inoculação nominal','kg','NUMERO',true,null,3,null,12.5,null,15.0,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','FV_GRAU_1','Grau 1','kg','NUMERO',true,null,4,12.5,11.8,null,13.1,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','FV_GRAU_2','Grau 2','kg','NUMERO',true,null,5,15.0,14.2,null,15.8,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_INOCULACAO','FV_TIPO_INOCULACAO','Tipo',null,'NUMERO',false,null,6,3,null,null,null,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_NODULARIZACAO','FV_PESO_METAL','Peso Metal','kg','NUMERO',true,null,1,null,1800,null,2200,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_NODULARIZACAO','FV_PESO_LIGA','Peso de liga','kg','TEXTO',false,null,2,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_NODULARIZACAO','FV_PERCENTUAL','Percentual','%','TEXTO',false,null,3,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_NODULARIZACAO','FV_COBERTURA','Cobertura','kg','TEXTO',false,null,4,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_NODULARIZACAO','FV_FADING','Fading','min','TEXTO',false,null,5,null,null,null,null,'Não aplicável',null,null,null,true,null,false),
    ('FUSAO_VAZAMENTO','FV_TEMPERATURAS','FV_TEMP_HOLDING','Forno Holding','°C','NUMERO',true,null,1,null,1520,null,1550,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_TEMPERATURAS','FV_TEMP_TRANSFERENCIA','Liberação Panela de Transferência','°C','NUMERO',true,null,2,null,1440,null,1500,null,null,null,null,false,null,false),
    ('FUSAO_VAZAMENTO','FV_TEMPERATURAS','FV_TEMP_VAZAMENTO','Liberação Panela de Vazamento','°C','NUMERO',true,null,3,null,1370,null,1420,null,null,null,null,false,'Pirômetro de imersão.',true),
    ('FUSAO_VAZAMENTO','FV_TEMPERATURAS','FV_TEMP_LIBERACAO_MOLDE','Liberação de Vazamento dos Moldes','°C','NUMERO',true,null,4,null,1360,null,1440,null,null,null,null,false,'Pirômetro laser.',true),
    ('FUSAO_VAZAMENTO','FV_ANALISE_TERMICA','FV_ANALISE_PENDENTE','Parâmetros de análise térmica',null,'TEXTO',false,null,1,null,null,null,null,null,null,null,null,false,'Valor pendente de conferência na ficha original.',false);

  insert into public.parametros (
    grupo_id, codigo, nome, unidade, tipo_dado, permite_faixa,
    lista_opcoes, obrigatorio, ordem_exibicao, ativo, observacao, critico
  )
  select g.id, s.codigo, s.nome, s.unidade, s.tipo_dado, s.faixa,
    s.opcoes, false, s.ordem, true, s.observacao, s.critico
  from seed_parametros s
  join public.grupos_parametros g
    on g.tipo_ficha=s.tipo and g.codigo=s.grupo
  on conflict (grupo_id, codigo) where codigo is not null
  do update set nome=excluded.nome, unidade=excluded.unidade,
    tipo_dado=excluded.tipo_dado, permite_faixa=excluded.permite_faixa,
    lista_opcoes=excluded.lista_opcoes, ordem_exibicao=excluded.ordem_exibicao,
    observacao=excluded.observacao, critico=excluded.critico, ativo=true;

  update public.parametros
  set configuracao_visual =
    configuracao_visual || '{"intervalo_inicio_fim": true}'::jsonb
  where codigo in (
    'MOLD_141_SOPRO_SP_3_FRENTE',
    'MOLD_142_SOPRO_SP_3_INFERIOR',
    'MOLD_143_SOPRO_SP_5_FRENTE',
    'MOLD_144_SOPRO_SP_5_INFERIOR',
    'MOLD_148_SOPRO_LATERAL'
  );

  insert into public.valores_parametros (
    ficha_tecnica_id, parametro_id, valor_texto, valor_numerico,
    valor_minimo, valor_alvo, valor_maximo, valor_booleano,
    valor_inicial, valor_final, nao_aplicavel, observacao
  )
  select case when s.tipo='MOLDAGEM' then v_ficha_moldagem else v_ficha_fusao end,
    p.id, s.texto, s.valor, s.minimo, s.alvo, s.maximo, s.booleano,
    s.inicial, s.final, s.nao_aplicavel, s.observacao
  from seed_parametros s
  join public.grupos_parametros g
    on g.tipo_ficha=s.tipo and g.codigo=s.grupo
  join public.parametros p on p.grupo_id=g.id and p.codigo=s.codigo
  on conflict (ficha_tecnica_id, parametro_id) do update set
    valor_texto=excluded.valor_texto, valor_numerico=excluded.valor_numerico,
    valor_minimo=excluded.valor_minimo, valor_alvo=excluded.valor_alvo,
    valor_maximo=excluded.valor_maximo, valor_booleano=excluded.valor_booleano,
    valor_inicial=excluded.valor_inicial, valor_final=excluded.valor_final,
    nao_aplicavel=excluded.nao_aplicavel, observacao=excluded.observacao;

  insert into public.historico_fichas (
    ficha_tecnica_id, numero_revisao, data_revisao, descricao
  ) values
    (v_ficha_moldagem,22,'2026-06-19','Revisão atual importada; histórico anterior pendente de conferência.'),
    (v_ficha_fusao,54,'2026-05-13','Alterado tempo de vazamento e pós-inoculação. Outras alterações pendentes de conferência na ficha original.'),
    (v_ficha_fusao,55,'2026-06-19','Alterado CE Líquido. Campo de observações alterado.'),
    (v_ficha_fusao,56,'2026-07-10','Alterados Ceq e CE Líquido; faixas do forno e vazamento; Holding, panela de transferência e vazamento.')
  on conflict (ficha_tecnica_id, numero_revisao) do update set
    data_revisao=excluded.data_revisao, descricao=excluded.descricao;

end;
$$;

create or replace function public.salvar_rascunho_ficha_tecnica_v2(
  p_produto_id bigint,
  p_tipo text,
  p_ficha_id bigint default null,
  p_motivo_revisao text default null,
  p_data_emissao date default null,
  p_valores jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_ficha_id bigint;
begin
  v_ficha_id := public.salvar_rascunho_ficha_tecnica(
    p_produto_id,
    p_tipo,
    p_ficha_id,
    p_motivo_revisao,
    p_data_emissao,
    p_valores
  );

  update public.valores_parametros valor
  set valor_inicial = recebido.valor_inicial,
      valor_final = recebido.valor_final,
      nao_aplicavel = coalesce(recebido.nao_aplicavel, false)
  from jsonb_to_recordset(coalesce(p_valores, '[]'::jsonb))
    as recebido(
      parametro_id bigint,
      valor_inicial numeric,
      valor_final numeric,
      nao_aplicavel boolean
    )
  where valor.ficha_tecnica_id = v_ficha_id
    and valor.parametro_id = recebido.parametro_id;

  return v_ficha_id;
end;
$$;

revoke all on function public.salvar_rascunho_ficha_tecnica_v2(
  bigint, text, bigint, text, date, jsonb
) from public;
grant execute on function public.salvar_rascunho_ficha_tecnica_v2(
  bigint, text, bigint, text, date, jsonb
) to authenticated;

notify pgrst, 'reload schema';

commit;
