begin;

create table if not exists public.composicoes_producao (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.composicoes_producao_itens (
  composicao_id bigint not null references public.composicoes_producao(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  percentual numeric(7,4) not null check (percentual > 0 and percentual <= 100),
  primary key (composicao_id, produto_id)
);

alter table public.registros_producao_moldes
  add column if not exists composicao_producao_id bigint references public.composicoes_producao(id),
  add column if not exists grupo_producao text;

create index if not exists registros_producao_grupo_idx
  on public.registros_producao_moldes(grupo_producao)
  where grupo_producao is not null;

insert into public.composicoes_producao(codigo,nome)
values ('MS0018/19','Produção conjunta MS0018 / MS0019')
on conflict(codigo) do update set nome=excluded.nome,ativo=true;

insert into public.composicoes_producao_itens(composicao_id,produto_id,percentual)
select composicao.id,produto.id,50
from public.composicoes_producao composicao
join public.produtos produto on upper(trim(produto.codigo)) in ('MS0018','MS0019')
where composicao.codigo='MS0018/19'
on conflict(composicao_id,produto_id) do update set percentual=excluded.percentual;

do $$
begin
  if (select count(*) from public.composicoes_producao_itens item
      join public.composicoes_producao composicao on composicao.id=item.composicao_id
      where composicao.codigo='MS0018/19') <> 2 then
    raise exception 'MS0018 e MS0019 precisam existir separadamente antes da composição.';
  end if;
end $$;

alter table public.composicoes_producao enable row level security;
alter table public.composicoes_producao_itens enable row level security;
create policy composicoes_producao_select on public.composicoes_producao
for select to authenticated using (public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
create policy composicoes_producao_itens_select on public.composicoes_producao_itens
for select to authenticated using (public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
grant select on public.composicoes_producao,public.composicoes_producao_itens to authenticated;

commit;
