begin;

-- ==========================================================================
-- Histórico de alterações da carga — pedido explícito: deixar o operador da
-- Ponte (e quem mais estiver olhando) ciente de quando o supervisor inclui,
-- altera planejado/real ou exclui um material, sem misturar com o quadro de
-- recados (que é conversa livre, não log automático). Guarda o texto já
-- pronto (igual mensagens) — o nome do autor entra via join na leitura.
-- ==========================================================================
create table public.corridas_fusao_alteracoes (
  id bigint generated by default as identity primary key,
  corrida_id bigint not null references public.corridas_fusao(id) on delete cascade,
  autor_id uuid references public.usuarios(id),
  descricao text not null,
  criado_em timestamptz not null default now()
);
create index corridas_fusao_alteracoes_corrida_idx on public.corridas_fusao_alteracoes(corrida_id, criado_em);
alter table public.corridas_fusao_alteracoes enable row level security;
create policy corridas_fusao_alteracoes_select on public.corridas_fusao_alteracoes for select to authenticated using (auth.uid() is not null);
grant select on public.corridas_fusao_alteracoes to authenticated;
grant usage,select on sequence public.corridas_fusao_alteracoes_id_seq to authenticated;

create or replace function public.adicionar_item_carga_fusao(
  p_corrida_id bigint, p_material_id bigint, p_quantidade_planejada_kg numeric, p_estado_fisico text default null
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_corrida record;
  v_material record;
  v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  select * into v_corrida from public.corridas_fusao where id = p_corrida_id;
  if not found then raise exception 'Corrida não encontrada.'; end if;
  if v_corrida.status <> 'ABERTA' then raise exception 'Só é possível incluir material numa corrida aberta.'; end if;
  if coalesce(p_quantidade_planejada_kg, -1) < 0 then raise exception 'Informe a quantidade planejada.'; end if;

  select * into v_material from public.materiais_fusao where id = p_material_id;
  if not found then raise exception 'Material inválido.'; end if;
  if v_material.tipo = 'GUSA' and p_estado_fisico is null then
    raise exception 'Informe se o gusa está sólido ou líquido.';
  end if;

  insert into public.corridas_fusao_carga_itens(corrida_id, material_id, quantidade_planejada_kg, estado_fisico, criado_por)
  values (p_corrida_id, p_material_id, p_quantidade_planejada_kg, case when v_material.tipo = 'GUSA' then p_estado_fisico else null end, auth.uid())
  returning id into v_id;

  insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
  values (p_corrida_id, auth.uid(), format('incluiu %s (%s kg planejado)', v_material.nome, p_quantidade_planejada_kg));

  return v_id;
end;
$$;

create or replace function public.atualizar_planejado_carga_fusao(p_corrida_id bigint, p_item_id bigint, p_quantidade_planejada_kg numeric)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_corrida record;
  v_planejado_antigo numeric;
  v_nome text;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  select * into v_corrida from public.corridas_fusao where id = p_corrida_id;
  if not found then raise exception 'Corrida não encontrada.'; end if;
  if v_corrida.status <> 'ABERTA' then raise exception 'Só é possível editar o planejado de uma corrida aberta.'; end if;
  if coalesce(p_quantidade_planejada_kg, -1) < 0 then raise exception 'Quantidade planejada inválida.'; end if;

  select item.quantidade_planejada_kg, material.nome into v_planejado_antigo, v_nome
    from public.corridas_fusao_carga_itens item
    join public.materiais_fusao material on material.id = item.material_id
    where item.corrida_id = p_corrida_id and item.id = p_item_id;
  if not found then raise exception 'Item de carga não encontrado nesta corrida.'; end if;

  update public.corridas_fusao_carga_itens
  set quantidade_planejada_kg = p_quantidade_planejada_kg
  where corrida_id = p_corrida_id and id = p_item_id;

  insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
  values (p_corrida_id, auth.uid(), format('alterou planejado de %s de %s kg para %s kg', v_nome, v_planejado_antigo, p_quantidade_planejada_kg));
end;
$$;

create or replace function public.atualizar_pesagem_carga_fusao(p_corrida_id bigint, p_material_id bigint, p_quantidade_realizada_kg numeric)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_realizado_antigo numeric;
  v_nome text;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if p_quantidade_realizada_kg is not null and p_quantidade_realizada_kg < 0 then
    raise exception 'Quantidade realizada não pode ser negativa.';
  end if;

  select item.quantidade_realizada_kg, material.nome into v_realizado_antigo, v_nome
    from public.corridas_fusao_carga_itens item
    join public.materiais_fusao material on material.id = item.material_id
    where item.corrida_id = p_corrida_id and item.id = p_material_id;
  if not found then raise exception 'Item de carga não encontrado nesta corrida.'; end if;

  update public.corridas_fusao_carga_itens
  set quantidade_realizada_kg = p_quantidade_realizada_kg, atualizado_por = auth.uid(), atualizado_em = now()
  where corrida_id = p_corrida_id and id = p_material_id;

  insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
  values (p_corrida_id, auth.uid(), format('alterou real de %s de %s kg para %s kg', v_nome,
    coalesce(v_realizado_antigo::text, '—'), coalesce(p_quantidade_realizada_kg::text, '—')));
end;
$$;

create or replace function public.remover_item_carga_fusao(p_corrida_id bigint, p_item_id bigint)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_corrida record;
  v_planejado numeric;
  v_realizado numeric;
  v_nome text;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  select * into v_corrida from public.corridas_fusao where id = p_corrida_id;
  if not found then raise exception 'Corrida não encontrada.'; end if;
  if v_corrida.status <> 'ABERTA' then raise exception 'Só é possível remover material de uma corrida aberta.'; end if;

  select item.quantidade_planejada_kg, item.quantidade_realizada_kg, material.nome into v_planejado, v_realizado, v_nome
    from public.corridas_fusao_carga_itens item
    join public.materiais_fusao material on material.id = item.material_id
    where item.id = p_item_id and item.corrida_id = p_corrida_id;
  if not found then raise exception 'Item não encontrado nesta corrida.'; end if;
  if coalesce(v_realizado, 0) > 0 then
    raise exception 'Só é possível remover material que ainda não foi pesado.';
  end if;

  delete from public.corridas_fusao_carga_itens where id = p_item_id;

  insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
  values (p_corrida_id, auth.uid(), format('excluiu %s (%s kg planejado)', v_nome, v_planejado));
end;
$$;

do $$ begin
  if not exists(select 1 from pg_catalog.pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='corridas_fusao_alteracoes') then
    alter publication supabase_realtime add table public.corridas_fusao_alteracoes;
  end if;
end $$;

notify pgrst, 'reload schema';

commit;
