begin;

alter table public.fichas_tecnicas
  add column if not exists revisao_origem_id bigint
    references public.fichas_tecnicas(id),
  add column if not exists etapa_aprovacao text;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.fichas_tecnicas'::regclass
      and conname = 'fichas_tecnicas_etapa_aprovacao_check'
  ) then
    alter table public.fichas_tecnicas
      add constraint fichas_tecnicas_etapa_aprovacao_check
      check (
        etapa_aprovacao is null
        or etapa_aprovacao in ('ENGENHARIA', 'PRODUCAO')
      );
  end if;
end;
$$;

create table if not exists public.templates_importacao_ficha (
  codigo text primary key,
  tipo_ficha text not null,
  versao text not null,
  nome text not null,
  configuracao jsonb not null default '{}'::jsonb,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (tipo_ficha, versao)
);

create table if not exists public.importacoes_ficha (
  id bigint generated by default as identity primary key,
  ficha_tecnica_id bigint not null unique
    references public.fichas_tecnicas(id),
  estado text not null default 'IMPORTACAO_RASCUNHO'
    check (
      estado in (
        'IMPORTACAO_RASCUNHO',
        'IMPORTACAO_PENDENTE_VALIDACAO',
        'IMPORTADA',
        'REJEITADA'
      )
    ),
  template_codigo text
    references public.templates_importacao_ficha(codigo),
  versao_extrator text not null,
  resultado_extracao jsonb not null default '{}'::jsonb,
  campos_alterados jsonb not null default '[]'::jsonb,
  avisos jsonb not null default '[]'::jsonb,
  campos_nao_reconhecidos jsonb not null default '[]'::jsonb,
  pdf_storage_path text,
  pdf_nome_original text,
  pdf_mime_type text,
  pdf_tamanho_bytes bigint,
  pdf_hash_sha256 text,
  enviado_por uuid references public.usuarios(id),
  enviado_em timestamptz,
  criado_por uuid not null references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  validado_em timestamptz
);

create table if not exists public.validacoes_importacao_ficha (
  id bigint generated by default as identity primary key,
  importacao_id bigint not null
    references public.importacoes_ficha(id),
  ficha_tecnica_id bigint not null
    references public.fichas_tecnicas(id),
  administrador_id uuid not null references public.usuarios(id),
  administrador_nome text not null,
  resultado text not null
    check (resultado in ('VALIDADA', 'REJEITADA')),
  observacao text,
  declaracao text not null default
    'Os dados cadastrados correspondem ao documento original.',
  pdf_nome_original text,
  pdf_hash_sha256 text,
  versao_extrator text,
  campos_alterados jsonb not null default '[]'::jsonb,
  criado_em timestamptz not null default now()
);

alter table public.validacoes_importacao_ficha
  add column if not exists administrador_nome text;

create table if not exists public.auditoria_importacao_ficha (
  id bigint generated by default as identity primary key,
  importacao_id bigint references public.importacoes_ficha(id),
  ficha_tecnica_id bigint references public.fichas_tecnicas(id),
  usuario_id uuid not null references public.usuarios(id),
  evento text not null
    check (
      evento in (
        'PDF_ENVIADO',
        'EXTRACAO_INICIADA',
        'EXTRACAO_CONCLUIDA',
        'CAMPO_CORRIGIDO',
        'IMPORTACAO_SALVA',
        'ENVIADA_VALIDACAO',
        'IMPORTACAO_VALIDADA',
        'IMPORTACAO_REJEITADA',
        'NOVA_REVISAO_CRIADA'
      )
    ),
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists importacoes_ficha_estado_idx
  on public.importacoes_ficha(estado, atualizado_em desc);
create index if not exists validacoes_importacao_ficha_ficha_idx
  on public.validacoes_importacao_ficha(ficha_tecnica_id, criado_em desc);
create index if not exists auditoria_importacao_ficha_ficha_idx
  on public.auditoria_importacao_ficha(ficha_tecnica_id, criado_em desc);

alter table public.templates_importacao_ficha enable row level security;
alter table public.importacoes_ficha enable row level security;
alter table public.validacoes_importacao_ficha enable row level security;
alter table public.auditoria_importacao_ficha enable row level security;

grant select on public.templates_importacao_ficha to authenticated;
grant select on public.importacoes_ficha to authenticated;
grant select on public.validacoes_importacao_ficha to authenticated;
grant select on public.auditoria_importacao_ficha to authenticated;

insert into public.permissoes (
  codigo, nome, descricao, modulo, ativo
)
select dados.codigo, dados.nome, dados.descricao, 'FICHAS_TECNICAS', true
from (
  values
    (
      'ficha.importar',
      'Importar ficha técnica',
      'Envia PDF e inicia uma importação histórica.'
    ),
    (
      'ficha.conferir_importacao',
      'Conferir importação de ficha',
      'Corrige os dados extraídos e envia para validação.'
    ),
    (
      'ficha.validar_importacao',
      'Validar importação de ficha',
      'Confirma administrativamente a fidelidade ao PDF original.'
    ),
    (
      'ficha.aprovar_engenharia',
      'Aprovar ficha pela Engenharia',
      'Executa a aprovação técnica da etapa de Engenharia.'
    ),
    (
      'ficha.aprovar_producao',
      'Aprovar ficha pela Produção',
      'Executa a aprovação técnica da etapa de Produção.'
    )
) as dados(codigo, nome, descricao)
where not exists (
  select 1
  from public.permissoes permissao
  where permissao.codigo = dados.codigo
);

insert into public.perfil_permissoes (perfil_id, permissao_id)
select perfil.id, permissao.id
from public.perfis perfil
cross join public.permissoes permissao
where (
    upper(perfil.codigo) in ('ADMIN', 'ADMINISTRADOR')
    or upper(perfil.nome) = 'ADMINISTRADOR'
  )
  and permissao.codigo in (
    'ficha.importar',
    'ficha.conferir_importacao',
    'ficha.validar_importacao'
  )
  and not exists (
    select 1
    from public.perfil_permissoes perfil_permissao
    where perfil_permissao.perfil_id = perfil.id
      and perfil_permissao.permissao_id = permissao.id
  );

create or replace function public.usuario_tem_permissao_ficha(
  p_codigo text
)
returns boolean
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_permitido_individual boolean;
begin
  if v_usuario_id is null then
    return false;
  end if;

  select usuario_permissao.permitido
    into v_permitido_individual
  from public.usuario_permissoes usuario_permissao
  join public.permissoes permissao
    on permissao.id = usuario_permissao.permissao_id
  where usuario_permissao.usuario_id = v_usuario_id
    and permissao.codigo = p_codigo
  limit 1;

  if found then
    return coalesce(v_permitido_individual, false);
  end if;

  return exists (
    select 1
    from public.usuario_perfis usuario_perfil
    join public.perfil_permissoes perfil_permissao
      on perfil_permissao.perfil_id = usuario_perfil.perfil_id
    join public.permissoes permissao
      on permissao.id = perfil_permissao.permissao_id
    where usuario_perfil.usuario_id = v_usuario_id
      and permissao.codigo = p_codigo
  );
end;
$$;

revoke all on function public.usuario_tem_permissao_ficha(text)
  from public;
grant execute on function public.usuario_tem_permissao_ficha(text)
  to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'templates_importacao_ficha'
      and policyname = 'templates_importacao_select'
  ) then
    create policy templates_importacao_select
      on public.templates_importacao_ficha for select
      to authenticated
      using (
        auth.uid() is not null
        and public.usuario_tem_permissao_ficha('ficha.visualizar')
      );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'importacoes_ficha'
      and policyname = 'importacoes_ficha_select'
  ) then
    create policy importacoes_ficha_select
      on public.importacoes_ficha for select
      to authenticated
      using (
        auth.uid() is not null
        and (
          public.usuario_tem_permissao_ficha('ficha.visualizar')
          or public.usuario_tem_permissao_ficha('ficha.importar')
          or public.usuario_tem_permissao_ficha(
            'ficha.conferir_importacao'
          )
          or public.usuario_tem_permissao_ficha(
            'ficha.validar_importacao'
          )
        )
      );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'validacoes_importacao_ficha'
      and policyname = 'validacoes_importacao_select'
  ) then
    create policy validacoes_importacao_select
      on public.validacoes_importacao_ficha for select
      to authenticated
      using (
        auth.uid() is not null
        and public.usuario_tem_permissao_ficha('ficha.visualizar')
      );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'auditoria_importacao_ficha'
      and policyname = 'auditoria_importacao_select'
  ) then
    create policy auditoria_importacao_select
      on public.auditoria_importacao_ficha for select
      to authenticated
      using (
        auth.uid() is not null
        and (
          public.usuario_tem_permissao_ficha(
            'ficha.conferir_importacao'
          )
          or public.usuario_tem_permissao_ficha(
            'ficha.validar_importacao'
          )
        )
      );
  end if;
end;
$$;

insert into public.templates_importacao_ficha (
  codigo, tipo_ficha, versao, nome, configuracao
) values
  (
    'moldagem_v1',
    'MOLDAGEM',
    '1',
    'Ficha de Moldagem v1',
    '{"aliases":["MOLDAGEM","FICHA TÉCNICA DE PROCESSO"],"grupos":[]}'::jsonb
  ),
  (
    'fusao_vazamento_v1',
    'FUSAO_VAZAMENTO',
    '1',
    'Ficha de Fusão/Vazamento v1',
    '{"aliases":["FUSÃO / VAZAMENTO","FICHA TÉCNICA DE PROCESSO"],"grupos":[]}'::jsonb
  ),
  (
    'macharia_v1',
    'MACHARIA',
    '1',
    'Ficha de Macharia v1',
    '{"aliases":["MACHARIA"],"grupos":[]}'::jsonb
  ),
  (
    'acabamento_v1',
    'ACABAMENTO',
    '1',
    'Ficha de Acabamento v1',
    '{"aliases":["ACABAMENTO"],"grupos":[]}'::jsonb
  ),
  (
    'laboratorio_v1',
    'LABORATORIO',
    '1',
    'Ficha de Laboratório v1',
    '{"aliases":["LABORATÓRIO"],"grupos":[]}'::jsonb
  )
on conflict (codigo) do update set
  tipo_ficha = excluded.tipo_ficha,
  versao = excluded.versao,
  nome = excluded.nome,
  configuracao = excluded.configuracao,
  ativo = true,
  atualizado_em = now();

insert into storage.buckets (id, name, public)
values ('fichas-tecnicas-pdf', 'fichas-tecnicas-pdf', false)
on conflict (id) do update set public = false;

do $$
begin
  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'fichas_pdf_select'
  ) then
    create policy fichas_pdf_select
      on storage.objects for select
      to authenticated
      using (
        bucket_id = 'fichas-tecnicas-pdf'
        and auth.uid() is not null
        and public.usuario_tem_permissao_ficha('ficha.visualizar')
      );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'fichas_pdf_insert'
  ) then
    create policy fichas_pdf_insert
      on storage.objects for insert
      to authenticated
      with check (
        bucket_id = 'fichas-tecnicas-pdf'
        and auth.uid() is not null
        and public.usuario_tem_permissao_ficha('ficha.importar')
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'fichas_pdf_update'
  ) then
    create policy fichas_pdf_update
      on storage.objects for update
      to authenticated
      using (
        bucket_id = 'fichas-tecnicas-pdf'
        and owner_id = auth.uid()::text
        and public.usuario_tem_permissao_ficha(
          'ficha.conferir_importacao'
        )
      )
      with check (
        bucket_id = 'fichas-tecnicas-pdf'
        and owner_id = auth.uid()::text
        and public.usuario_tem_permissao_ficha(
          'ficha.conferir_importacao'
        )
      );
  end if;
end;
$$;

create or replace function public.registrar_evento_importacao(
  p_importacao_id bigint,
  p_evento text,
  p_detalhes jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_evento_id bigint;
  v_ficha_id bigint;
begin
  if v_usuario_id is null then
    raise exception 'Usuário não autenticado.' using errcode = '42501';
  end if;

  if not (
    public.usuario_tem_permissao_ficha('ficha.importar')
    or public.usuario_tem_permissao_ficha(
      'ficha.conferir_importacao'
    )
    or public.usuario_tem_permissao_ficha(
      'ficha.validar_importacao'
    )
  ) then
    raise exception 'Usuário sem permissão para auditar importações.'
      using errcode = '42501';
  end if;

  select ficha_tecnica_id into v_ficha_id
  from public.importacoes_ficha
  where id = p_importacao_id;

  if not found then
    raise exception 'Importação não encontrada.' using errcode = 'P0002';
  end if;

  insert into public.auditoria_importacao_ficha (
    importacao_id, ficha_tecnica_id, usuario_id, evento, detalhes
  ) values (
    p_importacao_id,
    v_ficha_id,
    v_usuario_id,
    p_evento,
    coalesce(p_detalhes, '{}'::jsonb)
  )
  returning id into v_evento_id;

  return v_evento_id;
end;
$$;

create or replace function public.salvar_importacao_ficha(
  p_produto_id bigint,
  p_tipo text,
  p_codigo_documento text,
  p_numero_revisao integer,
  p_data_emissao date,
  p_template_codigo text,
  p_versao_extrator text,
  p_valores jsonb,
  p_resultado_extracao jsonb default '{}'::jsonb,
  p_campos_alterados jsonb default '[]'::jsonb,
  p_avisos jsonb default '[]'::jsonb,
  p_campos_nao_reconhecidos jsonb default '[]'::jsonb,
  p_pdf_storage_path text default null,
  p_pdf_nome_original text default null,
  p_pdf_mime_type text default null,
  p_pdf_tamanho_bytes bigint default null,
  p_pdf_hash_sha256 text default null,
  p_ficha_id bigint default null
)
returns table(ficha_id bigint, importacao_id bigint)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_ficha_id bigint;
  v_importacao_id bigint;
  v_estado text;
begin
  if v_usuario_id is null then
    raise exception 'Usuário não autenticado.' using errcode = '42501';
  end if;

  if not (
    public.usuario_tem_permissao_ficha('ficha.importar')
    or public.usuario_tem_permissao_ficha(
      'ficha.conferir_importacao'
    )
  ) then
    raise exception 'Usuário sem permissão para salvar importações.'
      using errcode = '42501';
  end if;

  if p_produto_id is null
    or nullif(trim(p_tipo), '') is null
    or nullif(trim(p_codigo_documento), '') is null
    or p_numero_revisao is null
    or p_numero_revisao < 0
    or p_data_emissao is null
    or nullif(trim(p_template_codigo), '') is null
    or nullif(trim(p_versao_extrator), '') is null
  then
    raise exception 'Cabeçalho obrigatório da importação incompleto.'
      using errcode = '22023';
  end if;

  if p_pdf_mime_type is not null
    and p_pdf_mime_type <> 'application/pdf'
  then
    raise exception 'O anexo original deve ser um PDF.'
      using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_valores, '[]'::jsonb)) <> 'array' then
    raise exception 'Os valores devem ser um array JSON.'
      using errcode = '22023';
  end if;

  if (
    select count(*)
    from jsonb_to_recordset(coalesce(p_valores, '[]'::jsonb))
      as valor(parametro_id bigint)
  ) <> (
    select count(distinct valor.parametro_id)
    from jsonb_to_recordset(coalesce(p_valores, '[]'::jsonb))
      as valor(parametro_id bigint)
  ) then
    raise exception 'A lista contém parâmetros ausentes ou duplicados.'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(coalesce(p_valores, '[]'::jsonb))
      as valor(parametro_id bigint)
    where not exists (
      select 1
      from public.parametros parametro
      join public.grupos_parametros grupo
        on grupo.id = parametro.grupo_id
      where parametro.id = valor.parametro_id
        and grupo.tipo_ficha = p_tipo
    )
  ) then
    raise exception 'A lista contém parâmetro incompatível com a ficha.'
      using errcode = '22023';
  end if;

  if p_ficha_id is null
    and p_pdf_storage_path is not null
    and split_part(p_pdf_storage_path, '/', 1) <> v_usuario_id::text
  then
    raise exception 'Caminho do PDF incompatível com o usuário.'
      using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_produto_id::text || ':' || p_tipo || ':' ||
      p_numero_revisao::text,
      0
    )
  );

  if p_ficha_id is null then
    insert into public.fichas_tecnicas (
      produto_id,
      tipo,
      codigo_documento,
      numero_revisao,
      status,
      vigente,
      elaborado_por,
      motivo_revisao,
      data_emissao
    ) values (
      p_produto_id,
      p_tipo,
      p_codigo_documento,
      p_numero_revisao,
      'IMPORTADA',
      false,
      v_usuario_id,
      'Importação histórica em conferência.',
      p_data_emissao
    )
    returning id into v_ficha_id;
  else
    select importacao.estado into v_estado
    from public.importacoes_ficha importacao
    where importacao.ficha_tecnica_id = p_ficha_id
    for update;

    if not found or v_estado not in (
      'IMPORTACAO_RASCUNHO',
      'REJEITADA'
    ) then
      raise exception 'A importação não pode mais ser alterada.'
        using errcode = '42501';
    end if;

    update public.fichas_tecnicas ficha
    set codigo_documento = p_codigo_documento,
        numero_revisao = p_numero_revisao,
        data_emissao = p_data_emissao,
        vigente = false
    where ficha.id = p_ficha_id
      and ficha.produto_id = p_produto_id
      and ficha.tipo = p_tipo
    returning ficha.id into v_ficha_id;

    if v_ficha_id is null then
      raise exception 'Ficha de importação incompatível.'
        using errcode = '22023';
    end if;
  end if;

  insert into public.importacoes_ficha (
    ficha_tecnica_id,
    estado,
    template_codigo,
    versao_extrator,
    resultado_extracao,
    campos_alterados,
    avisos,
    campos_nao_reconhecidos,
    pdf_storage_path,
    pdf_nome_original,
    pdf_mime_type,
    pdf_tamanho_bytes,
    pdf_hash_sha256,
    enviado_por,
    enviado_em,
    criado_por,
    atualizado_por
  ) values (
    v_ficha_id,
    'IMPORTACAO_RASCUNHO',
    p_template_codigo,
    p_versao_extrator,
    coalesce(p_resultado_extracao, '{}'::jsonb),
    coalesce(p_campos_alterados, '[]'::jsonb),
    coalesce(p_avisos, '[]'::jsonb),
    coalesce(p_campos_nao_reconhecidos, '[]'::jsonb),
    p_pdf_storage_path,
    p_pdf_nome_original,
    p_pdf_mime_type,
    p_pdf_tamanho_bytes,
    p_pdf_hash_sha256,
    case when p_pdf_storage_path is not null then v_usuario_id end,
    case when p_pdf_storage_path is not null then now() end,
    v_usuario_id,
    v_usuario_id
  )
  on conflict (ficha_tecnica_id) do update set
    template_codigo = excluded.template_codigo,
    versao_extrator = excluded.versao_extrator,
    resultado_extracao = excluded.resultado_extracao,
    campos_alterados = excluded.campos_alterados,
    avisos = excluded.avisos,
    campos_nao_reconhecidos = excluded.campos_nao_reconhecidos,
    pdf_storage_path = coalesce(
      excluded.pdf_storage_path,
      public.importacoes_ficha.pdf_storage_path
    ),
    pdf_nome_original = coalesce(
      excluded.pdf_nome_original,
      public.importacoes_ficha.pdf_nome_original
    ),
    pdf_mime_type = coalesce(
      excluded.pdf_mime_type,
      public.importacoes_ficha.pdf_mime_type
    ),
    pdf_tamanho_bytes = coalesce(
      excluded.pdf_tamanho_bytes,
      public.importacoes_ficha.pdf_tamanho_bytes
    ),
    pdf_hash_sha256 = coalesce(
      excluded.pdf_hash_sha256,
      public.importacoes_ficha.pdf_hash_sha256
    ),
    enviado_por = coalesce(
      excluded.enviado_por,
      public.importacoes_ficha.enviado_por
    ),
    enviado_em = coalesce(
      excluded.enviado_em,
      public.importacoes_ficha.enviado_em
    ),
    atualizado_por = v_usuario_id,
    atualizado_em = now()
  returning id into v_importacao_id;

  insert into public.valores_parametros (
    ficha_tecnica_id,
    parametro_id,
    valor_texto,
    valor_numerico,
    valor_minimo,
    valor_alvo,
    valor_maximo,
    valor_booleano,
    valor_data,
    valor_inicial,
    valor_final,
    nao_aplicavel,
    observacao
  )
  select
    v_ficha_id,
    valor.parametro_id,
    valor.valor_texto,
    valor.valor_numerico,
    valor.valor_minimo,
    valor.valor_alvo,
    valor.valor_maximo,
    valor.valor_booleano,
    valor.valor_data,
    valor.valor_inicial,
    valor.valor_final,
    coalesce(valor.nao_aplicavel, false),
    valor.observacao
  from jsonb_to_recordset(coalesce(p_valores, '[]'::jsonb))
    as valor(
      parametro_id bigint,
      valor_texto text,
      valor_numerico numeric,
      valor_minimo numeric,
      valor_alvo numeric,
      valor_maximo numeric,
      valor_booleano boolean,
      valor_data date,
      valor_inicial numeric,
      valor_final numeric,
      nao_aplicavel boolean,
      observacao text
    )
  on conflict (ficha_tecnica_id, parametro_id) do update set
    valor_texto = excluded.valor_texto,
    valor_numerico = excluded.valor_numerico,
    valor_minimo = excluded.valor_minimo,
    valor_alvo = excluded.valor_alvo,
    valor_maximo = excluded.valor_maximo,
    valor_booleano = excluded.valor_booleano,
    valor_data = excluded.valor_data,
    valor_inicial = excluded.valor_inicial,
    valor_final = excluded.valor_final,
    nao_aplicavel = excluded.nao_aplicavel,
    observacao = excluded.observacao;

  insert into public.auditoria_importacao_ficha (
    importacao_id,
    ficha_tecnica_id,
    usuario_id,
    evento,
    detalhes
  ) values (
    v_importacao_id,
    v_ficha_id,
    v_usuario_id,
    'IMPORTACAO_SALVA',
    jsonb_build_object('estado', 'IMPORTACAO_RASCUNHO')
  );

  return query select v_ficha_id, v_importacao_id;
end;
$$;

create or replace function public.enviar_importacao_validacao(
  p_importacao_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_ficha_id bigint;
begin
  if not public.usuario_tem_permissao_ficha(
    'ficha.conferir_importacao'
  ) then
    raise exception 'Usuário sem permissão para conferir importações.'
      using errcode = '42501';
  end if;

  update public.importacoes_ficha importacao
  set estado = 'IMPORTACAO_PENDENTE_VALIDACAO',
      atualizado_por = v_usuario_id,
      atualizado_em = now()
  where importacao.id = p_importacao_id
    and importacao.estado in ('IMPORTACAO_RASCUNHO', 'REJEITADA')
    and importacao.pdf_storage_path is not null
  returning ficha_tecnica_id into v_ficha_id;

  if not found then
    raise exception 'Importação sem PDF ou em estado incompatível.'
      using errcode = '22023';
  end if;

  insert into public.auditoria_importacao_ficha (
    importacao_id, ficha_tecnica_id, usuario_id, evento
  ) values (
    p_importacao_id,
    v_ficha_id,
    v_usuario_id,
    'ENVIADA_VALIDACAO'
  );

  return v_ficha_id;
end;
$$;

create or replace function public.validar_importacao_ficha(
  p_importacao_id bigint,
  p_resultado text,
  p_observacao text default null,
  p_tornar_vigente boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_importacao public.importacoes_ficha%rowtype;
  v_resultado text := coalesce(upper(trim(p_resultado)), '');
  v_administrador_nome text;
begin
  if not public.usuario_tem_permissao_ficha(
    'ficha.validar_importacao'
  ) then
    raise exception 'Usuário sem permissão para validar importações.'
      using errcode = '42501';
  end if;

  if v_resultado not in ('VALIDADA', 'REJEITADA') then
    raise exception 'Resultado de validação inválido.'
      using errcode = '22023';
  end if;

  select * into v_importacao
  from public.importacoes_ficha
  where id = p_importacao_id
  for update;

  if not found
    or v_importacao.estado <> 'IMPORTACAO_PENDENTE_VALIDACAO'
    or v_importacao.pdf_storage_path is null
  then
    raise exception 'Importação não está pronta para validação.'
      using errcode = '22023';
  end if;

  select usuario.nome into v_administrador_nome
  from public.usuarios usuario
  where usuario.id = v_usuario_id
    and usuario.status = 'ATIVO';

  if v_administrador_nome is null then
    raise exception 'Administrador não encontrado ou inativo.'
      using errcode = '42501';
  end if;

  insert into public.validacoes_importacao_ficha (
    importacao_id,
    ficha_tecnica_id,
    administrador_id,
    administrador_nome,
    resultado,
    observacao,
    pdf_nome_original,
    pdf_hash_sha256,
    versao_extrator,
    campos_alterados
  ) values (
    v_importacao.id,
    v_importacao.ficha_tecnica_id,
    v_usuario_id,
    v_administrador_nome,
    v_resultado,
    p_observacao,
    v_importacao.pdf_nome_original,
    v_importacao.pdf_hash_sha256,
    v_importacao.versao_extrator,
    v_importacao.campos_alterados
  );

  update public.importacoes_ficha
  set estado = case
        when v_resultado = 'VALIDADA' then 'IMPORTADA'
        else 'REJEITADA'
      end,
      validado_em = case
        when v_resultado = 'VALIDADA' then now()
        else null
      end,
      atualizado_por = v_usuario_id,
      atualizado_em = now()
  where id = v_importacao.id;

  update public.fichas_tecnicas
  set status = 'IMPORTADA',
      vigente = case
        when v_resultado = 'VALIDADA' then p_tornar_vigente
        else false
      end
  where id = v_importacao.ficha_tecnica_id;

  insert into public.auditoria_importacao_ficha (
    importacao_id,
    ficha_tecnica_id,
    usuario_id,
    evento,
    detalhes
  ) values (
    v_importacao.id,
    v_importacao.ficha_tecnica_id,
    v_usuario_id,
    case
      when v_resultado = 'VALIDADA'
        then 'IMPORTACAO_VALIDADA'
      else 'IMPORTACAO_REJEITADA'
    end,
    jsonb_build_object(
      'resultado',
      v_resultado,
      'observacao',
      p_observacao
    )
  );

  return v_importacao.ficha_tecnica_id;
end;
$$;

create or replace function public.criar_nova_revisao_ficha(
  p_ficha_origem_id bigint,
  p_numero_revisao integer,
  p_motivo_revisao text,
  p_data_emissao date default current_date
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_origem public.fichas_tecnicas%rowtype;
  v_nova_ficha_id bigint;
begin
  if not public.usuario_tem_permissao_ficha('ficha.criar') then
    raise exception 'Usuário sem permissão para criar revisão.'
      using errcode = '42501';
  end if;

  select * into v_origem
  from public.fichas_tecnicas
  where id = p_ficha_origem_id
  for share;

  if not found then
    raise exception 'Ficha de origem não encontrada.'
      using errcode = 'P0002';
  end if;

  if v_origem.status = 'IMPORTADA' and exists (
    select 1
    from public.importacoes_ficha importacao
    where importacao.ficha_tecnica_id = v_origem.id
      and importacao.estado <> 'IMPORTADA'
  ) then
    raise exception 'A importação ainda não foi validada.'
      using errcode = '42501';
  end if;

  if p_numero_revisao <= v_origem.numero_revisao then
    raise exception 'A nova revisão deve superar a revisão de origem.'
      using errcode = '22023';
  end if;

  insert into public.fichas_tecnicas (
    produto_id,
    tipo,
    codigo_documento,
    numero_revisao,
    status,
    vigente,
    elaborado_por,
    motivo_revisao,
    data_emissao,
    revisao_origem_id,
    etapa_aprovacao
  ) values (
    v_origem.produto_id,
    v_origem.tipo,
    v_origem.codigo_documento,
    p_numero_revisao,
    'RASCUNHO',
    false,
    v_usuario_id,
    p_motivo_revisao,
    p_data_emissao,
    v_origem.id,
    null
  )
  returning id into v_nova_ficha_id;

  insert into public.valores_parametros (
    ficha_tecnica_id,
    parametro_id,
    valor_texto,
    valor_numerico,
    valor_minimo,
    valor_alvo,
    valor_maximo,
    valor_booleano,
    valor_data,
    valor_inicial,
    valor_final,
    nao_aplicavel,
    observacao
  )
  select
    v_nova_ficha_id,
    valor.parametro_id,
    valor.valor_texto,
    valor.valor_numerico,
    valor.valor_minimo,
    valor.valor_alvo,
    valor.valor_maximo,
    valor.valor_booleano,
    valor.valor_data,
    valor.valor_inicial,
    valor.valor_final,
    valor.nao_aplicavel,
    valor.observacao
  from public.valores_parametros valor
  where valor.ficha_tecnica_id = v_origem.id;

  insert into public.auditoria_importacao_ficha (
    importacao_id,
    ficha_tecnica_id,
    usuario_id,
    evento,
    detalhes
  )
  select
    importacao.id,
    v_nova_ficha_id,
    v_usuario_id,
    'NOVA_REVISAO_CRIADA',
    jsonb_build_object(
      'ficha_origem_id',
      v_origem.id,
      'numero_revisao',
      p_numero_revisao
    )
  from public.importacoes_ficha importacao
  where importacao.ficha_tecnica_id = v_origem.id;

  return v_nova_ficha_id;
end;
$$;

revoke all on function public.registrar_evento_importacao(
  bigint, text, jsonb
) from public;
revoke all on function public.salvar_importacao_ficha(
  bigint, text, text, integer, date, text, text, jsonb, jsonb,
  jsonb, jsonb, jsonb, text, text, text, bigint, text, bigint
) from public;
revoke all on function public.enviar_importacao_validacao(bigint)
  from public;
revoke all on function public.validar_importacao_ficha(
  bigint, text, text, boolean
) from public;
revoke all on function public.criar_nova_revisao_ficha(
  bigint, integer, text, date
) from public;

grant execute on function public.registrar_evento_importacao(
  bigint, text, jsonb
) to authenticated;
grant execute on function public.salvar_importacao_ficha(
  bigint, text, text, integer, date, text, text, jsonb, jsonb,
  jsonb, jsonb, jsonb, text, text, text, bigint, text, bigint
) to authenticated;
grant execute on function public.enviar_importacao_validacao(bigint)
  to authenticated;
grant execute on function public.validar_importacao_ficha(
  bigint, text, text, boolean
) to authenticated;
grant execute on function public.criar_nova_revisao_ficha(
  bigint, integer, text, date
) to authenticated;

insert into public.importacoes_ficha (
  ficha_tecnica_id,
  estado,
  template_codigo,
  versao_extrator,
  resultado_extracao,
  avisos,
  criado_por
)
select
  ficha.id,
  'IMPORTACAO_RASCUNHO',
  case ficha.tipo
    when 'MOLDAGEM' then 'moldagem_v1'
    when 'FUSAO_VAZAMENTO' then 'fusao_vazamento_v1'
  end,
  'assistido-manual-1',
  jsonb_build_object(
    'origem',
    'migration_003',
    'observacao',
    'Importação histórica existente aguardando PDF e validação administrativa.'
  ),
  '["PDF original deve ser anexado antes da validação administrativa."]'::jsonb,
  ficha.elaborado_por
from public.fichas_tecnicas ficha
join public.produtos produto on produto.id = ficha.produto_id
where upper(trim(produto.codigo)) = 'MS0013'
  and (
    (ficha.tipo = 'MOLDAGEM' and ficha.numero_revisao = 22)
    or (
      ficha.tipo = 'FUSAO_VAZAMENTO'
      and ficha.numero_revisao = 56
    )
  )
  and not exists (
    select 1
    from public.importacoes_ficha importacao
    where importacao.ficha_tecnica_id = ficha.id
  );

update public.fichas_tecnicas ficha
set vigente = false
from public.importacoes_ficha importacao,
  public.produtos produto
where ficha.id = importacao.ficha_tecnica_id
  and produto.id = ficha.produto_id
  and importacao.estado in (
    'IMPORTACAO_RASCUNHO',
    'IMPORTACAO_PENDENTE_VALIDACAO',
    'REJEITADA'
  )
  and upper(trim(produto.codigo)) = 'MS0013'
  and (
    (ficha.tipo = 'MOLDAGEM' and ficha.numero_revisao = 22)
    or (
      ficha.tipo = 'FUSAO_VAZAMENTO'
      and ficha.numero_revisao = 56
    )
  );

notify pgrst, 'reload schema';

commit;
