begin;

-- Análise térmica do Holding — vale até a próxima (não precisa repetir a
-- cada panela). "Última válida" é sempre a mais recente por forno, sem
-- fluxo de vigência (diferente da ficha técnica — não é necessário aqui).
create table public.analises_termicas_holding (
  id bigint generated by default as identity primary key,
  forno_id bigint not null references public.fornos_fusao(id),
  carbono_equivalente numeric,
  carbono numeric,
  delta_t numeric,
  temp_liquidus numeric,
  temp_solidus numeric,
  medido_em timestamptz not null default now(),
  autor_id uuid references public.usuarios(id),
  criado_em timestamptz not null default now()
);

create index analises_termicas_holding_forno_idx on public.analises_termicas_holding(forno_id, medido_em desc);

alter table public.analises_termicas_holding enable row level security;

create policy analises_termicas_holding_select on public.analises_termicas_holding
  for select to authenticated using (auth.uid() is not null);

grant select on public.analises_termicas_holding to authenticated;

create or replace function public.registrar_analise_termica_holding(
  p_forno_id bigint, p_carbono_equivalente numeric, p_carbono numeric,
  p_delta_t numeric, p_temp_liquidus numeric, p_temp_solidus numeric
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_forno record;
  v_corrida_aberta bigint;
  v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  select * into v_forno from public.fornos_fusao where id = p_forno_id;
  if not found then raise exception 'Forno não encontrado.'; end if;
  if v_forno.tipo <> 'HOLDING' then raise exception 'Análise térmica é só pra forno Holding.'; end if;

  insert into public.analises_termicas_holding(forno_id, carbono_equivalente, carbono, delta_t, temp_liquidus, temp_solidus, autor_id)
  values (p_forno_id, p_carbono_equivalente, p_carbono, p_delta_t, p_temp_liquidus, p_temp_solidus, auth.uid())
  returning id into v_id;

  select id into v_corrida_aberta from public.corridas_fusao where forno_id = p_forno_id and status = 'ABERTA';
  if v_corrida_aberta is not null then
    insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
    values (v_corrida_aberta, auth.uid(), format('registrou nova análise térmica (CE %s)',
      coalesce(p_carbono_equivalente::text, '—')));
  end if;

  return v_id;
end;
$$;

revoke all on function public.registrar_analise_termica_holding(bigint,numeric,numeric,numeric,numeric,numeric) from public, anon;
grant execute on function public.registrar_analise_termica_holding(bigint,numeric,numeric,numeric,numeric,numeric) to authenticated;

-- CE da panela nova passa a herdar da última análise térmica do Holding
-- (fonte mais confiável que copiar da panela anterior); os demais campos
-- herdados continuam vindo da última panela válida, como já era.
create or replace function public.criar_panela_holding(
  p_holding_corrida_id bigint, p_peso_kg numeric, p_hora_retirada timestamptz,
  p_fesimg_liga1_kg numeric default null, p_fesimg_liga4_kg numeric default null
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_corrida record;
  v_forno record;
  v_ultima record;
  v_analise record;
  v_sequencia integer;
  v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if coalesce(p_peso_kg, 0) <= 0 then raise exception 'Informe um peso maior que zero.'; end if;
  if p_hora_retirada is null then raise exception 'Informe o horário da retirada.'; end if;

  select * into v_corrida from public.corridas_fusao where id = p_holding_corrida_id for update;
  if not found then raise exception 'Corrida do Holding não encontrada.'; end if;
  if v_corrida.status <> 'ABERTA' then raise exception 'A corrida do Holding precisa estar aberta.'; end if;

  select * into v_forno from public.fornos_fusao where id = v_corrida.forno_id;
  if v_forno.tipo <> 'HOLDING' then raise exception 'Esta corrida não é de um Holding.'; end if;

  select coalesce(max(sequencial), 0) + 1 into v_sequencia
  from public.panelas_holding where holding_corrida_id = p_holding_corrida_id;

  select panela.* into v_ultima
  from public.panelas_holding panela
  join public.corridas_fusao corrida on corrida.id = panela.holding_corrida_id
  where corrida.forno_id = v_forno.id and panela.status <> 'REJEITADA'
  order by panela.criado_em desc limit 1;

  select * into v_analise from public.analises_termicas_holding
  where forno_id = v_forno.id order by medido_em desc limit 1;

  insert into public.panelas_holding(
    holding_corrida_id, sequencial, produto_id, hora_retirada, peso_kg,
    temperatura_c, carbono_equivalente, fesimg_liga1_kg, fesimg_liga4_kg,
    inoculante_kg, silicio_kg, grafite_kg, sucata_cobertura_kg, criado_por
  ) values (
    p_holding_corrida_id, v_sequencia, v_corrida.produto_id, p_hora_retirada, p_peso_kg,
    v_ultima.temperatura_c, v_analise.carbono_equivalente, p_fesimg_liga1_kg, p_fesimg_liga4_kg,
    v_ultima.inoculante_kg, v_ultima.silicio_kg, v_ultima.grafite_kg, v_ultima.sucata_cobertura_kg, auth.uid()
  ) returning id into v_id;

  insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
  values (p_holding_corrida_id, auth.uid(), format('retirou a panela Nº %s do Holding (%s kg)', v_sequencia, p_peso_kg));

  return v_id;
end;
$$;

notify pgrst, 'reload schema';

commit;
