begin;

-- Análise térmica do Vazamento — mesmo modelo da análise térmica do
-- Holding (etapa 5), mas sem forno_id: o Vazamento é uma estação só (não
-- um forno por Holding). Vale até a próxima, "última" é a mais recente.
create table public.analises_termicas_vazamento (
  id bigint generated by default as identity primary key,
  carbono_equivalente numeric,
  carbono numeric,
  delta_t numeric,
  temp_liquidus numeric,
  temp_solidus numeric,
  medido_em timestamptz not null default now(),
  autor_id uuid references public.usuarios(id),
  criado_em timestamptz not null default now()
);

create index analises_termicas_vazamento_medido_idx on public.analises_termicas_vazamento(medido_em desc);

alter table public.analises_termicas_vazamento enable row level security;

create policy analises_termicas_vazamento_select on public.analises_termicas_vazamento
  for select to authenticated using (auth.uid() is not null);

grant select on public.analises_termicas_vazamento to authenticated;

create or replace function public.registrar_analise_termica_vazamento(
  p_carbono_equivalente numeric, p_carbono numeric,
  p_delta_t numeric, p_temp_liquidus numeric, p_temp_solidus numeric
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_id bigint;
begin
  if not (public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar')
       or public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar_vazamento')) then
    raise exception 'Usuário sem permissão para lançar vazamento.';
  end if;
  insert into public.analises_termicas_vazamento(carbono_equivalente, carbono, delta_t, temp_liquidus, temp_solidus, autor_id)
  values (p_carbono_equivalente, p_carbono, p_delta_t, p_temp_liquidus, p_temp_solidus, auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.registrar_analise_termica_vazamento(numeric,numeric,numeric,numeric,numeric) from public, anon;
grant execute on function public.registrar_analise_termica_vazamento(numeric,numeric,numeric,numeric,numeric) to authenticated;

-- Produto da panela passa a ser editável (o Vazamento pode precisar
-- corrigir o produto herdado da corrida do Holding antes de apontar).
create or replace function public.atualizar_produto_panela_holding(
  p_panela_id bigint, p_produto_id bigint
) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_panela record;
begin
  if not (public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar')
       or public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar_vazamento')) then
    raise exception 'Usuário sem permissão para lançar vazamento.';
  end if;
  if not exists(select 1 from public.produtos where id = p_produto_id) then
    raise exception 'Produto inválido.';
  end if;
  select * into v_panela from public.panelas_holding where id = p_panela_id;
  if not found then raise exception 'Panela não encontrada.'; end if;

  update public.panelas_holding
  set produto_id = p_produto_id, atualizado_por = auth.uid(), atualizado_em = now()
  where id = p_panela_id;

  insert into public.corridas_fusao_alteracoes(corrida_id, autor_id, descricao)
  values (v_panela.holding_corrida_id, auth.uid(), format('alterou o produto da panela Nº %s', v_panela.sequencial));
end;
$$;

revoke all on function public.atualizar_produto_panela_holding(bigint,bigint) from public, anon;
grant execute on function public.atualizar_produto_panela_holding(bigint,bigint) to authenticated;

notify pgrst, 'reload schema';

commit;
