begin;

create table if not exists public.medicoes_temperatura_vazamento (
  id bigint generated by default as identity primary key,
  origem_registro text not null,
  medido_em timestamptz not null,
  item text not null,
  temperatura numeric(8,2) not null,
  temperatura_minima numeric(8,2),
  temperatura_maxima numeric(8,2),
  tempo_vazamento numeric(12,2),
  recebido_em timestamptz not null default now(),
  constraint medicoes_temperatura_faixa_valida check (
    temperatura_minima is null
    or temperatura_maxima is null
    or temperatura_minima <= temperatura_maxima
  ),
  constraint medicoes_temperatura_origem_unica unique (origem_registro)
);

create index if not exists medicoes_temperatura_periodo_idx
on public.medicoes_temperatura_vazamento(medido_em desc);

create index if not exists medicoes_temperatura_item_periodo_idx
on public.medicoes_temperatura_vazamento(item,medido_em desc);

alter table public.medicoes_temperatura_vazamento
enable row level security;

create policy medicoes_temperatura_select
on public.medicoes_temperatura_vazamento
for select to authenticated
using (
  public.usuario_tem_permissao_producao_moldes(
    'controle_processo.visualizar'
  )
);

grant select on public.medicoes_temperatura_vazamento
to authenticated;

commit;
