begin;

-- ==========================================================================
-- Módulo de Fusão — Fase 1 (planejamento da carga até a corrida "pronta"
-- pra transferência; Holding/panela/vazamento ficam pra uma Fase 2).
--
-- Vários papéis mexem na MESMA corrida ao mesmo tempo (supervisor planeja,
-- operador da ponte pesa, operador do forno registra adição e avança
-- status) — por isso, ao contrário das telas de turno (Moldagem/Acabamento/
-- Macharia, que usam 1 rascunho JSON com versão), aqui cada ação vira uma
-- RPC pequena e independente, mexendo só na própria linha/coluna. Só a
-- transição de status da corrida usa "versao" (trava optimista), pra dois
-- cliques simultâneos em "concluir" não avançarem duas vezes.
-- ==========================================================================

insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'PRODUCAO',true from (values
  ('producao_fusao.visualizar','Visualizar produção de fusão','Consulta corridas, cargas e indicadores da Fusão.'),
  ('producao_fusao.lancar','Lançar produção de fusão','Planeja carga, registra pesagem, adições e avança o status da corrida.'),
  ('producao_fusao.editar','Editar produção de fusão','Corrige registros de uma corrida já concluída ou cancela uma corrida.'),
  ('producao_fusao.configurar','Configurar cadastros de fusão','Cadastra materiais, fornos e troca de refratário.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id from public.perfis profile
cross join public.permissoes permission
where (upper(profile.codigo) in ('ADMIN','ADMINISTRADOR') or upper(profile.nome)='ADMINISTRADOR')
and permission.codigo like 'producao_fusao.%'
and not exists(select 1 from public.perfil_permissoes relation
  where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select perfil.id,permissao.id from public.perfis perfil
join public.permissoes permissao on permissao.codigo in ('producao_fusao.visualizar','producao_fusao.lancar')
where upper(coalesce(perfil.codigo,'')) in ('FUSAO','COORDENADOR_PRODUCAO','GERENTE_PRODUCAO')
on conflict do nothing;

insert into public.perfil_permissoes(perfil_id,permissao_id)
select perfil.id,permissao.id from public.perfis perfil
join public.permissoes permissao on permissao.codigo in ('producao_fusao.editar','producao_fusao.configurar')
where upper(coalesce(perfil.codigo,'')) in ('COORDENADOR_PRODUCAO','GERENTE_PRODUCAO')
on conflict do nothing;

-- Mesmo corpo usado em todos os domínios de produção (ver
-- usuario_tem_permissao_producao_macharia/acabamento).
create or replace function public.usuario_tem_permissao_producao_fusao(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select user_permission.permitido
     from public.usuario_permissoes user_permission
     join public.permissoes permission on permission.id=user_permission.permissao_id
     where user_permission.usuario_id=auth.uid()
       and permission.codigo=p_codigo limit 1),
    exists(select 1 from public.usuario_perfis user_profile
      join public.perfil_permissoes profile_permission
        on profile_permission.perfil_id=user_profile.perfil_id
      join public.permissoes permission
        on permission.id=profile_permission.permissao_id
      where user_profile.usuario_id=auth.uid() and permission.codigo=p_codigo)
  );
$$;

-- ==========================================================================
-- Cadastros
-- ==========================================================================
create table if not exists public.materiais_fusao (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  tipo text not null check (tipo in ('SUCATA','RETORNO','CANAL','LIGA_CORRECAO','OUTRO')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);
alter table public.materiais_fusao enable row level security;
drop policy if exists materiais_fusao_select on public.materiais_fusao;
create policy materiais_fusao_select on public.materiais_fusao for select to authenticated using (auth.uid() is not null);
grant select on public.materiais_fusao to authenticated;
grant usage,select on sequence public.materiais_fusao_id_seq to authenticated;

-- Fornos de elaboração (tipo FUSAO) e Holdings (tipo HOLDING, só recebem/
-- mantêm — usados na Fase 2). Limites de corridas do refratário ficam aqui,
-- por forno, pra dar pra ajustar sem mexer em código.
create table if not exists public.fornos_fusao (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  tipo text not null check (tipo in ('FUSAO','HOLDING')),
  limite_atencao_corridas integer not null default 100,
  limite_critico_corridas integer not null default 150,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  check (limite_critico_corridas >= limite_atencao_corridas)
);
alter table public.fornos_fusao enable row level security;
drop policy if exists fornos_fusao_select on public.fornos_fusao;
create policy fornos_fusao_select on public.fornos_fusao for select to authenticated using (auth.uid() is not null);
grant select on public.fornos_fusao to authenticated;
grant usage,select on sequence public.fornos_fusao_id_seq to authenticated;

create or replace function public.salvar_material_fusao(
  p_id bigint, p_codigo text, p_nome text, p_tipo text, p_ativo boolean default true
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.configurar') then
    raise exception 'Usuário sem permissão para configurar cadastros de fusão.';
  end if;
  if p_tipo not in ('SUCATA','RETORNO','CANAL','LIGA_CORRECAO','OUTRO') then raise exception 'Tipo de material inválido.'; end if;
  if p_id is null then
    insert into public.materiais_fusao(codigo,nome,tipo,ativo) values(trim(p_codigo),trim(p_nome),p_tipo,coalesce(p_ativo,true))
    returning id into v_id;
  else
    update public.materiais_fusao set codigo=trim(p_codigo),nome=trim(p_nome),tipo=p_tipo,ativo=coalesce(p_ativo,true)
    where id=p_id returning id into v_id;
  end if;
  return v_id;
end;
$$;
revoke all on function public.salvar_material_fusao(bigint,text,text,text,boolean) from public,anon;
grant execute on function public.salvar_material_fusao(bigint,text,text,text,boolean) to authenticated;

create or replace function public.salvar_forno_fusao(
  p_id bigint, p_codigo text, p_nome text, p_tipo text,
  p_limite_atencao integer default 100, p_limite_critico integer default 150, p_ativo boolean default true
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.configurar') then
    raise exception 'Usuário sem permissão para configurar cadastros de fusão.';
  end if;
  if p_tipo not in ('FUSAO','HOLDING') then raise exception 'Tipo de forno inválido.'; end if;
  if p_id is null then
    insert into public.fornos_fusao(codigo,nome,tipo,limite_atencao_corridas,limite_critico_corridas,ativo)
    values(trim(p_codigo),trim(p_nome),p_tipo,coalesce(p_limite_atencao,100),coalesce(p_limite_critico,150),coalesce(p_ativo,true))
    returning id into v_id;
  else
    update public.fornos_fusao set codigo=trim(p_codigo),nome=trim(p_nome),tipo=p_tipo,
      limite_atencao_corridas=coalesce(p_limite_atencao,100),limite_critico_corridas=coalesce(p_limite_critico,150),ativo=coalesce(p_ativo,true)
    where id=p_id returning id into v_id;
  end if;
  return v_id;
end;
$$;
revoke all on function public.salvar_forno_fusao(bigint,text,text,text,integer,integer,boolean) from public,anon;
grant execute on function public.salvar_forno_fusao(bigint,text,text,text,integer,integer,boolean) to authenticated;

-- ==========================================================================
-- Ciclo de vida do refratário — só 1 ciclo "aberto" (encerrado_em null) por
-- forno de cada vez; a contagem de corridas nele é o indicador de desgaste.
-- ==========================================================================
create table if not exists public.ciclos_refratario_fusao (
  id bigint generated by default as identity primary key,
  forno_id bigint not null references public.fornos_fusao(id),
  numero_ciclo integer not null,
  iniciado_em timestamptz not null default now(),
  iniciado_por uuid references public.usuarios(id),
  encerrado_em timestamptz,
  motivo_encerramento text,
  unique(forno_id, numero_ciclo)
);
create unique index if not exists ciclos_refratario_fusao_aberto_uidx
  on public.ciclos_refratario_fusao(forno_id) where encerrado_em is null;
alter table public.ciclos_refratario_fusao enable row level security;
drop policy if exists ciclos_refratario_fusao_select on public.ciclos_refratario_fusao;
create policy ciclos_refratario_fusao_select on public.ciclos_refratario_fusao for select to authenticated using (auth.uid() is not null);
grant select on public.ciclos_refratario_fusao to authenticated;
grant usage,select on sequence public.ciclos_refratario_fusao_id_seq to authenticated;

-- Abre um novo ciclo pro forno (trocou o refratário), encerrando o anterior
-- se existir. Se for a primeira vez do forno, só abre o ciclo 1.
create or replace function public.trocar_refratario_fusao(p_forno_id bigint, p_motivo text default null)
returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_novo_numero integer; v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para registrar troca de refratário.';
  end if;
  update public.ciclos_refratario_fusao set encerrado_em=now(), motivo_encerramento=nullif(trim(p_motivo),'')
  where forno_id=p_forno_id and encerrado_em is null;
  select coalesce(max(numero_ciclo),0)+1 into v_novo_numero from public.ciclos_refratario_fusao where forno_id=p_forno_id;
  insert into public.ciclos_refratario_fusao(forno_id,numero_ciclo,iniciado_por)
  values(p_forno_id,v_novo_numero,auth.uid()) returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.trocar_refratario_fusao(bigint,text) from public,anon;
grant execute on function public.trocar_refratario_fusao(bigint,text) to authenticated;

-- ==========================================================================
-- Corrida — 1 carga elaborada em 1 forno, dentro do ciclo de refratário
-- ativo dele. Código único gerado (forno + ciclo + sequência, ex.:
-- "H1100235" — sem separador, 1 campo de texto só).
-- ==========================================================================
create table if not exists public.corridas_fusao (
  id bigint generated by default as identity primary key,
  forno_id bigint not null references public.fornos_fusao(id),
  ciclo_refratario_id bigint not null references public.ciclos_refratario_fusao(id),
  numero_sequencia integer not null,
  codigo text not null unique,
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  status text not null default 'PLANEJADA' check (status in ('PLANEJADA','CARREGANDO','ELABORACAO','PRONTA','TRANSFERIDA','CANCELADA')),
  versao bigint not null default 0,
  criado_por uuid references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  unique(ciclo_refratario_id, numero_sequencia)
);
create index if not exists corridas_fusao_forno_idx on public.corridas_fusao(forno_id, criado_em desc);
alter table public.corridas_fusao enable row level security;
drop policy if exists corridas_fusao_select on public.corridas_fusao;
create policy corridas_fusao_select on public.corridas_fusao for select to authenticated using (auth.uid() is not null);
grant select on public.corridas_fusao to authenticated;
grant usage,select on sequence public.corridas_fusao_id_seq to authenticated;

create table if not exists public.corridas_fusao_carga_itens (
  id bigint generated by default as identity primary key,
  corrida_id bigint not null references public.corridas_fusao(id) on delete cascade,
  material_id bigint not null references public.materiais_fusao(id),
  quantidade_planejada_kg numeric not null check (quantidade_planejada_kg >= 0),
  quantidade_realizada_kg numeric check (quantidade_realizada_kg >= 0),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz,
  unique(corrida_id, material_id)
);
alter table public.corridas_fusao_carga_itens enable row level security;
drop policy if exists corridas_fusao_carga_itens_select on public.corridas_fusao_carga_itens;
create policy corridas_fusao_carga_itens_select on public.corridas_fusao_carga_itens for select to authenticated using (auth.uid() is not null);
grant select on public.corridas_fusao_carga_itens to authenticated;
grant usage,select on sequence public.corridas_fusao_carga_itens_id_seq to authenticated;

create table if not exists public.corridas_fusao_adicoes (
  id bigint generated by default as identity primary key,
  corrida_id bigint not null references public.corridas_fusao(id) on delete cascade,
  material_id bigint not null references public.materiais_fusao(id),
  quantidade_kg numeric not null check (quantidade_kg > 0),
  adicionado_em timestamptz not null default now(),
  adicionado_por uuid references public.usuarios(id)
);
alter table public.corridas_fusao_adicoes enable row level security;
drop policy if exists corridas_fusao_adicoes_select on public.corridas_fusao_adicoes;
create policy corridas_fusao_adicoes_select on public.corridas_fusao_adicoes for select to authenticated using (auth.uid() is not null);
grant select on public.corridas_fusao_adicoes to authenticated;
grant usage,select on sequence public.corridas_fusao_adicoes_id_seq to authenticated;

create table if not exists public.paradas_producao_fusao (
  id bigint generated by default as identity primary key,
  forno_id bigint not null references public.fornos_fusao(id),
  corrida_id bigint references public.corridas_fusao(id),
  categoria_id bigint references public.categorias_parada_producao(id),
  setor_responsavel_id bigint references public.setores_responsaveis_parada(id),
  inicio timestamptz not null,
  fim timestamptz,
  duracao_minutos integer,
  observacao text,
  criado_por uuid references public.usuarios(id),
  criado_em timestamptz not null default now()
);
alter table public.paradas_producao_fusao enable row level security;
drop policy if exists paradas_producao_fusao_select on public.paradas_producao_fusao;
create policy paradas_producao_fusao_select on public.paradas_producao_fusao for select to authenticated using (auth.uid() is not null);
grant select on public.paradas_producao_fusao to authenticated;
grant usage,select on sequence public.paradas_producao_fusao_id_seq to authenticated;

-- ==========================================================================
-- RPCs de apontamento — 1 ação por papel, sem rascunho compartilhado (ver
-- comentário no topo do arquivo).
-- ==========================================================================

-- Supervisor: cria a corrida com a carga planejada. Usa o ciclo de
-- refratário aberto do forno (cria o ciclo 1 automaticamente se o forno
-- nunca teve nenhum). Trava a linha do ciclo pra gerar a sequência sem
-- risco de 2 corridas nascerem com o mesmo número.
create or replace function public.criar_corrida_fusao(
  p_forno_id bigint, p_turno text, p_itens jsonb
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_ciclo record;
  v_forno record;
  v_sequencia integer;
  v_codigo text;
  v_corrida_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_array_length(coalesce(p_itens,'[]'::jsonb)) = 0 then raise exception 'Informe ao menos um material na carga.'; end if;

  select * into v_forno from public.fornos_fusao where id = p_forno_id and tipo = 'FUSAO' for update;
  if not found then raise exception 'Forno inválido.'; end if;

  select * into v_ciclo from public.ciclos_refratario_fusao where forno_id = p_forno_id and encerrado_em is null for update;
  if not found then
    insert into public.ciclos_refratario_fusao(forno_id, numero_ciclo, iniciado_por)
    values (p_forno_id, 1, auth.uid())
    returning * into v_ciclo;
  end if;

  select coalesce(max(numero_sequencia), 0) + 1 into v_sequencia
  from public.corridas_fusao where ciclo_refratario_id = v_ciclo.id;
  v_codigo := v_forno.codigo || lpad(v_ciclo.numero_ciclo::text, 3, '0') || lpad(v_sequencia::text, 3, '0');

  insert into public.corridas_fusao(forno_id, ciclo_refratario_id, numero_sequencia, codigo, data_operacional, turno, criado_por, atualizado_por)
  values (p_forno_id, v_ciclo.id, v_sequencia, v_codigo, current_date, p_turno, auth.uid(), auth.uid())
  returning id into v_corrida_id;

  insert into public.corridas_fusao_carga_itens(corrida_id, material_id, quantidade_planejada_kg)
  select v_corrida_id, item.material_id, item.quantidade_planejada_kg
  from jsonb_to_recordset(p_itens) as item(material_id bigint, quantidade_planejada_kg numeric)
  where item.material_id is not null and item.quantidade_planejada_kg >= 0;

  return v_corrida_id;
end;
$$;
revoke all on function public.criar_corrida_fusao(bigint,text,jsonb) from public,anon;
grant execute on function public.criar_corrida_fusao(bigint,text,jsonb) to authenticated;

-- Operador da ponte: registra o realizado de 1 material por vez — não
-- conflita com o planejamento (coluna diferente) nem com outro material
-- sendo pesado ao mesmo tempo (linha diferente).
create or replace function public.atualizar_pesagem_carga_fusao(
  p_corrida_id bigint, p_material_id bigint, p_quantidade_realizada_kg numeric
) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if p_quantidade_realizada_kg is not null and p_quantidade_realizada_kg < 0 then
    raise exception 'Quantidade realizada não pode ser negativa.';
  end if;
  update public.corridas_fusao_carga_itens
  set quantidade_realizada_kg = p_quantidade_realizada_kg, atualizado_por = auth.uid(), atualizado_em = now()
  where corrida_id = p_corrida_id and material_id = p_material_id;
  if not found then raise exception 'Item de carga não encontrado nesta corrida.'; end if;
end;
$$;
revoke all on function public.atualizar_pesagem_carga_fusao(bigint,bigint,numeric) from public,anon;
grant execute on function public.atualizar_pesagem_carga_fusao(bigint,bigint,numeric) to authenticated;

-- Operador do forno: registra 1 adição de liga/correção (insert simples,
-- sem conflito possível).
create or replace function public.registrar_adicao_fusao(
  p_corrida_id bigint, p_material_id bigint, p_quantidade_kg numeric
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if coalesce(p_quantidade_kg,0) <= 0 then raise exception 'Quantidade da adição deve ser maior que zero.'; end if;
  insert into public.corridas_fusao_adicoes(corrida_id, material_id, quantidade_kg, adicionado_por)
  values (p_corrida_id, p_material_id, p_quantidade_kg, auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.registrar_adicao_fusao(bigint,bigint,numeric) from public,anon;
grant execute on function public.registrar_adicao_fusao(bigint,bigint,numeric) to authenticated;

-- Avança (ou cancela) o status da corrida — única ação com trava de versão,
-- pra 2 cliques simultâneos em "concluir etapa" não pularem 2 estados.
create or replace function public.avancar_status_corrida_fusao(
  p_corrida_id bigint, p_novo_status text, p_versao bigint
) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_corrida record;
  v_ordem text[] := array['PLANEJADA','CARREGANDO','ELABORACAO','PRONTA','TRANSFERIDA'];
  v_atual_pos integer; v_novo_pos integer;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  select * into v_corrida from public.corridas_fusao where id = p_corrida_id for update;
  if not found then raise exception 'Corrida não encontrada.'; end if;
  if v_corrida.versao <> p_versao then
    raise exception 'CONFLITO_RASCUNHO: a corrida foi atualizada por outro usuário.' using errcode = '40001';
  end if;
  if v_corrida.status in ('TRANSFERIDA','CANCELADA') then
    raise exception 'Esta corrida já foi encerrada.';
  end if;
  if p_novo_status = 'CANCELADA' then
    update public.corridas_fusao set status='CANCELADA', versao=versao+1, atualizado_por=auth.uid(), atualizado_em=now()
    where id = p_corrida_id;
    return;
  end if;
  v_atual_pos := array_position(v_ordem, v_corrida.status);
  v_novo_pos := array_position(v_ordem, p_novo_status);
  if v_novo_pos is null or v_novo_pos <> v_atual_pos + 1 then
    raise exception 'Transição de status inválida (% -> %).', v_corrida.status, p_novo_status;
  end if;
  update public.corridas_fusao set status = p_novo_status, versao = versao + 1, atualizado_por = auth.uid(), atualizado_em = now()
  where id = p_corrida_id;
end;
$$;
revoke all on function public.avancar_status_corrida_fusao(bigint,text,bigint) from public,anon;
grant execute on function public.avancar_status_corrida_fusao(bigint,text,bigint) to authenticated;

notify pgrst, 'reload schema';

commit;
