begin;

insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select 'calendario_operacional.gerenciar','Gerenciar calendário operacional','Mantém feriados, férias coletivas, folgas e trabalhos excepcionais.','ADMINISTRACAO',true
where not exists(select 1 from public.permissoes where codigo='calendario_operacional.gerenciar');

insert into public.perfil_permissoes(perfil_id,permissao_id)
select perfil.id,permissao.id
from public.perfis perfil
join public.permissoes permissao on permissao.codigo='calendario_operacional.gerenciar'
where upper(perfil.codigo) in('ADMIN','ADMINISTRADOR','GERENTE_GERAL','GERENTE_PRODUCAO','COORDENADOR_PRODUCAO')
and not exists(
  select 1 from public.perfil_permissoes existente
  where existente.perfil_id=perfil.id and existente.permissao_id=permissao.id
);

create table if not exists public.calendario_operacional (
  id bigint generated by default as identity primary key,
  nome text not null check(length(trim(nome))>=3),
  tipo text not null check(tipo in('FERIADO','FERIAS_COLETIVAS','FOLGA_PROGRAMADA','TRABALHO_EXCEPCIONAL')),
  escopo text not null default 'EMPRESA' check(escopo in('FEDERAL','ESTADUAL','MUNICIPAL','EMPRESA')),
  data_inicio date not null,
  data_fim date not null,
  turno text not null default 'TODOS' check(turno in('TODOS','MANHA','TARDE','NOITE')),
  observacao text,
  ativo boolean not null default true,
  criado_por uuid default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid default auth.uid() references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  check(data_fim>=data_inicio),
  unique(nome,tipo,data_inicio,data_fim,turno)
);

create index if not exists calendario_operacional_periodo_idx
  on public.calendario_operacional(data_inicio,data_fim) where ativo=true;

alter table public.calendario_operacional enable row level security;
create policy calendario_operacional_select on public.calendario_operacional
for select to authenticated using(true);
create policy calendario_operacional_manage on public.calendario_operacional
for all to authenticated
using(public.usuario_tem_permissao_checklist('calendario_operacional.gerenciar'))
with check(public.usuario_tem_permissao_checklist('calendario_operacional.gerenciar'));

grant select,insert,update,delete on public.calendario_operacional to authenticated;
grant usage,select on sequence public.calendario_operacional_id_seq to authenticated;

insert into public.calendario_operacional(nome,tipo,escopo,data_inicio,data_fim,turno) values
('Confraternização Universal','FERIADO','FEDERAL','2026-01-01','2026-01-01','TODOS'),
('Paixão de Cristo','FERIADO','MUNICIPAL','2026-04-03','2026-04-03','TODOS'),
('Tiradentes','FERIADO','FEDERAL','2026-04-21','2026-04-21','TODOS'),
('Dia do Trabalho','FERIADO','FEDERAL','2026-05-01','2026-05-01','TODOS'),
('Corpus Christi','FERIADO','MUNICIPAL','2026-06-04','2026-06-04','TODOS'),
('Nossa Senhora do Carmo — Padroeira de Betim','FERIADO','MUNICIPAL','2026-07-16','2026-07-16','TODOS'),
('Independência do Brasil','FERIADO','FEDERAL','2026-09-07','2026-09-07','TODOS'),
('Nossa Senhora Aparecida','FERIADO','FEDERAL','2026-10-12','2026-10-12','TODOS'),
('Dia do Servidor','FERIADO','MUNICIPAL','2026-10-30','2026-10-30','TODOS'),
('Finados','FERIADO','FEDERAL','2026-11-02','2026-11-02','TODOS'),
('Proclamação da República','FERIADO','FEDERAL','2026-11-15','2026-11-15','TODOS'),
('Consciência Negra','FERIADO','FEDERAL','2026-11-20','2026-11-20','TODOS'),
('Natal','FERIADO','FEDERAL','2026-12-25','2026-12-25','TODOS')
on conflict(nome,tipo,data_inicio,data_fim,turno) do update set escopo=excluded.escopo,ativo=true;

notify pgrst,'reload schema';
commit;
