begin;
insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select 'paradas.configurar_codigos','Configurar códigos de parada','Mantém a matriz de área, equipamento, motivo e setor.','PRODUCAO',true
where not exists(select 1 from public.permissoes where codigo='paradas.configurar_codigos');
insert into public.perfil_permissoes(perfil_id,permissao_id)
select p.id,pm.id from public.perfis p join public.permissoes pm on pm.codigo='paradas.configurar_codigos'
where upper(p.codigo) in('ADMIN','ADMINISTRADOR','GERENTE_GERAL','GERENTE_PRODUCAO','COORDENADOR_PRODUCAO')
and not exists(select 1 from public.perfil_permissoes pp where pp.perfil_id=p.id and pp.permissao_id=pm.id);

alter table public.linhas_maquinas_producao add column if not exists area_id bigint references public.areas_checklist(id);
update public.linhas_maquinas_producao set area_id=(select id from public.areas_checklist where codigo='MOLDAGEM') where area_id is null;

create table if not exists public.motivos_genericos_parada(
 id bigint generated by default as identity primary key,codigo text,nome text not null,ativo boolean not null default true,
 criado_em timestamptz not null default now(),unique(nome));
create table if not exists public.codigos_parada_operacional(
 id bigint generated by default as identity primary key,area_id bigint not null references public.areas_checklist(id),
 equipamento_id bigint not null references public.linhas_maquinas_producao(id),motivo_id bigint not null references public.motivos_genericos_parada(id),
 setor_responsavel_id bigint not null references public.setores_responsaveis_parada(id),codigo text not null,
 ativo boolean not null default true,atualizado_por uuid default auth.uid() references public.usuarios(id),
 atualizado_em timestamptz not null default now(),unique(area_id,equipamento_id,motivo_id,setor_responsavel_id));
alter table public.motivos_genericos_parada enable row level security;alter table public.codigos_parada_operacional enable row level security;
create policy motivos_parada_select on public.motivos_genericos_parada for select to authenticated using(true);
create policy motivos_parada_manage on public.motivos_genericos_parada for all to authenticated using(public.usuario_tem_permissao_checklist('paradas.configurar_codigos')) with check(public.usuario_tem_permissao_checklist('paradas.configurar_codigos'));
create policy codigos_parada_select on public.codigos_parada_operacional for select to authenticated using(public.usuario_pode_acessar_area(area_id));
create policy codigos_parada_manage on public.codigos_parada_operacional for all to authenticated using(public.usuario_tem_permissao_checklist('paradas.configurar_codigos')) with check(public.usuario_tem_permissao_checklist('paradas.configurar_codigos'));
grant select,insert,update on public.motivos_genericos_parada,public.codigos_parada_operacional to authenticated;
grant usage,select on all sequences in schema public to authenticated;
notify pgrst,'reload schema';commit;
