begin;

-- ==========================================================================
-- Permissões
-- ==========================================================================
insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'PRODUCAO',true from (values
  ('producao_macharia.visualizar','Visualizar produção de macharia','Consulta apontamentos e indicadores de macharia.'),
  ('producao_macharia.lancar','Lançar produção de macharia','Registra sopros por estação de macharia.'),
  ('producao_macharia.editar','Editar produção de macharia','Corrige registros de um turno fechado de macharia.'),
  ('producao_macharia.excluir_turno','Excluir turno de macharia','Exclui integralmente um turno fechado de macharia e seus apontamentos.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id from public.perfis profile
cross join public.permissoes permission
where (upper(profile.codigo) in ('ADMIN','ADMINISTRADOR')
  or upper(profile.nome)='ADMINISTRADOR')
and permission.codigo like 'producao_macharia.%'
and not exists(select 1 from public.perfil_permissoes relation
  where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select perfil.id,permissao.id from public.perfis perfil
join public.permissoes permissao on permissao.codigo='producao_macharia.excluir_turno'
where upper(coalesce(perfil.codigo,'')) in ('GERENTE_PRODUCAO','COORDENADOR_PRODUCAO')
on conflict do nothing;

-- ==========================================================================
-- Tabelas
-- ==========================================================================
create table if not exists public.turnos_producao_macharia (
  id bigint generated by default as identity primary key,
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  status text not null default 'ABERTO' check (status in ('ABERTO','FECHADO')),
  fechado_por uuid references public.usuarios(id),
  fechado_em timestamptz,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  rascunho_producoes jsonb not null default '[]'::jsonb,
  versao bigint not null default 0,
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz,
  unique (data_operacional, turno),
  check ((status='ABERTO' and fechado_em is null) or
         (status='FECHADO' and fechado_em is not null and fechado_por is not null))
);

do $$ begin
  if not exists(select 1 from pg_catalog.pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='turnos_producao_macharia') then
    alter publication supabase_realtime add table public.turnos_producao_macharia;
  end if;
end $$;

-- Uma linha por sopro lançado numa estação/hora — máquina e estação em vez de
-- produto (o produto é resolvido depois, via machos_macharia_produtos).
create table if not exists public.registros_producao_macharia (
  id bigint generated by default as identity primary key,
  turno_producao_id bigint not null references public.turnos_producao_macharia(id),
  linha_maquina_id bigint not null references public.linhas_maquinas_producao(id),
  estacao integer not null check (estacao > 0),
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  horario_previsto timestamptz not null,
  macho_id bigint not null references public.machos_macharia(id),
  quantidade_sopros integer not null default 0 check (quantidade_sopros>=0),
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now()
);

create index if not exists registros_macharia_turno_idx
  on public.registros_producao_macharia(turno_producao_id);
create index if not exists registros_macharia_data_turno_idx
  on public.registros_producao_macharia(data_operacional desc, turno);
create index if not exists registros_macharia_linha_idx
  on public.registros_producao_macharia(linha_maquina_id, estacao, horario_previsto);

create table if not exists public.historico_edicoes_turno_macharia (
  id bigint generated by default as identity primary key,
  turno_producao_id bigint not null references public.turnos_producao_macharia(id) on delete cascade,
  descricao text not null check (length(trim(descricao)) between 1 and 1000),
  dados_anteriores jsonb not null default '{}'::jsonb,
  dados_novos jsonb not null default '{}'::jsonb,
  alterado_por uuid not null default auth.uid() references public.usuarios(id),
  alterado_em timestamptz not null default now()
);

create index if not exists historico_edicoes_turno_macharia_idx
  on public.historico_edicoes_turno_macharia(turno_producao_id, alterado_em desc);

-- ==========================================================================
-- Triggers
-- ==========================================================================
create or replace function public.validar_acesso_producao_macharia()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if not public.usuario_pode_acessar_area_codigo('MACHARIA') then
    raise exception 'Usuário sem acesso à área de Macharia.';
  end if;
  return new;
end $$;

drop trigger if exists validar_area_turno_macharia on public.turnos_producao_macharia;
create trigger validar_area_turno_macharia before insert or update on public.turnos_producao_macharia
for each row execute function public.validar_acesso_producao_macharia();
drop trigger if exists validar_area_registro_macharia on public.registros_producao_macharia;
create trigger validar_area_registro_macharia before insert or update on public.registros_producao_macharia
for each row execute function public.validar_acesso_producao_macharia();

-- ==========================================================================
-- RLS
-- ==========================================================================
alter table public.turnos_producao_macharia enable row level security;
alter table public.registros_producao_macharia enable row level security;
alter table public.historico_edicoes_turno_macharia enable row level security;

drop policy if exists turnos_macharia_select on public.turnos_producao_macharia;
create policy turnos_macharia_select on public.turnos_producao_macharia for select to authenticated using(
  public.usuario_tem_permissao_producao_macharia('producao_macharia.visualizar')
  and public.usuario_pode_acessar_area_codigo('MACHARIA'));
grant select on public.turnos_producao_macharia to authenticated;

drop policy if exists registros_macharia_select on public.registros_producao_macharia;
create policy registros_macharia_select on public.registros_producao_macharia for select to authenticated using(
  public.usuario_tem_permissao_producao_macharia('producao_macharia.visualizar')
  and public.usuario_pode_acessar_area_codigo('MACHARIA'));
drop policy if exists registros_macharia_insert on public.registros_producao_macharia;
create policy registros_macharia_insert on public.registros_producao_macharia for insert to authenticated with check(
  criado_por=auth.uid() and public.usuario_tem_permissao_producao_macharia('producao_macharia.lancar'));
drop policy if exists registros_macharia_update on public.registros_producao_macharia;
create policy registros_macharia_update on public.registros_producao_macharia for update to authenticated using(
  public.usuario_tem_permissao_producao_macharia('producao_macharia.editar'))
with check(public.usuario_tem_permissao_producao_macharia('producao_macharia.editar'));
grant select,insert,update on public.registros_producao_macharia to authenticated;

drop policy if exists historico_edicoes_macharia_select on public.historico_edicoes_turno_macharia;
create policy historico_edicoes_macharia_select on public.historico_edicoes_turno_macharia for select to authenticated using(
  public.usuario_tem_permissao_producao_macharia('producao_macharia.visualizar'));
grant select on public.historico_edicoes_turno_macharia to authenticated;

grant usage,select on sequence
  public.turnos_producao_macharia_id_seq,
  public.registros_producao_macharia_id_seq,
  public.historico_edicoes_turno_macharia_id_seq
to authenticated;

-- ==========================================================================
-- RPCs
-- ==========================================================================
create or replace function public.salvar_rascunho_turno_producao_macharia(
  p_data_operacional date,
  p_turno text,
  p_producoes jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_macharia%rowtype;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de macharia.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_typeof(coalesce(p_producoes,'[]'::jsonb))<>'array' then raise exception 'Rascunho inválido.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))>500 then raise exception 'O rascunho excede o limite de linhas.'; end if;

  insert into public.turnos_producao_macharia(data_operacional,turno,status,criado_por)
  values(p_data_operacional,p_turno,'ABERTO',auth.uid())
  on conflict(data_operacional,turno) do nothing;

  select * into v_turno from public.turnos_producao_macharia
  where data_operacional=p_data_operacional and turno=p_turno for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if (p_versao is null and v_turno.versao<>0) or (p_versao is not null and p_versao<>v_turno.versao) then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  update public.turnos_producao_macharia set
    rascunho_producoes=coalesce(p_producoes,'[]'::jsonb),
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id
  returning * into v_turno;

  return jsonb_build_object('id',v_turno.id,'versao',v_turno.versao,'atualizado_por',v_turno.atualizado_por,'atualizado_em',v_turno.atualizado_em);
end;
$$;
revoke all on function public.salvar_rascunho_turno_producao_macharia(date,text,jsonb,bigint) from public,anon;
grant execute on function public.salvar_rascunho_turno_producao_macharia(date,text,jsonb,bigint) to authenticated;

create or replace function public.fechar_turno_producao_macharia(
  p_data_operacional date,
  p_turno text,
  p_producoes jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_macharia%rowtype;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.lancar') then
    raise exception 'Usuário sem permissão para fechar o turno.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos um lançamento de sopro.'; end if;

  insert into public.turnos_producao_macharia(data_operacional,turno,status,criado_por)
  values(p_data_operacional,p_turno,'ABERTO',auth.uid())
  on conflict(data_operacional,turno) do nothing;

  select * into v_turno from public.turnos_producao_macharia
  where data_operacional=p_data_operacional and turno=p_turno for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if p_versao is not null and p_versao<>v_turno.versao then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_macharia(turno_producao_id,linha_maquina_id,estacao,data_operacional,turno,horario_previsto,macho_id,quantidade_sopros,criado_por)
  select v_turno.id,item.linha_id,item.estacao,p_data_operacional,p_turno,item.horario_previsto,item.macho_id,item.quantidade_sopros,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(linha_id bigint,estacao integer,horario_previsto timestamptz,macho_id bigint,quantidade_sopros integer)
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id and item.estacao between 1 and linha.numero_estacoes
  join public.machos_macharia macho on macho.id=item.macho_id and macho.status='APROVADO'
  where coalesce(item.quantidade_sopros,0)>=0 and item.horario_previsto is not null;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Um ou mais lançamentos são inválidos (máquina, estação ou macho).'; end if;

  update public.turnos_producao_macharia set
    status='FECHADO',fechado_por=auth.uid(),fechado_em=now(),
    rascunho_producoes='[]'::jsonb,
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id;
  return v_turno.id;
end;
$$;
revoke all on function public.fechar_turno_producao_macharia(date,text,jsonb,bigint) from public,anon;
grant execute on function public.fechar_turno_producao_macharia(date,text,jsonb,bigint) to authenticated;

create or replace function public.editar_turno_producao_macharia(
  p_turno_id bigint,
  p_producoes jsonb default '[]'::jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_macharia%rowtype;
  v_anteriores jsonb;
  v_novos jsonb;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.editar') then
    raise exception 'Usuário sem permissão para editar turnos fechados.';
  end if;
  select * into v_turno from public.turnos_producao_macharia where id=p_turno_id and status='FECHADO' for update;
  if not found then raise exception 'Turno fechado não encontrado.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos um lançamento de sopro.'; end if;

  select coalesce(jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,estacao,horario_previsto),'[]'::jsonb)
  into v_anteriores from public.registros_producao_macharia registro where turno_producao_id=p_turno_id;

  delete from public.registros_producao_macharia where turno_producao_id=p_turno_id;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_macharia(turno_producao_id,linha_maquina_id,estacao,data_operacional,turno,horario_previsto,macho_id,quantidade_sopros,criado_por)
  select v_turno.id,item.linha_id,item.estacao,v_turno.data_operacional,v_turno.turno,item.horario_previsto,item.macho_id,item.quantidade_sopros,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(linha_id bigint,estacao integer,horario_previsto timestamptz,macho_id bigint,quantidade_sopros integer)
  join public.linhas_maquinas_producao linha on linha.id=item.linha_id and item.estacao between 1 and linha.numero_estacoes
  join public.machos_macharia macho on macho.id=item.macho_id and macho.status='APROVADO'
  where coalesce(item.quantidade_sopros,0)>=0 and item.horario_previsto is not null;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Um ou mais lançamentos são inválidos (máquina, estação ou macho).'; end if;

  select coalesce(jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em' order by linha_maquina_id,estacao,horario_previsto),'[]'::jsonb)
  into v_novos from public.registros_producao_macharia registro where turno_producao_id=p_turno_id;

  if v_anteriores=v_novos then raise exception 'Nenhuma alteração foi identificada.'; end if;

  update public.turnos_producao_macharia set atualizado_por=auth.uid(),atualizado_em=now() where id=v_turno.id;

  insert into public.historico_edicoes_turno_macharia(
    turno_producao_id,descricao,dados_anteriores,dados_novos,alterado_por
  ) values (
    p_turno_id,'os apontamentos do turno',v_anteriores,v_novos,auth.uid()
  );
  return p_turno_id;
end;
$$;
grant execute on function public.editar_turno_producao_macharia(bigint,jsonb) to authenticated;

create or replace function public.excluir_turno_producao_macharia(p_turno_id bigint)
returns void language plpgsql security definer
set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_producao_macharia('producao_macharia.excluir_turno') then
    raise exception 'Usuário sem permissão para excluir turnos de macharia.';
  end if;
  if not exists(select 1 from public.turnos_producao_macharia where id=p_turno_id and status='FECHADO') then
    raise exception 'Turno fechado não encontrado.';
  end if;
  delete from public.registros_producao_macharia where turno_producao_id=p_turno_id;
  delete from public.historico_edicoes_turno_macharia where turno_producao_id=p_turno_id;
  delete from public.turnos_producao_macharia where id=p_turno_id;
end;
$$;
grant execute on function public.excluir_turno_producao_macharia(bigint) to authenticated;

notify pgrst,'reload schema';

commit;
