begin;

-- ---------------------------------------------------------------------------
-- Módulo SGI (Sistema de Gestão Integrado) — incremento 1: cadastro,
-- armazenamento (metadados), pesquisa e visualização de documentos externos.
-- Revisão/aprovação/histórico entram num incremento seguinte, depois de
-- validar este esqueleto funcionando de ponta a ponta.
--
-- O binário do arquivo NÃO fica no Supabase Storage nem no Postgres — por
-- decisão de negócio, os documentos controlados devem ficar em disco
-- local/rede interna da empresa (ver dev-server.cjs, rotas /api/arquivos/*
-- — um serviço de arquivos genérico da aplicação, não exclusivo do SGI).
-- Aqui só guardamos o caminho relativo e metadados do arquivo.
-- ---------------------------------------------------------------------------

-- Áreas responsáveis pelo documento (Qualidade/Engenharia/Manutenção/Produção
-- etc). Não reaproveita `areas_checklist` (escopada a produção/checklist) nem
-- `areas`/`usuario_areas` (órfãs, sem uso em código, sem RLS mantida).
create table if not exists public.sgi_areas (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ativo boolean not null default true
);

insert into public.sgi_areas (codigo, nome) values
  ('QUALIDADE', 'Qualidade'),
  ('ENGENHARIA', 'Engenharia'),
  ('MANUTENCAO', 'Manutenção'),
  ('PRODUCAO', 'Produção')
on conflict (codigo) do nothing;

-- Tipos de documento (IT, ET, PC, FMEA, Manual da Qualidade...). `template`
-- em jsonb permite adicionar tipo/campo novo sem migration nova (documentos
-- internos com template entram no incremento 2 — a coluna já nasce pronta).
create table if not exists public.sgi_tipos_documento (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  editavel boolean not null default true,
  template jsonb not null default '{}'::jsonb,
  area_aprovadora_padrao_id bigint references public.sgi_areas(id),
  ativo boolean not null default true
);

insert into public.sgi_tipos_documento (codigo, nome, editavel) values
  ('NORMA_EXTERNA', 'Norma / documento externo', false),
  ('MANUAL_QUALIDADE', 'Manual da Qualidade', true),
  ('ESPECIFICACAO_TECNICA', 'Especificação Técnica', true),
  ('INSTRUCAO_TRABALHO', 'Instrução de Trabalho', true),
  ('PLANO_CONTROLE', 'Plano de Controle', true),
  ('FMEA', 'FMEA', true)
on conflict (codigo) do nothing;

-- Registro do arquivo em disco — o binário mora fora do banco; aqui só o
-- caminho relativo (nunca absoluto) e metadados de integridade.
create table if not exists public.sgi_arquivos (
  id bigint generated by default as identity primary key,
  documento_id bigint,
  tipo text not null check (tipo in ('OFICIAL', 'EDITAVEL')),
  nome_original text not null,
  caminho_relativo text not null,
  mime_type text,
  tamanho_bytes bigint,
  hash_sha256 text,
  enviado_por uuid references public.usuarios(id),
  criado_em timestamptz not null default now()
);

-- Documento = 1 linha por revisão (mesmo padrão de `fichas_tecnicas`: a
-- revisão nova é uma linha nova, não uma tabela de snapshot separada).
create table if not exists public.sgi_documentos (
  id bigint generated by default as identity primary key,
  codigo text not null,
  titulo text not null,
  tipo_documento_id bigint not null references public.sgi_tipos_documento(id),
  origem text not null check (origem in ('INTERNO', 'EXTERNO')),
  numero_revisao integer not null default 0 check (numero_revisao >= 0),
  status text not null default 'EM_ELABORACAO' check (status in (
    'EM_ELABORACAO', 'EM_REVISAO', 'AGUARDANDO_APROVACAO', 'APROVADO', 'VIGENTE', 'OBSOLETO'
  )),
  vigente boolean not null default false,
  area_responsavel_id bigint references public.sgi_areas(id),
  processo_setor text,
  palavras_chave text,
  observacoes text,
  arquivo_oficial_id bigint references public.sgi_arquivos(id),
  arquivo_editavel_id bigint references public.sgi_arquivos(id),
  documento_anterior_id bigint references public.sgi_documentos(id),
  elaborado_por uuid references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (codigo, numero_revisao)
);

alter table public.sgi_arquivos
  add constraint sgi_arquivos_documento_id_fkey
  foreign key (documento_id) references public.sgi_documentos(id) on delete cascade;

create index if not exists sgi_documentos_codigo_idx on public.sgi_documentos (codigo);
create index if not exists sgi_documentos_vigente_idx on public.sgi_documentos (vigente) where vigente;

alter table public.sgi_areas enable row level security;
alter table public.sgi_tipos_documento enable row level security;
alter table public.sgi_arquivos enable row level security;
alter table public.sgi_documentos enable row level security;

create policy sgi_areas_select on public.sgi_areas for select to authenticated
  using (public.usuario_tem_permissao_sistema('sgi.visualizar'));

create policy sgi_tipos_documento_select on public.sgi_tipos_documento for select to authenticated
  using (public.usuario_tem_permissao_sistema('sgi.visualizar'));

create policy sgi_documentos_select on public.sgi_documentos for select to authenticated
  using (public.usuario_tem_permissao_sistema('sgi.visualizar'));

create policy sgi_arquivos_select on public.sgi_arquivos for select to authenticated
  using (public.usuario_tem_permissao_sistema('sgi.visualizar'));

grant select on public.sgi_areas, public.sgi_tipos_documento, public.sgi_documentos, public.sgi_arquivos
  to authenticated;

-- Cadastro de documento externo: o arquivo já foi salvo em disco pelo backend
-- local (dev-server.cjs) antes desta chamada; aqui só gravamos os metadados,
-- em duas etapas (documento -> arquivo com documento_id -> liga arquivo ao
-- documento) na mesma transação.
create or replace function public.sgi_cadastrar_documento_externo(
  p_codigo text,
  p_titulo text,
  p_tipo_documento_id bigint,
  p_area_responsavel_id bigint,
  p_processo_setor text,
  p_palavras_chave text,
  p_observacoes text,
  p_arquivo_nome_original text,
  p_arquivo_caminho_relativo text,
  p_arquivo_mime_type text,
  p_arquivo_tamanho_bytes bigint,
  p_arquivo_hash_sha256 text
) returns bigint
language plpgsql security definer
set search_path = pg_catalog, public as $$
declare
  v_documento_id bigint;
  v_arquivo_id bigint;
begin
  if not public.usuario_tem_permissao_sistema('sgi.criar') then
    raise exception 'Usuário sem permissão para cadastrar documentos.';
  end if;
  if trim(coalesce(p_codigo, '')) = '' then raise exception 'Informe o código do documento.'; end if;
  if trim(coalesce(p_titulo, '')) = '' then raise exception 'Informe o título do documento.'; end if;
  if trim(coalesce(p_arquivo_caminho_relativo, '')) = '' then raise exception 'Nenhum arquivo foi enviado.'; end if;

  insert into public.sgi_documentos (
    codigo, titulo, tipo_documento_id, origem, status, vigente,
    area_responsavel_id, processo_setor, palavras_chave, observacoes, elaborado_por
  ) values (
    trim(p_codigo), trim(p_titulo), p_tipo_documento_id, 'EXTERNO', 'VIGENTE', true,
    p_area_responsavel_id, p_processo_setor, p_palavras_chave, p_observacoes, auth.uid()
  ) returning id into v_documento_id;

  insert into public.sgi_arquivos (
    documento_id, tipo, nome_original, caminho_relativo, mime_type, tamanho_bytes, hash_sha256, enviado_por
  ) values (
    v_documento_id, 'OFICIAL', p_arquivo_nome_original, p_arquivo_caminho_relativo,
    p_arquivo_mime_type, p_arquivo_tamanho_bytes, p_arquivo_hash_sha256, auth.uid()
  ) returning id into v_arquivo_id;

  update public.sgi_documentos set arquivo_oficial_id = v_arquivo_id where id = v_documento_id;

  return v_documento_id;
end;
$$;

revoke all on function public.sgi_cadastrar_documento_externo(
  text, text, bigint, bigint, text, text, text, text, text, text, bigint, text
) from public, anon;
grant execute on function public.sgi_cadastrar_documento_externo(
  text, text, bigint, bigint, text, text, text, text, text, text, bigint, text
) to authenticated;

-- Permissões do módulo — código livre, sem precisar de tabela nova
-- (`permissoes.modulo` já é texto livre; usuario_tem_permissao_sistema já é
-- genérica e cobre qualquer código novo automaticamente).
insert into public.permissoes (codigo, nome, descricao, modulo, ativo)
select dados.codigo, dados.nome, dados.descricao, 'SGI', true
from (
  values
    ('sgi.visualizar', 'Visualizar documentos do SGI', 'Pesquisa, abre e consulta documentos controlados.'),
    ('sgi.criar', 'Cadastrar documentos no SGI', 'Cadastra novos documentos (externos e internos).'),
    ('sgi.editar_rascunho', 'Editar rascunho de documento do SGI', 'Edita documento interno ainda em elaboração.'),
    ('sgi.enviar_aprovacao', 'Enviar documento do SGI para aprovação', 'Envia um documento pronto para o fluxo de aprovação.'),
    ('sgi.aprovar', 'Aprovar documentos do SGI', 'Participa do fluxo de aprovação de documentos controlados.'),
    ('sgi.gerenciar_tipos', 'Gerenciar tipos de documento do SGI', 'Administra tipos de documento e templates.')
) as dados(codigo, nome, descricao)
where not exists (select 1 from public.permissoes p where p.codigo = dados.codigo);

insert into public.perfil_permissoes (perfil_id, permissao_id)
select perfil.id, permissao.id
from public.perfis perfil
cross join public.permissoes permissao
where (
    upper(perfil.codigo) in ('ADMIN', 'ADMINISTRADOR', 'GERENTE_QUALIDADE')
    or upper(perfil.nome) = 'ADMINISTRADOR'
  )
  and permissao.codigo like 'sgi.%'
  and not exists (
    select 1 from public.perfil_permissoes perfil_permissao
    where perfil_permissao.perfil_id = perfil.id
      and perfil_permissao.permissao_id = permissao.id
  );

commit;
