begin;

-- ---------------------------------------------------------------------------
-- Módulo SGI — incremento 2: revisão, aprovação (por área) e histórico de
-- ações. Só adiciona — não altera nenhuma tabela/função do incremento 1
-- (sgi_documentos, sgi_arquivos, sgi_tipos_documento, sgi_areas).
-- Padrão espelhado de fichas_tecnicas/aprovacoes_ficha, simplificado porque o
-- SGI aprova por uma única área (não duas etapas Engenharia→Produção).
-- ---------------------------------------------------------------------------

create table if not exists public.sgi_aprovacoes (
  id bigint generated by default as identity primary key,
  documento_id bigint not null references public.sgi_documentos(id) on delete cascade,
  area_id bigint references public.sgi_areas(id),
  aprovador_id uuid references public.usuarios(id),
  solicitante_id uuid references public.usuarios(id),
  status text not null default 'PENDENTE' check (status in ('PENDENTE', 'APROVADO', 'REJEITADO')),
  comentario text,
  solicitado_em timestamptz not null default now(),
  decidido_em timestamptz
);

create index if not exists sgi_aprovacoes_documento_idx on public.sgi_aprovacoes (documento_id);
create index if not exists sgi_aprovacoes_pendentes_idx on public.sgi_aprovacoes (status) where status = 'PENDENTE';

-- Log append-only das ações do documento — diferente de historico_fichas
-- (que é manual, só preenchido na conferência de import), este é alimentado
-- automaticamente por cada RPC abaixo, pra rastreabilidade completa.
create table if not exists public.sgi_historico (
  id bigint generated by default as identity primary key,
  documento_id bigint not null references public.sgi_documentos(id) on delete cascade,
  usuario_id uuid references public.usuarios(id),
  acao text not null,
  descricao text,
  status_anterior text,
  status_novo text,
  criado_em timestamptz not null default now()
);

create index if not exists sgi_historico_documento_idx on public.sgi_historico (documento_id, criado_em);

alter table public.sgi_aprovacoes enable row level security;
alter table public.sgi_historico enable row level security;

create policy sgi_aprovacoes_select on public.sgi_aprovacoes for select to authenticated
  using (public.usuario_tem_permissao_sistema('sgi.visualizar'));

create policy sgi_historico_select on public.sgi_historico for select to authenticated
  using (public.usuario_tem_permissao_sistema('sgi.visualizar'));

grant select on public.sgi_aprovacoes, public.sgi_historico to authenticated;

-- ---------------------------------------------------------------------------
-- Criar nova revisão: só a partir de um documento VIGENTE. Copia os
-- metadados, exige o arquivo novo já anexado (documento externo só é
-- revisado quando chega o PDF atualizado) e referencia a origem via
-- documento_anterior_id. Não mexe na revisão de origem.
-- ---------------------------------------------------------------------------
create or replace function public.sgi_criar_nova_revisao(
  p_documento_id bigint,
  p_motivo text,
  p_arquivo_nome_original text,
  p_arquivo_caminho_relativo text,
  p_arquivo_mime_type text,
  p_arquivo_tamanho_bytes bigint,
  p_arquivo_hash_sha256 text
) returns bigint
language plpgsql security definer
set search_path = pg_catalog, public as $$
declare
  v_origem public.sgi_documentos%rowtype;
  v_documento_id bigint;
  v_arquivo_id bigint;
begin
  if not public.usuario_tem_permissao_sistema('sgi.criar') then
    raise exception 'Usuário sem permissão para criar revisão.';
  end if;

  select * into v_origem from public.sgi_documentos where id = p_documento_id;
  if not found then
    raise exception 'Documento não encontrado.';
  end if;
  if v_origem.status <> 'VIGENTE' then
    raise exception 'Só é possível criar uma nova revisão a partir do documento vigente.';
  end if;
  if trim(coalesce(p_arquivo_caminho_relativo, '')) = '' then
    raise exception 'Anexe o arquivo da nova revisão.';
  end if;

  insert into public.sgi_documentos (
    codigo, titulo, tipo_documento_id, origem, numero_revisao, status, vigente,
    area_responsavel_id, processo_setor, palavras_chave, observacoes,
    documento_anterior_id, elaborado_por
  ) values (
    v_origem.codigo, v_origem.titulo, v_origem.tipo_documento_id, v_origem.origem,
    v_origem.numero_revisao + 1, 'EM_ELABORACAO', false,
    v_origem.area_responsavel_id, v_origem.processo_setor, v_origem.palavras_chave, p_motivo,
    v_origem.id, auth.uid()
  ) returning id into v_documento_id;

  insert into public.sgi_arquivos (
    documento_id, tipo, nome_original, caminho_relativo, mime_type, tamanho_bytes, hash_sha256, enviado_por
  ) values (
    v_documento_id, 'OFICIAL', p_arquivo_nome_original, p_arquivo_caminho_relativo,
    p_arquivo_mime_type, p_arquivo_tamanho_bytes, p_arquivo_hash_sha256, auth.uid()
  ) returning id into v_arquivo_id;

  update public.sgi_documentos set arquivo_oficial_id = v_arquivo_id where id = v_documento_id;

  insert into public.sgi_historico (documento_id, usuario_id, acao, descricao, status_anterior, status_novo)
  values (v_documento_id, auth.uid(), 'NOVA_REVISAO', p_motivo, null, 'EM_ELABORACAO');

  return v_documento_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Enviar para aprovação: só o próprio elaborador, só em EM_ELABORACAO.
-- ---------------------------------------------------------------------------
create or replace function public.sgi_enviar_para_aprovacao(
  p_documento_id bigint
) returns void
language plpgsql security definer
set search_path = pg_catalog, public as $$
declare
  v_documento public.sgi_documentos%rowtype;
  v_area_id bigint;
begin
  if not public.usuario_tem_permissao_sistema('sgi.enviar_aprovacao') then
    raise exception 'Usuário sem permissão para enviar documentos para aprovação.';
  end if;

  select * into v_documento from public.sgi_documentos where id = p_documento_id for update;
  if not found then
    raise exception 'Documento não encontrado.';
  end if;
  if v_documento.elaborado_por is distinct from auth.uid() then
    raise exception 'Só quem elaborou o documento pode enviá-lo para aprovação.';
  end if;
  if v_documento.status <> 'EM_ELABORACAO' then
    raise exception 'Este documento não está em elaboração.';
  end if;

  v_area_id := v_documento.area_responsavel_id;
  if v_area_id is null then
    select area_aprovadora_padrao_id into v_area_id
    from public.sgi_tipos_documento where id = v_documento.tipo_documento_id;
  end if;

  update public.sgi_documentos set status = 'AGUARDANDO_APROVACAO' where id = p_documento_id;

  insert into public.sgi_aprovacoes (documento_id, area_id, solicitante_id, status)
  values (p_documento_id, v_area_id, auth.uid(), 'PENDENTE');

  insert into public.sgi_historico (documento_id, usuario_id, acao, status_anterior, status_novo)
  values (p_documento_id, auth.uid(), 'ENVIADO_APROVACAO', 'EM_ELABORACAO', 'AGUARDANDO_APROVACAO');
end;
$$;

-- ---------------------------------------------------------------------------
-- Decidir aprovação: aprovar torna a nova revisão vigente e obsoleta a
-- anterior (o predecessor direto, via documento_anterior_id — não precisa
-- rebaixar "todas as vigentes da família" como em fichas técnicas, porque
-- aqui já sabemos exatamente qual é o predecessor). Rejeitar devolve pro
-- elaborador ajustar.
-- ---------------------------------------------------------------------------
create or replace function public.sgi_decidir_aprovacao(
  p_aprovacao_id bigint,
  p_resultado text,
  p_comentario text
) returns void
language plpgsql security definer
set search_path = pg_catalog, public as $$
declare
  v_aprovacao public.sgi_aprovacoes%rowtype;
  v_documento public.sgi_documentos%rowtype;
  v_status_anterior text;
begin
  if not public.usuario_tem_permissao_sistema('sgi.aprovar') then
    raise exception 'Usuário sem permissão para aprovar documentos.';
  end if;
  if p_resultado not in ('APROVADO', 'REJEITADO') then
    raise exception 'Resultado inválido.';
  end if;

  select * into v_aprovacao from public.sgi_aprovacoes where id = p_aprovacao_id for update;
  if not found then
    raise exception 'Solicitação de aprovação não encontrada.';
  end if;
  if v_aprovacao.status <> 'PENDENTE' then
    raise exception 'Esta solicitação já foi decidida.';
  end if;

  select * into v_documento from public.sgi_documentos where id = v_aprovacao.documento_id for update;
  if v_documento.status <> 'AGUARDANDO_APROVACAO' then
    raise exception 'Este documento não está aguardando aprovação.';
  end if;
  v_status_anterior := v_documento.status;

  update public.sgi_aprovacoes
  set status = p_resultado, aprovador_id = auth.uid(), comentario = p_comentario, decidido_em = now()
  where id = p_aprovacao_id;

  if p_resultado = 'APROVADO' then
    update public.sgi_documentos set status = 'VIGENTE', vigente = true where id = v_documento.id;
    if v_documento.documento_anterior_id is not null then
      update public.sgi_documentos
      set status = 'OBSOLETO', vigente = false
      where id = v_documento.documento_anterior_id;
    end if;
  else
    update public.sgi_documentos set status = 'EM_ELABORACAO' where id = v_documento.id;
  end if;

  insert into public.sgi_historico (documento_id, usuario_id, acao, descricao, status_anterior, status_novo)
  values (
    v_documento.id, auth.uid(), p_resultado, p_comentario, v_status_anterior,
    case when p_resultado = 'APROVADO' then 'VIGENTE' else 'EM_ELABORACAO' end
  );
end;
$$;

revoke all on function public.sgi_criar_nova_revisao(bigint, text, text, text, text, bigint, text) from public, anon;
grant execute on function public.sgi_criar_nova_revisao(bigint, text, text, text, text, bigint, text) to authenticated;

revoke all on function public.sgi_enviar_para_aprovacao(bigint) from public, anon;
grant execute on function public.sgi_enviar_para_aprovacao(bigint) to authenticated;

revoke all on function public.sgi_decidir_aprovacao(bigint, text, text) from public, anon;
grant execute on function public.sgi_decidir_aprovacao(bigint, text, text) to authenticated;

commit;
