begin;
create table if not exists public.mapeamentos_ficha_checklist(id bigint generated by default as identity primary key,chave_especificacao text not null unique,parametro_minimo_codigo text,parametro_alvo_codigo text,parametro_maximo_codigo text,ativo boolean not null default true);
insert into public.mapeamentos_ficha_checklist(chave_especificacao,parametro_minimo_codigo,parametro_alvo_codigo,parametro_maximo_codigo)
values('COMPRESSIBILIDADE','MOLD_063_COMPRESSIBILIDADE_MIN',null,'MOLD_064_COMPRESSIBILIDADE_MAX')
on conflict(chave_especificacao) do update set parametro_minimo_codigo=excluded.parametro_minimo_codigo,parametro_alvo_codigo=excluded.parametro_alvo_codigo,parametro_maximo_codigo=excluded.parametro_maximo_codigo,ativo=true;
alter table public.mapeamentos_ficha_checklist enable row level security;
drop policy if exists mapeamentos_ficha_checklist_select on public.mapeamentos_ficha_checklist;
create policy mapeamentos_ficha_checklist_select on public.mapeamentos_ficha_checklist for select to authenticated using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
grant select on public.mapeamentos_ficha_checklist to authenticated;

create or replace function public.resolver_limite_ficha_checklist(p_chave_especificacao text,p_produto_id bigint)
returns table(ficha_id bigint,numero_revisao integer,valor_minimo numeric,valor_alvo numeric,valor_maximo numeric,unidade text)
language sql stable security definer set search_path=pg_catalog,public as $$
 select ficha.id,ficha.numero_revisao,
  coalesce(vmin.valor_numerico,vmin.valor_minimo,vmin.valor_alvo,vmin.valor_maximo),
  coalesce(valvo.valor_numerico,valvo.valor_alvo,valvo.valor_minimo,valvo.valor_maximo),
  coalesce(vmax.valor_numerico,vmax.valor_maximo,vmax.valor_alvo,vmax.valor_minimo),
  coalesce(pmin.unidade,palvo.unidade,pmax.unidade)
 from public.mapeamentos_ficha_checklist mapa
 join public.fichas_tecnicas ficha on ficha.produto_id=p_produto_id and ficha.vigente=true and ficha.status in('APROVADA','IMPORTADA')
 left join public.parametros pmin on pmin.codigo=mapa.parametro_minimo_codigo
 left join public.valores_parametros vmin on vmin.ficha_tecnica_id=ficha.id and vmin.parametro_id=pmin.id and not coalesce(vmin.nao_aplicavel,false)
 left join public.parametros palvo on palvo.codigo=mapa.parametro_alvo_codigo
 left join public.valores_parametros valvo on valvo.ficha_tecnica_id=ficha.id and valvo.parametro_id=palvo.id and not coalesce(valvo.nao_aplicavel,false)
 left join public.parametros pmax on pmax.codigo=mapa.parametro_maximo_codigo
 left join public.valores_parametros vmax on vmax.ficha_tecnica_id=ficha.id and vmax.parametro_id=pmax.id and not coalesce(vmax.nao_aplicavel,false)
 where mapa.ativo and mapa.chave_especificacao=upper(trim(p_chave_especificacao)) and (vmin.id is not null or valvo.id is not null or vmax.id is not null)
 order by ficha.numero_revisao desc,ficha.id desc limit 1
$$;

create or replace function public.registrar_fonte_medicao_checklist()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare item public.itens_checklist; limite record; doc_codigo text;
begin
 select * into item from public.itens_checklist where id=new.item_id;
 if new.produto_id is not null and item.chave_especificacao is not null then select * into limite from public.resolver_limite_ficha_checklist(item.chave_especificacao,new.produto_id); end if;
 if limite.ficha_id is not null then
  new.limite_minimo:=limite.valor_minimo;new.valor_alvo:=limite.valor_alvo;new.limite_maximo:=limite.valor_maximo;
  new.conforme:=(limite.valor_minimo is null or new.valor>=limite.valor_minimo) and (limite.valor_maximo is null or new.valor<=limite.valor_maximo);
  new.fonte_limite_tipo:='FICHA_TECNICA';new.fonte_limite_id:=limite.ficha_id;
  select produto.codigo into doc_codigo from public.produtos produto where produto.id=new.produto_id;
  new.fonte_limite_codigo:='FT-'||coalesce(doc_codigo,new.produto_id::text);new.fonte_limite_revisao:=limite.numero_revisao::text;new.fonte_limite_pagina:=null;
 else
  if item.fonte_limite_tipo='INSTRUCAO_TRABALHO' then select instrucao.codigo into doc_codigo from public.especificacoes_instrucao_trabalho spec join public.revisoes_instrucao_trabalho revisao on revisao.id=spec.revisao_id join public.instrucoes_trabalho instrucao on instrucao.id=revisao.instrucao_id where spec.id=item.fonte_limite_id; end if;
  new.fonte_limite_tipo:=item.fonte_limite_tipo;new.fonte_limite_id:=item.fonte_limite_id;new.fonte_limite_codigo:=doc_codigo;new.fonte_limite_revisao:=item.fonte_limite_revisao;new.fonte_limite_pagina:=item.fonte_limite_pagina;
 end if;return new;
end $$;
drop trigger if exists medicoes_checklist_fonte_trigger on public.medicoes_checklist;
create trigger medicoes_checklist_fonte_trigger before insert on public.medicoes_checklist for each row execute function public.registrar_fonte_medicao_checklist();

do $$ declare medicao record;limite record;begin
 for medicao in select m.id,m.valor,m.produto_id,item.chave_especificacao from public.medicoes_checklist m join public.itens_checklist item on item.id=m.item_id where m.produto_id is not null and item.chave_especificacao is not null and m.limite_minimo is null and m.limite_maximo is null loop
  select * into limite from public.resolver_limite_ficha_checklist(medicao.chave_especificacao,medicao.produto_id);
  if limite.ficha_id is not null then update public.medicoes_checklist set limite_minimo=limite.valor_minimo,valor_alvo=limite.valor_alvo,limite_maximo=limite.valor_maximo,conforme=(limite.valor_minimo is null or medicao.valor>=limite.valor_minimo) and (limite.valor_maximo is null or medicao.valor<=limite.valor_maximo),fonte_limite_tipo='FICHA_TECNICA',fonte_limite_id=limite.ficha_id,fonte_limite_revisao=limite.numero_revisao::text where id=medicao.id;end if;
 end loop;
end $$;
grant execute on function public.resolver_limite_ficha_checklist(text,bigint) to authenticated;
commit;
