begin;

-- ==========================================================================
-- Catálogo de postos de linha e equipamentos avulsos do Acabamento
-- ==========================================================================
-- POSTO_LINHA: pertence a uma das duas linhas: quando um posto para, o resto da
-- linha continua operando — a parada só reduz a capacidade daquele posto, não
-- da linha inteira (ver ajuste em calcularDisponibilidade, turnos.js).
-- EQUIPAMENTO_AVULSO: não pertence a nenhuma linha e não entra na conta de
-- disponibilidade da linha; tem uma taxa de utilização própria e independente.
create table if not exists public.postos_equipamentos_acabamento (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  tipo text not null check (tipo in ('POSTO_LINHA','EQUIPAMENTO_AVULSO')),
  linha_maquina_id bigint references public.linhas_maquinas_producao(id),
  ordem integer not null default 0,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  check (
    (tipo = 'POSTO_LINHA' and linha_maquina_id is not null) or
    (tipo = 'EQUIPAMENTO_AVULSO' and linha_maquina_id is null)
  )
);

insert into public.postos_equipamentos_acabamento(codigo,nome,tipo,linha_maquina_id,ordem)
select 'POSTO_'||lpad(posto.numero::text,2,'0'), 'Posto '||lpad(posto.numero::text,2,'0'),
  'POSTO_LINHA', linha.id, posto.numero
from generate_series(1,7) as posto(numero)
cross join (select id from public.linhas_maquinas_producao where codigo='ACABAMENTO_L1') linha
on conflict(codigo) do nothing;

insert into public.postos_equipamentos_acabamento(codigo,nome,tipo,linha_maquina_id,ordem)
select 'POSTO_'||lpad(posto.numero::text,2,'0'), 'Posto '||lpad(posto.numero::text,2,'0'),
  'POSTO_LINHA', linha.id, posto.numero
from generate_series(8,18) as posto(numero)
cross join (select id from public.linhas_maquinas_producao where codigo='ACABAMENTO_L2') linha
on conflict(codigo) do nothing;

insert into public.postos_equipamentos_acabamento(codigo,nome,tipo,ordem)
values
  ('JATO_1','Jato 1','EQUIPAMENTO_AVULSO',101),
  ('JATO_2','Jato 2','EQUIPAMENTO_AVULSO',102),
  ('JATO_GANCHEIRA','Jato Gancheira','EQUIPAMENTO_AVULSO',103),
  ('CORREIA_3','Correia 3','EQUIPAMENTO_AVULSO',104),
  ('CORREIA_ACABAMENTO','Correia Acabamento','EQUIPAMENTO_AVULSO',105),
  ('VS_AUTOMATICA','VS Automática','EQUIPAMENTO_AVULSO',106)
on conflict(codigo) do nothing;

alter table public.postos_equipamentos_acabamento enable row level security;
drop policy if exists postos_equipamentos_select_catalogo on public.postos_equipamentos_acabamento;
create policy postos_equipamentos_select_catalogo on public.postos_equipamentos_acabamento
for select to authenticated using (auth.uid() is not null);
grant select on public.postos_equipamentos_acabamento to authenticated;
grant usage,select on sequence public.postos_equipamentos_acabamento_id_seq to authenticated;

-- ==========================================================================
-- Coluna nova em paradas_producao_acabamento
-- ==========================================================================
-- Nullable no banco (o módulo pode já ter paradas de teste sem esse dado);
-- exigido de fato dentro das RPCs de fechar/editar turno, abaixo.
alter table public.paradas_producao_acabamento
  add column if not exists posto_equipamento_id bigint references public.postos_equipamentos_acabamento(id);

create index if not exists paradas_acabamento_posto_idx
  on public.paradas_producao_acabamento(posto_equipamento_id);

-- ==========================================================================
-- RPCs: fechar_turno_producao_acabamento e editar_turno_producao_acabamento
-- passam a exigir e gravar posto_id em cada parada.
-- ==========================================================================
create or replace function public.fechar_turno_producao_acabamento(
  p_data_operacional date,
  p_turno text,
  p_linha_maquina_id bigint,
  p_operadores_presentes integer,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_acabamento%rowtype;
  v_area_id bigint;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_acabamento('producao_acabamento.lancar') then
    raise exception 'Usuário sem permissão para fechar o turno.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos uma linha de produção.'; end if;
  if p_operadores_presentes is null or p_operadores_presentes<0 then raise exception 'Informe a quantidade de operadores presentes.'; end if;

  select id into v_area_id from public.areas_checklist where codigo='ACABAMENTO';

  insert into public.turnos_producao_acabamento(data_operacional,turno,linha_maquina_id,status,operadores_planejados,criado_por)
  values(p_data_operacional,p_turno,p_linha_maquina_id,'ABERTO',
    public.meta_vigente(v_area_id,p_linha_maquina_id,p_turno,'OPERADORES_PLANEJADOS',p_data_operacional),
    auth.uid())
  on conflict(data_operacional,turno,linha_maquina_id) do nothing;

  select * into v_turno from public.turnos_producao_acabamento
  where data_operacional=p_data_operacional and turno=p_turno and linha_maquina_id=p_linha_maquina_id for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if p_versao is not null and p_versao<>v_turno.versao then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_acabamento(turno_producao_id,data_operacional,turno,produto_id,quantidade_liberada,quantidade_rejeitada,quantidade_retrabalhada,quantidade_refugada,criado_por)
  select v_turno.id,p_data_operacional,p_turno,item.produto_id,item.quantidade_liberada,item.quantidade_rejeitada,item.quantidade_retrabalhada,item.quantidade_refugada,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(produto_id bigint,quantidade_liberada integer,quantidade_rejeitada integer,quantidade_retrabalhada integer,quantidade_refugada integer)
  join public.produtos produto on produto.id=item.produto_id
  where coalesce(item.quantidade_liberada,0)>=0 and coalesce(item.quantidade_rejeitada,0)>=0
    and coalesce(item.quantidade_retrabalhada,0)>=0 and coalesce(item.quantidade_refugada,0)>=0;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais linhas de produção são inválidas ou possuem produto inexistente.'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_acabamento(turno_producao_id,data_operacional,turno,setor_origem_id,categoria_id,posto_equipamento_id,inicio,fim,duracao_minutos,observacao,criado_por)
  select v_turno.id,p_data_operacional,p_turno,item.setor_id,item.categoria_id,item.posto_id,item.inicio,item.fim,round(extract(epoch from(item.fim-item.inicio))/60)::integer,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,posto_id bigint,observacao text)
  join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  join public.setores_responsaveis_parada setor on setor.id=item.setor_id
  join public.postos_equipamentos_acabamento posto on posto.id=item.posto_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais paradas possuem dados, horários ou posto/equipamento inválidos.'; end if;

  update public.turnos_producao_acabamento set
    status='FECHADO',fechado_por=auth.uid(),fechado_em=now(),
    operadores_presentes=p_operadores_presentes,
    rascunho_producoes='[]'::jsonb,rascunho_paradas='[]'::jsonb,
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id;
  return v_turno.id;
end;
$$;

create or replace function public.editar_turno_producao_acabamento(
  p_turno_id bigint,
  p_operadores_presentes integer,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_acabamento%rowtype;
  v_anteriores jsonb;
  v_novos jsonb;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_acabamento('producao_acabamento.editar') then
    raise exception 'Usuário sem permissão para editar turnos fechados.';
  end if;
  select * into v_turno from public.turnos_producao_acabamento where id=p_turno_id and status='FECHADO' for update;
  if not found then raise exception 'Turno fechado não encontrado.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos uma linha de produção.'; end if;

  select jsonb_build_object(
    'operadores_presentes',v_turno.operadores_presentes,
    'productions',coalesce((select jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by produto_id) from public.registros_producao_acabamento registro where turno_producao_id=p_turno_id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(parada)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by inicio) from public.paradas_producao_acabamento parada where turno_producao_id=p_turno_id),'[]'::jsonb)
  ) into v_anteriores;

  delete from public.paradas_producao_acabamento where turno_producao_id=p_turno_id;
  delete from public.registros_producao_acabamento where turno_producao_id=p_turno_id;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_acabamento(turno_producao_id,data_operacional,turno,produto_id,quantidade_liberada,quantidade_rejeitada,quantidade_retrabalhada,quantidade_refugada,criado_por)
  select v_turno.id,v_turno.data_operacional,v_turno.turno,item.produto_id,item.quantidade_liberada,item.quantidade_rejeitada,item.quantidade_retrabalhada,item.quantidade_refugada,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(produto_id bigint,quantidade_liberada integer,quantidade_rejeitada integer,quantidade_retrabalhada integer,quantidade_refugada integer)
  join public.produtos produto on produto.id=item.produto_id
  where coalesce(item.quantidade_liberada,0)>=0 and coalesce(item.quantidade_rejeitada,0)>=0
    and coalesce(item.quantidade_retrabalhada,0)>=0 and coalesce(item.quantidade_refugada,0)>=0;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais linhas de produção são inválidas ou possuem produto inexistente.'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_acabamento(turno_producao_id,data_operacional,turno,setor_origem_id,categoria_id,posto_equipamento_id,inicio,fim,duracao_minutos,observacao,criado_por)
  select v_turno.id,v_turno.data_operacional,v_turno.turno,item.setor_id,item.categoria_id,item.posto_id,item.inicio,item.fim,round(extract(epoch from(item.fim-item.inicio))/60)::integer,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,posto_id bigint,observacao text)
  join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  join public.setores_responsaveis_parada setor on setor.id=item.setor_id
  join public.postos_equipamentos_acabamento posto on posto.id=item.posto_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais paradas possuem dados, horários ou posto/equipamento inválidos.'; end if;

  update public.turnos_producao_acabamento set
    operadores_presentes=coalesce(p_operadores_presentes,operadores_presentes),
    atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id;

  select jsonb_build_object(
    'operadores_presentes',coalesce(p_operadores_presentes,v_turno.operadores_presentes),
    'productions',coalesce((select jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by produto_id) from public.registros_producao_acabamento registro where turno_producao_id=p_turno_id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(parada)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by inicio) from public.paradas_producao_acabamento parada where turno_producao_id=p_turno_id),'[]'::jsonb)
  ) into v_novos;

  if v_anteriores = v_novos then
    raise exception 'Nenhuma alteração foi identificada.';
  end if;

  insert into public.historico_edicoes_turno_acabamento(
    turno_producao_id,descricao,dados_anteriores,dados_novos,alterado_por
  ) values (
    p_turno_id,'os apontamentos do turno',v_anteriores,v_novos,auth.uid()
  );
  return p_turno_id;
end;
$$;

notify pgrst,'reload schema';

commit;
