begin;

create table if not exists public.reclamacoes_cliente (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  titulo text not null,
  cliente_nome text not null,
  produto_id bigint references public.produtos(id),
  descricao text not null,
  status text not null default 'ABERTA'
    check (status in ('ABERTA','EM_ANALISE','EM_ACAO','CONCLUIDA','CANCELADA')),
  prioridade text not null default 'MEDIA'
    check (prioridade in ('BAIXA','MEDIA','ALTA','CRITICA')),
  data_ocorrencia date,
  criado_por uuid not null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.reclamacoes_anexos (
  id bigint generated by default as identity primary key,
  reclamacao_id bigint not null references public.reclamacoes_cliente(id) on delete cascade,
  nome_original text not null,
  storage_path text not null unique,
  mime_type text not null check (mime_type like 'image/%' or mime_type like 'video/%'),
  tamanho_bytes bigint not null check (tamanho_bytes > 0 and tamanho_bytes <= 52428800),
  criado_por uuid not null default auth.uid(),
  criado_em timestamptz not null default now()
);

create table if not exists public.reclamacoes_comentarios (
  id bigint generated by default as identity primary key,
  reclamacao_id bigint not null references public.reclamacoes_cliente(id) on delete cascade,
  comentario text not null check (length(trim(comentario)) between 1 and 4000),
  criado_por uuid not null default auth.uid(),
  criado_em timestamptz not null default now()
);

create table if not exists public.reclamacoes_acoes (
  id bigint generated by default as identity primary key,
  reclamacao_id bigint not null references public.reclamacoes_cliente(id) on delete cascade,
  titulo text not null,
  descricao text,
  tipo text not null default 'ACAO'
    check (tipo in ('MELHORIA','CORRECAO','CONTENCAO','ACAO')),
  responsavel text,
  prazo date,
  status text not null default 'PENDENTE'
    check (status in ('PENDENTE','EM_ANDAMENTO','CONCLUIDA','CANCELADA')),
  criado_por uuid not null default auth.uid(),
  criado_em timestamptz not null default now(),
  concluido_em timestamptz
);

create index if not exists reclamacoes_status_idx
  on public.reclamacoes_cliente(status, criado_em desc);
create index if not exists reclamacoes_anexos_reclamacao_idx
  on public.reclamacoes_anexos(reclamacao_id);
create index if not exists reclamacoes_comentarios_reclamacao_idx
  on public.reclamacoes_comentarios(reclamacao_id, criado_em);
create index if not exists reclamacoes_acoes_reclamacao_idx
  on public.reclamacoes_acoes(reclamacao_id, status);

insert into public.permissoes (codigo, nome, descricao, modulo, ativo)
select codigo, nome, descricao, 'QUALIDADE', true
from (values
  ('reclamacao.visualizar','Visualizar reclamações','Consulta reclamações, evidências, comentários e ações.'),
  ('reclamacao.criar','Criar reclamações','Registra reclamações e envia evidências.'),
  ('reclamacao.comentar','Comentar reclamações','Participa da discussão da reclamação.'),
  ('reclamacao.gerenciar','Gerenciar reclamações','Atualiza status e administra o plano de ações.')
) as p(codigo,nome,descricao)
where not exists (select 1 from public.permissoes x where x.codigo=p.codigo);

insert into public.perfil_permissoes (perfil_id, permissao_id)
select pf.id, pe.id from public.perfis pf cross join public.permissoes pe
where (upper(pf.codigo) in ('ADMIN','ADMINISTRADOR') or upper(pf.nome)='ADMINISTRADOR')
  and pe.codigo like 'reclamacao.%'
  and not exists (
    select 1 from public.perfil_permissoes pp
    where pp.perfil_id=pf.id and pp.permissao_id=pe.id
  );

create or replace function public.usuario_tem_permissao_reclamacao(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select up.permitido from public.usuario_permissoes up
     join public.permissoes p on p.id=up.permissao_id
     where up.usuario_id=auth.uid() and p.codigo=p_codigo limit 1),
    exists (
      select 1 from public.usuario_perfis uf
      join public.perfil_permissoes pp on pp.perfil_id=uf.perfil_id
      join public.permissoes p on p.id=pp.permissao_id
      where uf.usuario_id=auth.uid() and p.codigo=p_codigo
    )
  );
$$;
grant execute on function public.usuario_tem_permissao_reclamacao(text) to authenticated;

alter table public.reclamacoes_cliente enable row level security;
alter table public.reclamacoes_anexos enable row level security;
alter table public.reclamacoes_comentarios enable row level security;
alter table public.reclamacoes_acoes enable row level security;

create policy reclamacoes_select on public.reclamacoes_cliente for select to authenticated
  using (public.usuario_tem_permissao_reclamacao('reclamacao.visualizar'));
create policy reclamacoes_insert on public.reclamacoes_cliente for insert to authenticated
  with check (criado_por=auth.uid() and public.usuario_tem_permissao_reclamacao('reclamacao.criar'));
create policy reclamacoes_update on public.reclamacoes_cliente for update to authenticated
  using (public.usuario_tem_permissao_reclamacao('reclamacao.gerenciar'))
  with check (public.usuario_tem_permissao_reclamacao('reclamacao.gerenciar'));

create policy reclamacoes_anexos_select on public.reclamacoes_anexos for select to authenticated
  using (public.usuario_tem_permissao_reclamacao('reclamacao.visualizar'));
create policy reclamacoes_anexos_insert on public.reclamacoes_anexos for insert to authenticated
  with check (criado_por=auth.uid() and public.usuario_tem_permissao_reclamacao('reclamacao.criar'));
create policy reclamacoes_comentarios_select on public.reclamacoes_comentarios for select to authenticated
  using (public.usuario_tem_permissao_reclamacao('reclamacao.visualizar'));
create policy reclamacoes_comentarios_insert on public.reclamacoes_comentarios for insert to authenticated
  with check (criado_por=auth.uid() and public.usuario_tem_permissao_reclamacao('reclamacao.comentar'));
create policy reclamacoes_acoes_select on public.reclamacoes_acoes for select to authenticated
  using (public.usuario_tem_permissao_reclamacao('reclamacao.visualizar'));
create policy reclamacoes_acoes_all on public.reclamacoes_acoes for all to authenticated
  using (public.usuario_tem_permissao_reclamacao('reclamacao.gerenciar'))
  with check (public.usuario_tem_permissao_reclamacao('reclamacao.gerenciar'));

grant select,insert,update on public.reclamacoes_cliente to authenticated;
grant select,insert on public.reclamacoes_anexos,public.reclamacoes_comentarios to authenticated;
grant select,insert,update on public.reclamacoes_acoes to authenticated;
grant usage,select on sequence public.reclamacoes_cliente_id_seq to authenticated;
grant usage,select on sequence public.reclamacoes_anexos_id_seq to authenticated;
grant usage,select on sequence public.reclamacoes_comentarios_id_seq to authenticated;
grant usage,select on sequence public.reclamacoes_acoes_id_seq to authenticated;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('reclamacoes-cliente','reclamacoes-cliente',false,52428800,
  array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

create policy reclamacoes_storage_select on storage.objects for select to authenticated
  using (bucket_id='reclamacoes-cliente' and public.usuario_tem_permissao_reclamacao('reclamacao.visualizar'));
create policy reclamacoes_storage_insert on storage.objects for insert to authenticated
  with check (bucket_id='reclamacoes-cliente' and public.usuario_tem_permissao_reclamacao('reclamacao.criar'));

commit;
