begin;

create table if not exists public.indicadores_metas (
  codigo text primary key,
  nome text not null,
  unidade text,
  area_id bigint not null references public.areas_checklist(id),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

insert into public.indicadores_metas(codigo,nome,unidade,area_id)
select 'OPERADORES_PLANEJADOS','Operadores planejados por turno','operadores',area.id
from public.areas_checklist area where area.codigo='ACABAMENTO'
union all
select 'HOMEM_HORA_PLANEJADO','Homem-hora planejado por turno','h',area.id
from public.areas_checklist area where area.codigo='ACABAMENTO'
union all
select 'PECAS_LIBERADAS_PLANEJADAS','Peças liberadas planejadas por turno','peças',area.id
from public.areas_checklist area where area.codigo='ACABAMENTO'
on conflict(codigo) do nothing;

alter table public.indicadores_metas enable row level security;
drop policy if exists indicadores_metas_select on public.indicadores_metas;
create policy indicadores_metas_select on public.indicadores_metas
for select to authenticated using(auth.uid() is not null);
grant select on public.indicadores_metas to authenticated;

create table if not exists public.metas_gerenciais (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.areas_checklist(id),
  linha_maquina_id bigint references public.linhas_maquinas_producao(id),
  turno text check (turno in ('MANHA','TARDE','NOITE')),
  indicador_codigo text not null references public.indicadores_metas(codigo),
  valor_planejado numeric not null check (valor_planejado >= 0),
  vigencia_inicio date not null,
  vigencia_fim date,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  check (vigencia_fim is null or vigencia_fim >= vigencia_inicio)
);

create index if not exists metas_gerenciais_busca_idx
  on public.metas_gerenciais(area_id, indicador_codigo, vigencia_inicio desc);

-- Garante no máximo uma vigência "em aberto" (vigencia_fim null) por combinação de
-- área/linha/turno/indicador, para o histórico nunca ficar ambíguo.
create unique index if not exists metas_gerenciais_vigente_uidx
  on public.metas_gerenciais(area_id, coalesce(linha_maquina_id,-1), coalesce(turno,'-'), indicador_codigo)
  where vigencia_fim is null;

alter table public.metas_gerenciais enable row level security;

insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'PLANEJAMENTO',true from (values
  ('metas.visualizar','Visualizar metas gerenciais','Consulta metas de planejamento por setor.'),
  ('metas.gerenciar','Gerenciar metas gerenciais','Cadastra e altera metas de planejamento por setor.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id from public.perfis profile
cross join public.permissoes permission
where (upper(profile.codigo) in ('ADMIN','ADMINISTRADOR','GERENTE_GERAL','GERENTE_PRODUCAO')
  or upper(profile.nome)='ADMINISTRADOR')
and permission.codigo in ('metas.visualizar','metas.gerenciar')
and not exists(select 1 from public.perfil_permissoes relation
  where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

create or replace function public.usuario_tem_permissao_metas(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select user_permission.permitido
     from public.usuario_permissoes user_permission
     join public.permissoes permission on permission.id=user_permission.permissao_id
     where user_permission.usuario_id=auth.uid()
       and permission.codigo=p_codigo limit 1),
    exists(select 1 from public.usuario_perfis user_profile
      join public.perfil_permissoes profile_permission
        on profile_permission.perfil_id=user_profile.perfil_id
      join public.permissoes permission
        on permission.id=profile_permission.permissao_id
      where user_profile.usuario_id=auth.uid() and permission.codigo=p_codigo)
  );
$$;
grant execute on function public.usuario_tem_permissao_metas(text) to authenticated;

drop policy if exists metas_gerenciais_select on public.metas_gerenciais;
create policy metas_gerenciais_select on public.metas_gerenciais for select to authenticated using(
  public.usuario_tem_permissao_metas('metas.visualizar') or public.usuario_tem_permissao_metas('metas.gerenciar')
);
grant select on public.metas_gerenciais to authenticated;
grant usage,select on sequence public.metas_gerenciais_id_seq to authenticated;

create or replace function public.definir_meta_gerencial(
  p_area_id bigint,
  p_linha_maquina_id bigint,
  p_turno text,
  p_indicador_codigo text,
  p_valor numeric,
  p_vigencia_inicio date
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_id bigint;
begin
  if not public.usuario_tem_permissao_metas('metas.gerenciar') then
    raise exception 'Usuário sem permissão para gerenciar metas.';
  end if;
  if p_turno is not null and p_turno not in ('MANHA','TARDE','NOITE') then
    raise exception 'Turno inválido.';
  end if;
  if p_valor < 0 then raise exception 'O valor planejado não pode ser negativo.'; end if;
  if not exists(select 1 from public.indicadores_metas where codigo=p_indicador_codigo and area_id=p_area_id) then
    raise exception 'Indicador inválido para este setor.';
  end if;

  update public.metas_gerenciais set vigencia_fim = p_vigencia_inicio - 1
  where area_id=p_area_id
    and coalesce(linha_maquina_id,-1)=coalesce(p_linha_maquina_id,-1)
    and coalesce(turno,'-')=coalesce(p_turno,'-')
    and indicador_codigo=p_indicador_codigo
    and vigencia_fim is null
    and vigencia_inicio < p_vigencia_inicio;

  insert into public.metas_gerenciais(area_id,linha_maquina_id,turno,indicador_codigo,valor_planejado,vigencia_inicio,criado_por)
  values(p_area_id,p_linha_maquina_id,p_turno,p_indicador_codigo,p_valor,p_vigencia_inicio,auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.definir_meta_gerencial(bigint,bigint,text,text,numeric,date) from public,anon;
grant execute on function public.definir_meta_gerencial(bigint,bigint,text,text,numeric,date) to authenticated;

create or replace function public.meta_vigente(
  p_area_id bigint,
  p_linha_maquina_id bigint,
  p_turno text,
  p_indicador_codigo text,
  p_data date
) returns numeric
language sql stable security definer
set search_path=pg_catalog,public as $$
  select valor_planejado from public.metas_gerenciais
  where area_id=p_area_id
    and indicador_codigo=p_indicador_codigo
    and (linha_maquina_id=p_linha_maquina_id or linha_maquina_id is null)
    and (turno=p_turno or turno is null)
    and vigencia_inicio<=p_data
    and (vigencia_fim is null or vigencia_fim>=p_data)
  order by (linha_maquina_id is not null) desc, (turno is not null) desc, vigencia_inicio desc
  limit 1
$$;
grant execute on function public.meta_vigente(bigint,bigint,text,text,date) to authenticated;

notify pgrst,'reload schema';

commit;
