begin;

insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'PRODUCAO',true from (values
  ('producao_moldes.visualizar','Visualizar produção de moldes','Consulta produção, paradas e indicadores.'),
  ('producao_moldes.lancar','Lançar produção de moldes','Registra produção e paradas.'),
  ('producao_moldes.editar','Editar produção de moldes','Corrige registros de produção e paradas.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id from public.perfis profile
cross join public.permissoes permission
where (upper(profile.codigo) in ('ADMIN','ADMINISTRADOR')
  or upper(profile.nome)='ADMINISTRADOR')
and permission.codigo like 'producao_moldes.%'
and not exists(select 1 from public.perfil_permissoes relation
  where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

create table if not exists public.linhas_maquinas_producao (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.categorias_parada_producao (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

insert into public.categorias_parada_producao(codigo,nome)
values
 ('MANUTENCAO_MECANICA','Manutenção mecânica'),
 ('MANUTENCAO_ELETRICA','Manutenção elétrica'),
 ('FALTA_MATERIAL','Falta de material'),
 ('FALTA_METAL','Falta de metal'),
 ('FALTA_MAO_OBRA','Falta de mão de obra'),
 ('TROCA_MODELO','Troca de modelo'),
 ('AJUSTE_PROCESSO','Ajuste de processo'),
 ('QUALIDADE','Qualidade'),('LIMPEZA','Limpeza'),('SETUP','Setup'),
 ('PROGRAMACAO','Programação'),('OUTROS','Outros')
on conflict(codigo) do update set nome=excluded.nome;

create table if not exists public.registros_producao_moldes (
  id bigint generated by default as identity primary key,
  data_operacional date not null,
  turno text not null check(turno in ('MANHA','TARDE','NOITE')),
  produto_id bigint not null references public.produtos(id),
  linha_maquina_id bigint references public.linhas_maquinas_producao(id),
  quantidade_planejada integer not null default 0 check(quantidade_planejada>=0),
  quantidade_produzida integer not null default 0 check(quantidade_produzida>=0),
  quantidade_aprovada integer not null default 0 check(quantidade_aprovada>=0),
  quantidade_refugada integer not null default 0 check(quantidade_refugada>=0),
  observacao text,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  check(quantidade_aprovada+quantidade_refugada<=quantidade_produzida)
);

create unique index if not exists producao_moldes_registro_natural_idx
on public.registros_producao_moldes(
  data_operacional,turno,produto_id,coalesce(linha_maquina_id,0)
);
create index if not exists producao_moldes_data_turno_idx
on public.registros_producao_moldes(data_operacional desc,turno);

create table if not exists public.paradas_producao_moldes (
  id bigint generated by default as identity primary key,
  data_operacional date not null,
  turno text not null check(turno in ('MANHA','TARDE','NOITE')),
  produto_id bigint references public.produtos(id),
  linha_maquina_id bigint references public.linhas_maquinas_producao(id),
  categoria_id bigint not null references public.categorias_parada_producao(id),
  motivo text not null check(length(trim(motivo)) between 1 and 500),
  inicio timestamptz not null,
  fim timestamptz not null,
  duracao_minutos integer not null check(duracao_minutos>=0),
  observacao text,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  check(fim>=inicio),
  check(duracao_minutos=round(extract(epoch from (fim-inicio))/60))
);

create unique index if not exists paradas_producao_evidente_idx
on public.paradas_producao_moldes(
  inicio,fim,categoria_id,coalesce(linha_maquina_id,0)
);
create index if not exists paradas_producao_data_turno_idx
on public.paradas_producao_moldes(data_operacional desc,turno);

create or replace function public.usuario_tem_permissao_producao_moldes(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select user_permission.permitido
     from public.usuario_permissoes user_permission
     join public.permissoes permission on permission.id=user_permission.permissao_id
     where user_permission.usuario_id=auth.uid()
       and permission.codigo=p_codigo limit 1),
    exists(select 1 from public.usuario_perfis user_profile
      join public.perfil_permissoes profile_permission
        on profile_permission.perfil_id=user_profile.perfil_id
      join public.permissoes permission
        on permission.id=profile_permission.permissao_id
      where user_profile.usuario_id=auth.uid() and permission.codigo=p_codigo)
  );
$$;

alter table public.linhas_maquinas_producao enable row level security;
alter table public.categorias_parada_producao enable row level security;
alter table public.registros_producao_moldes enable row level security;
alter table public.paradas_producao_moldes enable row level security;

create policy linhas_maquinas_select on public.linhas_maquinas_producao
for select to authenticated using(
  public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
create policy categorias_parada_select on public.categorias_parada_producao
for select to authenticated using(
  public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
create policy producao_moldes_select on public.registros_producao_moldes
for select to authenticated using(
  public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
create policy producao_moldes_insert on public.registros_producao_moldes
for insert to authenticated with check(criado_por=auth.uid() and
  public.usuario_tem_permissao_producao_moldes('producao_moldes.lancar'));
create policy producao_moldes_update on public.registros_producao_moldes
for update to authenticated using(
  public.usuario_tem_permissao_producao_moldes('producao_moldes.editar'))
with check(public.usuario_tem_permissao_producao_moldes('producao_moldes.editar'));
create policy paradas_moldes_select on public.paradas_producao_moldes
for select to authenticated using(
  public.usuario_tem_permissao_producao_moldes('producao_moldes.visualizar'));
create policy paradas_moldes_insert on public.paradas_producao_moldes
for insert to authenticated with check(criado_por=auth.uid() and
  public.usuario_tem_permissao_producao_moldes('producao_moldes.lancar'));
create policy paradas_moldes_update on public.paradas_producao_moldes
for update to authenticated using(
  public.usuario_tem_permissao_producao_moldes('producao_moldes.editar'))
with check(public.usuario_tem_permissao_producao_moldes('producao_moldes.editar'));

grant execute on function public.usuario_tem_permissao_producao_moldes(text)
to authenticated;
grant select on public.linhas_maquinas_producao,
  public.categorias_parada_producao to authenticated;
grant select,insert,update on public.registros_producao_moldes,
  public.paradas_producao_moldes to authenticated;
grant usage,select on sequence
  public.linhas_maquinas_producao_id_seq,
  public.categorias_parada_producao_id_seq,
  public.registros_producao_moldes_id_seq,
  public.paradas_producao_moldes_id_seq
to authenticated;

commit;
