begin;

-- ==========================================================================
-- Dias da semana em que uma linha opera, por turno — hoje isso só existe pra
-- Linha 2 do Acabamento, e vive fixo no código (linha_2_ativa_acabamento,
-- com um "case" listando os dias). Essa tabela torna a regra configurável
-- por dado, com histórico por vigência (mesmo padrão já usado em
-- metas_gerenciais e paradas_programadas): criar uma vigência nova fecha a
-- anterior automaticamente, então dá pra mudar (ex.: Linha 2 de folga toda
-- segunda-feira) e reverter depois sem editar código nenhuma das duas vezes.
--
-- turno é opcional (null = vale pra qualquer turno), mesmo padrão de
-- metas_gerenciais/paradas_programadas — assim "Linha 2 de folga toda
-- segunda" cobre os 3 turnos com 1 cadastro só, sem precisar repetir 3x;
-- uma vigência específica de um turno tem prioridade sobre a geral.
--
-- Linha sem nenhuma vigência cadastrada aqui roda todos os dias — mesmo
-- comportamento de qualquer linha hoje que não tem essa restrição.
-- ==========================================================================
create table if not exists public.linha_turno_dias_ativos (
  id bigint generated by default as identity primary key,
  linha_maquina_id bigint not null references public.linhas_maquinas_producao(id),
  turno text check (turno in ('MANHA','TARDE','NOITE')),
  dias_semana smallint[] not null check (
    array_length(dias_semana,1) > 0
    and dias_semana <@ array[0,1,2,3,4,5,6]::smallint[]
  ),
  vigencia_inicio date not null,
  vigencia_fim date,
  criado_por uuid references public.usuarios(id),
  criado_em timestamptz not null default now(),
  check (vigencia_fim is null or vigencia_fim >= vigencia_inicio)
);

create index if not exists linha_turno_dias_ativos_busca_idx
  on public.linha_turno_dias_ativos(linha_maquina_id, vigencia_inicio desc);

-- No máximo uma vigência "em aberto" por combinação de linha/turno (turno
-- nulo tratado como um valor próprio, '-', pro índice não deixar duas linhas
-- nulas coexistirem — mesma técnica de paradas_programadas).
create unique index if not exists linha_turno_dias_ativos_vigente_uidx
  on public.linha_turno_dias_ativos(linha_maquina_id, coalesce(turno,'-'))
  where vigencia_fim is null;

alter table public.linha_turno_dias_ativos enable row level security;
drop policy if exists linha_turno_dias_ativos_select on public.linha_turno_dias_ativos;
create policy linha_turno_dias_ativos_select on public.linha_turno_dias_ativos
for select to authenticated using (auth.uid() is not null);
grant select on public.linha_turno_dias_ativos to authenticated;
grant usage,select on sequence public.linha_turno_dias_ativos_id_seq to authenticated;

-- Mesma permissão de metas_gerenciais (metas.gerenciar) — na prática é o
-- mesmo tipo de decisão de planejamento ("quando a linha roda").
create or replace function public.definir_linha_turno_dias_ativos(
  p_linha_maquina_id bigint,
  p_turno text,
  p_dias_semana smallint[],
  p_vigencia_inicio date
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_id bigint;
begin
  if not public.usuario_tem_permissao_metas('metas.gerenciar') then
    raise exception 'Usuário sem permissão para gerenciar os dias de operação da linha.';
  end if;
  if p_turno is not null and p_turno not in ('MANHA','TARDE','NOITE') then
    raise exception 'Turno inválido.';
  end if;
  if p_dias_semana is null or array_length(p_dias_semana,1) is null then
    raise exception 'Selecione ao menos um dia da semana.';
  end if;
  if not exists (select 1 from public.linhas_maquinas_producao where id = p_linha_maquina_id) then
    raise exception 'Linha inválida.';
  end if;

  update public.linha_turno_dias_ativos set vigencia_fim = p_vigencia_inicio - 1
  where linha_maquina_id = p_linha_maquina_id
    and coalesce(turno,'-') = coalesce(p_turno,'-')
    and vigencia_fim is null
    and vigencia_inicio < p_vigencia_inicio;

  insert into public.linha_turno_dias_ativos(linha_maquina_id,turno,dias_semana,vigencia_inicio,criado_por)
  values(p_linha_maquina_id,p_turno,p_dias_semana,p_vigencia_inicio,auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.definir_linha_turno_dias_ativos(bigint,text,smallint[],date) from public,anon;
grant execute on function public.definir_linha_turno_dias_ativos(bigint,text,smallint[],date) to authenticated;

-- ==========================================================================
-- Backfill: registra a regra atual da Linha 2 (hoje fixa em
-- linha_2_ativa_acabamento) como a primeira vigência — o comportamento em
-- produção não muda nada quando esta migração for aplicada de verdade.
--   Manhã: roda seg-sáb (não domingo)
--   Tarde: roda seg-sex (não sáb/dom)
--   Noite: roda seg-qui (não sex/sáb/dom)
-- ==========================================================================
insert into public.linha_turno_dias_ativos(linha_maquina_id, turno, dias_semana, vigencia_inicio)
select linha.id, regra.turno, regra.dias, date '2026-01-01'
from public.linhas_maquinas_producao linha
cross join (values
  ('MANHA', array[1,2,3,4,5,6]::smallint[]),
  ('TARDE', array[1,2,3,4,5]::smallint[]),
  ('NOITE', array[1,2,3,4]::smallint[])
) as regra(turno, dias)
where linha.codigo = 'ACABAMENTO_L2'
  and not exists (
    select 1 from public.linha_turno_dias_ativos existente
    where existente.linha_maquina_id = linha.id and existente.turno = regra.turno
  );

-- ==========================================================================
-- linha_2_ativa_acabamento passa a consultar a tabela em vez de ter os dias
-- escritos no código — mesma assinatura e mesmo comportamento de hoje
-- (garantido pelo backfill acima), só que agora editável via
-- definir_linha_turno_dias_ativos(...) sem precisar de nova migração. Uma
-- vigência específica do turno pedido tem prioridade sobre uma geral
-- (turno nulo), mesmo critério de meta_vigente().
-- ==========================================================================
create or replace function public.linha_2_ativa_acabamento(p_data_operacional date, p_turno text)
returns boolean
language sql
stable
as $function$
  select coalesce(
    (
      select extract(dow from p_data_operacional)::int = any(regra.dias_semana)
      from public.linha_turno_dias_ativos regra
      join public.linhas_maquinas_producao linha on linha.id = regra.linha_maquina_id
      where linha.codigo = 'ACABAMENTO_L2'
        and (regra.turno = p_turno or regra.turno is null)
        and regra.vigencia_inicio <= p_data_operacional
        and (regra.vigencia_fim is null or regra.vigencia_fim >= p_data_operacional)
      order by (regra.turno is not null) desc, regra.vigencia_inicio desc
      limit 1
    ),
    true
  )
$function$;

notify pgrst, 'reload schema';

commit;
