begin;

-- ==========================================================================
-- Quadro de recados por corrida — comunicação rápida entre quem planeja
-- (supervisor) e quem pesa na Ponte, nos dois sentidos. Não é um chat
-- completo (sem "lido/não lido"), só uma lista curta ligada à corrida.
-- ==========================================================================
create table public.corridas_fusao_mensagens (
  id bigint generated by default as identity primary key,
  corrida_id bigint not null references public.corridas_fusao(id) on delete cascade,
  autor_id uuid references public.usuarios(id),
  mensagem text not null check (length(trim(mensagem)) > 0 and length(mensagem) <= 500),
  criado_em timestamptz not null default now()
);
create index corridas_fusao_mensagens_corrida_idx on public.corridas_fusao_mensagens(corrida_id, criado_em);
alter table public.corridas_fusao_mensagens enable row level security;
create policy corridas_fusao_mensagens_select on public.corridas_fusao_mensagens for select to authenticated using (auth.uid() is not null);
grant select on public.corridas_fusao_mensagens to authenticated;
grant usage,select on sequence public.corridas_fusao_mensagens_id_seq to authenticated;

-- Quem lança produção (supervisor) ou só pesa na Ponte pode mandar
-- mensagem — os dois lados da conversa.
create or replace function public.enviar_mensagem_corrida_fusao(p_corrida_id bigint, p_mensagem text)
returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_id bigint;
begin
  if not (public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar')
       or public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar_ponte')) then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if not exists(select 1 from public.corridas_fusao where id = p_corrida_id) then
    raise exception 'Corrida não encontrada.';
  end if;
  if coalesce(trim(p_mensagem), '') = '' then raise exception 'Escreva uma mensagem.'; end if;
  insert into public.corridas_fusao_mensagens(corrida_id, autor_id, mensagem)
  values (p_corrida_id, auth.uid(), trim(p_mensagem))
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.enviar_mensagem_corrida_fusao(bigint,text) from public,anon;
grant execute on function public.enviar_mensagem_corrida_fusao(bigint,text) to authenticated;

do $$ begin
  if not exists(select 1 from pg_catalog.pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='corridas_fusao_mensagens') then
    alter publication supabase_realtime add table public.corridas_fusao_mensagens;
  end if;
end $$;

notify pgrst, 'reload schema';

commit;
