begin;

-- ==========================================================================
-- Transferência de metal entre fornos — parcial ou total, e pode ir pra
-- mais de um forno (o operador repete a ação uma vez por destino). O forno
-- destino precisa já ter uma corrida ABERTA esperando (não abre sozinho).
-- Não fecha a corrida de origem sozinho mesmo numa transferência total — o
-- operador fecha manualmente quando quiser, igual a qualquer outra corrida.
-- ==========================================================================
create table public.transferencias_fusao (
  id bigint generated by default as identity primary key,
  corrida_origem_id bigint not null references public.corridas_fusao(id),
  corrida_destino_id bigint not null references public.corridas_fusao(id),
  quantidade_kg numeric not null check (quantidade_kg > 0),
  registrado_por uuid references public.usuarios(id),
  registrado_em timestamptz not null default now()
);
create index transferencias_fusao_origem_idx on public.transferencias_fusao(corrida_origem_id);
create index transferencias_fusao_destino_idx on public.transferencias_fusao(corrida_destino_id);
alter table public.transferencias_fusao enable row level security;
create policy transferencias_fusao_select on public.transferencias_fusao for select to authenticated using (auth.uid() is not null);
grant select on public.transferencias_fusao to authenticated;
grant usage,select on sequence public.transferencias_fusao_id_seq to authenticated;

-- Volume de metal que o forno tem "guardado" agora: tudo que já foi
-- carregado/recebido nas corridas dele, menos o que já saiu por
-- transferência. É por FORNO (não por corrida) de propósito — é isso que
-- resolve a "sobra": o número não zera quando abre a corrida seguinte no
-- mesmo forno, porque continua sendo a mesma soma.
create or replace function public.volume_atual_forno_fusao(p_forno_id bigint)
returns numeric language sql stable set search_path=pg_catalog,public as $$
  select
    coalesce((
      select sum(item.quantidade_realizada_kg)
      from public.corridas_fusao_carga_itens item
      join public.corridas_fusao corrida on corrida.id = item.corrida_id
      where corrida.forno_id = p_forno_id and corrida.status <> 'CANCELADA'
    ), 0)
    + coalesce((
      select sum(transferencia.quantidade_kg)
      from public.transferencias_fusao transferencia
      join public.corridas_fusao destino on destino.id = transferencia.corrida_destino_id
      where destino.forno_id = p_forno_id
    ), 0)
    - coalesce((
      select sum(transferencia.quantidade_kg)
      from public.transferencias_fusao transferencia
      join public.corridas_fusao origem on origem.id = transferencia.corrida_origem_id
      where origem.forno_id = p_forno_id
    ), 0);
$$;
revoke all on function public.volume_atual_forno_fusao(bigint) from public,anon;
grant execute on function public.volume_atual_forno_fusao(bigint) to authenticated;

create or replace function public.transferir_metal_fusao(
  p_corrida_origem_id bigint, p_forno_destino_id bigint, p_quantidade_kg numeric
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_origem record;
  v_destino record;
  v_disponivel numeric;
  v_id bigint;
begin
  if not public.usuario_tem_permissao_producao_fusao('producao_fusao.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de fusão.';
  end if;
  if coalesce(p_quantidade_kg, 0) <= 0 then raise exception 'Informe uma quantidade maior que zero.'; end if;

  select * into v_origem from public.corridas_fusao where id = p_corrida_origem_id for update;
  if not found then raise exception 'Corrida de origem não encontrada.'; end if;
  if v_origem.status <> 'ABERTA' then raise exception 'A corrida de origem precisa estar aberta.'; end if;
  if v_origem.forno_id = p_forno_destino_id then raise exception 'O forno destino precisa ser diferente do forno de origem.'; end if;

  v_disponivel := public.volume_atual_forno_fusao(v_origem.forno_id);
  if p_quantidade_kg > v_disponivel then
    raise exception 'Quantidade maior que o volume disponível no forno (% kg).', v_disponivel;
  end if;

  select * into v_destino from public.corridas_fusao where forno_id = p_forno_destino_id and status = 'ABERTA';
  if not found then raise exception 'O forno destino não tem corrida aberta.'; end if;

  insert into public.transferencias_fusao(corrida_origem_id, corrida_destino_id, quantidade_kg, registrado_por)
  values (p_corrida_origem_id, v_destino.id, p_quantidade_kg, auth.uid())
  returning id into v_id;

  return v_id;
end;
$$;
revoke all on function public.transferir_metal_fusao(bigint,bigint,numeric) from public,anon;
grant execute on function public.transferir_metal_fusao(bigint,bigint,numeric) to authenticated;

notify pgrst, 'reload schema';

commit;
