begin;

-- A tabela public.produtos nunca ganhou uma função de checagem de permissão própria
-- (o RLS de fichas técnicas usa usuario_tem_permissao_ficha). Esta função espelha
-- exatamente o mesmo padrão, usando o código de permissão já existente "produto.editar".
create or replace function public.usuario_tem_permissao_produto(
  p_codigo text
)
returns boolean
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_permitido_individual boolean;
begin
  if v_usuario_id is null then
    return false;
  end if;

  select usuario_permissao.permitido
    into v_permitido_individual
  from public.usuario_permissoes usuario_permissao
  join public.permissoes permissao
    on permissao.id = usuario_permissao.permissao_id
  where usuario_permissao.usuario_id = v_usuario_id
    and permissao.codigo = p_codigo
  limit 1;

  if found then
    return coalesce(v_permitido_individual, false);
  end if;

  return exists (
    select 1
    from public.usuario_perfis usuario_perfil
    join public.perfil_permissoes perfil_permissao
      on perfil_permissao.perfil_id = usuario_perfil.perfil_id
    join public.permissoes permissao
      on permissao.id = perfil_permissao.permissao_id
    where usuario_perfil.usuario_id = v_usuario_id
      and permissao.codigo = p_codigo
  );
end;
$$;

revoke all on function public.usuario_tem_permissao_produto(text) from public;
grant execute on function public.usuario_tem_permissao_produto(text) to authenticated;

create table if not exists public.tempos_ciclo_padrao (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.produtos(id),
  area_id bigint not null references public.areas_checklist(id),
  identificador text,
  tempo_ciclo_segundos numeric not null check (tempo_ciclo_segundos > 0),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now()
);

create index if not exists tempos_ciclo_padrao_produto_idx
  on public.tempos_ciclo_padrao(produto_id, area_id);

-- unique() de tabela só aceita colunas simples; coalesce(identificador,'') é uma
-- expressão, por isso a unicidade precisa ser um índice único, não uma constraint.
create unique index if not exists tempos_ciclo_padrao_uidx
  on public.tempos_ciclo_padrao(produto_id, area_id, coalesce(identificador,''));

alter table public.tempos_ciclo_padrao enable row level security;

drop policy if exists tempos_ciclo_padrao_select on public.tempos_ciclo_padrao;
create policy tempos_ciclo_padrao_select on public.tempos_ciclo_padrao
for select to authenticated using (auth.uid() is not null);

drop policy if exists tempos_ciclo_padrao_insert on public.tempos_ciclo_padrao;
create policy tempos_ciclo_padrao_insert on public.tempos_ciclo_padrao
for insert to authenticated with check (public.usuario_tem_permissao_produto('produto.editar'));

drop policy if exists tempos_ciclo_padrao_update on public.tempos_ciclo_padrao;
create policy tempos_ciclo_padrao_update on public.tempos_ciclo_padrao
for update to authenticated using (public.usuario_tem_permissao_produto('produto.editar'))
with check (public.usuario_tem_permissao_produto('produto.editar'));

drop policy if exists tempos_ciclo_padrao_delete on public.tempos_ciclo_padrao;
create policy tempos_ciclo_padrao_delete on public.tempos_ciclo_padrao
for delete to authenticated using (public.usuario_tem_permissao_produto('produto.editar'));

grant select,insert,update,delete on public.tempos_ciclo_padrao to authenticated;
grant usage,select on sequence public.tempos_ciclo_padrao_id_seq to authenticated;

notify pgrst,'reload schema';

commit;
