begin;

-- Catálogo dos tipos de parada programada (refeição, hidratação, manutenção
-- preventiva, etc.) — paradas reais que caem dentro dessas janelas de horário
-- não impactam a disponibilidade, pois já são esperadas/planejadas.
create table if not exists public.tipos_parada_programada (
  codigo text primary key,
  nome text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

insert into public.tipos_parada_programada(codigo,nome) values
  ('REFEICAO','Refeição'),
  ('HIDRATACAO','Hidratação'),
  ('MANUTENCAO_PREVENTIVA','Manutenção Preventiva')
on conflict(codigo) do nothing;

alter table public.tipos_parada_programada enable row level security;
drop policy if exists tipos_parada_programada_select on public.tipos_parada_programada;
create policy tipos_parada_programada_select on public.tipos_parada_programada
for select to authenticated using(auth.uid() is not null);
grant select on public.tipos_parada_programada to authenticated;

-- Estrutura genérica (reaproveitável por qualquer setor), mesmo padrão de
-- histórico por vigência de metas_gerenciais: alterar um horário nunca muda o
-- cálculo de turnos já fechados no passado.
create table if not exists public.paradas_programadas (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.areas_checklist(id),
  linha_maquina_id bigint references public.linhas_maquinas_producao(id),
  turno text check (turno in ('MANHA','TARDE','NOITE')),
  tipo_parada_codigo text not null references public.tipos_parada_programada(codigo),
  horario_inicial time not null,
  horario_final time not null,
  dias_semana smallint[] not null check (
    array_length(dias_semana,1) > 0
    and dias_semana <@ array[0,1,2,3,4,5,6]::smallint[]
  ),
  vigencia_inicio date not null,
  vigencia_fim date,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  check (vigencia_fim is null or vigencia_fim >= vigencia_inicio)
);

create index if not exists paradas_programadas_busca_idx
  on public.paradas_programadas(area_id, vigencia_inicio desc);

-- No máximo uma vigência "em aberto" por combinação de área/linha/turno/tipo.
create unique index if not exists paradas_programadas_vigente_uidx
  on public.paradas_programadas(area_id, coalesce(linha_maquina_id,-1), coalesce(turno,'-'), tipo_parada_codigo)
  where vigencia_fim is null;

alter table public.paradas_programadas enable row level security;

drop policy if exists paradas_programadas_select on public.paradas_programadas;
create policy paradas_programadas_select on public.paradas_programadas for select to authenticated using(
  public.usuario_tem_permissao_metas('metas.visualizar') or public.usuario_tem_permissao_metas('metas.gerenciar')
);
grant select on public.paradas_programadas to authenticated;
grant usage,select on sequence public.paradas_programadas_id_seq to authenticated;

create or replace function public.definir_parada_programada(
  p_area_id bigint,
  p_linha_maquina_id bigint,
  p_turno text,
  p_tipo_parada_codigo text,
  p_horario_inicial time,
  p_horario_final time,
  p_dias_semana smallint[],
  p_vigencia_inicio date
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_id bigint;
begin
  if not public.usuario_tem_permissao_metas('metas.gerenciar') then
    raise exception 'Usuário sem permissão para gerenciar paradas programadas.';
  end if;
  if p_turno is not null and p_turno not in ('MANHA','TARDE','NOITE') then
    raise exception 'Turno inválido.';
  end if;
  if p_dias_semana is null or array_length(p_dias_semana,1) is null then
    raise exception 'Selecione ao menos um dia da semana.';
  end if;

  update public.paradas_programadas set vigencia_fim = p_vigencia_inicio - 1
  where area_id=p_area_id
    and coalesce(linha_maquina_id,-1)=coalesce(p_linha_maquina_id,-1)
    and coalesce(turno,'-')=coalesce(p_turno,'-')
    and tipo_parada_codigo=p_tipo_parada_codigo
    and vigencia_fim is null
    and vigencia_inicio < p_vigencia_inicio;

  insert into public.paradas_programadas(
    area_id,linha_maquina_id,turno,tipo_parada_codigo,horario_inicial,horario_final,dias_semana,vigencia_inicio,criado_por
  ) values (
    p_area_id,p_linha_maquina_id,p_turno,p_tipo_parada_codigo,p_horario_inicial,p_horario_final,p_dias_semana,p_vigencia_inicio,auth.uid()
  ) returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.definir_parada_programada(bigint,bigint,text,text,time,time,smallint[],date) from public,anon;
grant execute on function public.definir_parada_programada(bigint,bigint,text,text,time,time,smallint[],date) to authenticated;

notify pgrst,'reload schema';

commit;
