begin;

insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'CONTROLE_PROCESSO',true from (values
  ('checklist.visualizar','Visualizar checklists','Consulta checklists, medições e desvios.'),
  ('checklist.preencher','Preencher checklists','Executa checklists operacionais.'),
  ('checklist.aprovar','Liberar checklists críticos','Libera ou mantém bloqueados os desvios críticos.'),
  ('checklist.configurar','Configurar checklists','Mantém modelos, itens e frequências.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id
from public.perfis profile cross join public.permissoes permission
where permission.codigo in('checklist.visualizar','checklist.preencher')
  and upper(coalesce(profile.codigo,'')) in(
    'ADMIN','ADMINISTRADOR','GERENTE_GERAL','GERENTE_PRODUCAO',
    'COORDENADOR_PRODUCAO','GERENTE_QUALIDADE','FUSAO','MOLDAGEM',
    'VAZAMENTO','MACHARIA','ACABAMENTO'
  )
  and not exists(select 1 from public.perfil_permissoes relation
    where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id
from public.perfis profile cross join public.permissoes permission
where permission.codigo='checklist.aprovar'
  and upper(coalesce(profile.codigo,'')) in(
    'ADMIN','ADMINISTRADOR','GERENTE_GERAL','GERENTE_PRODUCAO',
    'COORDENADOR_PRODUCAO','GERENTE_QUALIDADE'
  )
  and not exists(select 1 from public.perfil_permissoes relation
    where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id
from public.perfis profile cross join public.permissoes permission
where permission.codigo='checklist.configurar'
  and upper(coalesce(profile.codigo,'')) in('ADMIN','ADMINISTRADOR')
  and not exists(select 1 from public.perfil_permissoes relation
    where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

create or replace function public.usuario_tem_permissao_checklist(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select user_permission.permitido
     from public.usuario_permissoes user_permission
     join public.permissoes permission on permission.id=user_permission.permissao_id
     where user_permission.usuario_id=auth.uid()
       and permission.codigo=p_codigo limit 1),
    exists(select 1 from public.usuario_perfis user_profile
      join public.perfil_permissoes profile_permission
        on profile_permission.perfil_id=user_profile.perfil_id
      join public.permissoes permission
        on permission.id=profile_permission.permissao_id
      where user_profile.usuario_id=auth.uid() and permission.codigo=p_codigo),
    false
  );
$$;

grant execute on function public.usuario_tem_permissao_checklist(text) to authenticated;

create table if not exists public.areas_checklist (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ordem integer not null default 0,
  cor text not null default '#1f45a8',
  ativo boolean not null default true
);

create table if not exists public.modelos_checklist (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.areas_checklist(id),
  codigo text not null unique,
  nome text not null,
  descricao text,
  instrucao_codigo text,
  instrucao_revisao text,
  frequencia_tipo text not null check(frequencia_tipo in(
    'INICIO_TURNO','SETUP','INTERVALO','CORRIDA','DIARIO','SEMANAL','EVENTO','ESPECIAL'
  )),
  intervalo_minutos integer check(intervalo_minutos is null or intervalo_minutos>0),
  produto_obrigatorio boolean not null default false,
  equipamento_obrigatorio boolean not null default false,
  corrida_obrigatoria boolean not null default false,
  versao integer not null default 1,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.itens_checklist (
  id bigint generated by default as identity primary key,
  modelo_id bigint not null references public.modelos_checklist(id) on delete cascade,
  codigo text not null,
  secao text not null default 'Verificações',
  descricao text not null,
  orientacao text,
  tipo_resposta text not null default 'CONFORMIDADE' check(tipo_resposta in(
    'CONFORMIDADE','NUMERO','TEXTO','SIM_NAO'
  )),
  unidade text,
  valor_minimo numeric,
  valor_alvo numeric,
  valor_maximo numeric,
  permite_na boolean not null default false,
  critico boolean not null default false,
  gera_carta boolean not null default false,
  plano_reacao text,
  ordem integer not null default 0,
  ativo boolean not null default true,
  unique(modelo_id,codigo)
);

create table if not exists public.execucoes_checklist (
  id bigint generated by default as identity primary key,
  modelo_id bigint not null references public.modelos_checklist(id),
  data_operacional date not null default current_date,
  turno text not null check(turno in('MANHA','TARDE','NOITE')),
  produto_id bigint references public.produtos(id),
  equipamento text,
  corrida text,
  status text not null default 'EM_PREENCHIMENTO' check(status in(
    'EM_PREENCHIMENTO','CONFORME','NAO_CONFORME','AGUARDANDO_SUPERVISOR','BLOQUEADO','LIBERADO'
  )),
  observacao text,
  iniciado_em timestamptz not null default now(),
  concluido_em timestamptz,
  operador_id uuid not null default auth.uid() references public.usuarios(id),
  modelo_versao integer not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.respostas_checklist (
  id bigint generated by default as identity primary key,
  execucao_id bigint not null references public.execucoes_checklist(id) on delete cascade,
  item_id bigint not null references public.itens_checklist(id),
  resultado text check(resultado in('CONFORME','NAO_CONFORME','NAO_APLICAVEL')),
  valor_numero numeric,
  valor_texto text,
  observacao text,
  acao_imediata text,
  respondido_por uuid not null default auth.uid() references public.usuarios(id),
  respondido_em timestamptz not null default now(),
  unique(execucao_id,item_id)
);

create table if not exists public.liberacoes_checklist (
  id bigint generated by default as identity primary key,
  execucao_id bigint not null references public.execucoes_checklist(id) on delete cascade,
  decisao text not null check(decisao in('LIBERADO','MANTIDO_BLOQUEADO')),
  justificativa text not null check(length(trim(justificativa))>=3),
  supervisor_id uuid not null default auth.uid() references public.usuarios(id),
  decidido_em timestamptz not null default now()
);

create table if not exists public.medicoes_checklist (
  id bigint generated by default as identity primary key,
  execucao_id bigint not null references public.execucoes_checklist(id) on delete cascade,
  resposta_id bigint not null unique references public.respostas_checklist(id) on delete cascade,
  item_id bigint not null references public.itens_checklist(id),
  produto_id bigint references public.produtos(id),
  equipamento text,
  valor numeric not null,
  limite_minimo numeric,
  valor_alvo numeric,
  limite_maximo numeric,
  conforme boolean,
  medido_em timestamptz not null default now()
);

create index if not exists execucoes_checklist_data_idx
  on public.execucoes_checklist(data_operacional desc,status);
create index if not exists execucoes_checklist_modelo_idx
  on public.execucoes_checklist(modelo_id,iniciado_em desc);
create index if not exists medicoes_checklist_item_idx
  on public.medicoes_checklist(item_id,medido_em desc);

alter table public.areas_checklist enable row level security;
alter table public.modelos_checklist enable row level security;
alter table public.itens_checklist enable row level security;
alter table public.execucoes_checklist enable row level security;
alter table public.respostas_checklist enable row level security;
alter table public.liberacoes_checklist enable row level security;
alter table public.medicoes_checklist enable row level security;

create policy areas_checklist_select on public.areas_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy modelos_checklist_select on public.modelos_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy itens_checklist_select on public.itens_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy execucoes_checklist_select on public.execucoes_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy execucoes_checklist_insert on public.execucoes_checklist for insert to authenticated
with check(operador_id=auth.uid() and public.usuario_tem_permissao_checklist('checklist.preencher'));
create policy execucoes_checklist_update_operador on public.execucoes_checklist for update to authenticated
using(operador_id=auth.uid() and status='EM_PREENCHIMENTO'
  and public.usuario_tem_permissao_checklist('checklist.preencher'))
with check(operador_id=auth.uid() and public.usuario_tem_permissao_checklist('checklist.preencher'));
create policy execucoes_checklist_update_supervisor on public.execucoes_checklist for update to authenticated
using(public.usuario_tem_permissao_checklist('checklist.aprovar'))
with check(public.usuario_tem_permissao_checklist('checklist.aprovar'));
create policy respostas_checklist_select on public.respostas_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy respostas_checklist_insert on public.respostas_checklist for insert to authenticated
with check(respondido_por=auth.uid() and public.usuario_tem_permissao_checklist('checklist.preencher'));
create policy liberacoes_checklist_select on public.liberacoes_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy liberacoes_checklist_insert on public.liberacoes_checklist for insert to authenticated
with check(supervisor_id=auth.uid() and public.usuario_tem_permissao_checklist('checklist.aprovar'));
create policy medicoes_checklist_select on public.medicoes_checklist for select to authenticated
using(public.usuario_tem_permissao_checklist('checklist.visualizar'));
create policy medicoes_checklist_insert on public.medicoes_checklist for insert to authenticated
with check(public.usuario_tem_permissao_checklist('checklist.preencher'));

grant select on public.areas_checklist,public.modelos_checklist,public.itens_checklist,
  public.execucoes_checklist,public.respostas_checklist,public.liberacoes_checklist,
  public.medicoes_checklist to authenticated;
grant update on public.execucoes_checklist to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into public.areas_checklist(codigo,nome,ordem,cor) values
  ('MOLDAGEM','Moldagem',1,'#1f45a8'),
  ('VAZAMENTO','Vazamento',2,'#b42318'),
  ('FUSAO','Fusão',3,'#d97706'),
  ('MACHARIA','Macharia',4,'#15803d'),
  ('ACABAMENTO','Acabamento',5,'#6d28d9')
on conflict(codigo) do update set nome=excluded.nome,ordem=excluded.ordem,cor=excluded.cor;

insert into public.modelos_checklist(
  area_id,codigo,nome,descricao,instrucao_codigo,frequencia_tipo,intervalo_minutos,
  produto_obrigatorio,equipamento_obrigatorio,corrida_obrigatoria
)
select area.id,model.codigo,model.nome,model.descricao,model.instrucao,
  model.frequencia,model.intervalo,model.produto,model.equipamento,model.corrida
from (values
 ('MOLDAGEM','M01','Liberação de setup da DISA','Liberação de produto e ferramental na DISA.','ITF-PRO-026','SETUP',null,true,true,false),
 ('MOLDAGEM','M02','Inspeção periódica de moldes','Verificação operacional a cada 30 minutos.','ITF-PRO-026','INTERVALO',30,true,true,false),
 ('VAZAMENTO','V01','Liberação pré-operacional da OCU 55','Condição da panela e equipamentos no início do turno.','ITF-PRO-022','INICIO_TURNO',null,false,true,false),
 ('VAZAMENTO','V02','Liberação de setup de vazamento','Liberação por produto, metal ou retomada.','ITF-PRO-022','SETUP',null,true,true,false),
 ('VAZAMENTO','V03','Calibração do inoculante','Calibração no início da produção ou troca de material.','ITF-PRO-024','EVENTO',null,true,true,false),
 ('VAZAMENTO','V04','Inspeção periódica da OCU 55','Desgaste, componentes e dimensões da panela.','ITF-PRO-032 / ITF-PRO-035','SEMANAL',null,false,true,false),
 ('VAZAMENTO','V05','Segregação de material duvidoso','Registro de desvio e faixa de três moldes antes e depois.','ITF-PRO-027','EVENTO',null,true,false,false),
 ('FUSAO','F01','Condições diárias da Fusão','Condições de panelas, fornos, balanças e área.','ITF-PRO-001 / ITF-PRO-004 / ITF-PRO-006','DIARIO',null,false,true,false),
 ('FUSAO','F02','Verificação periódica da Fusão','Verificações operacionais a cada duas horas.','ITF-PRO-001 / ITF-PRO-006','INTERVALO',120,false,true,false),
 ('FUSAO','F03','Liberação de corrida e tratamento','Liberação do metal exclusivamente por corrida.','ITF-PRO-004','CORRIDA',null,true,true,true),
 ('FUSAO','F04','Revestimento e sinterização','Fluxo especial de revestimento e sinterização.','ITF-PRO-003 / ITF-PRO-005','ESPECIAL',null,false,true,false),
 ('MACHARIA','MA01','Liberação da sopradora','Inspeção da SPM20 ou HV3 no início do turno.','ITF-PRO-013 / ITF-PRO-014','INICIO_TURNO',null,false,true,false),
 ('MACHARIA','MA02','Liberação de setup da Macharia','Receita, ferramental e primeiro macho.','ITF-PRO-013 / ITF-PRO-014','SETUP',null,true,true,false),
 ('MACHARIA','MA03','Aferição de areia e resina','Aferição programada a cada duas horas.','ITF-PRO-012','INTERVALO',120,true,true,false),
 ('MACHARIA','MA04','Checklist da estufa','Condições da estufa no início do turno.','ITF-PRO-016','INICIO_TURNO',null,false,true,false),
 ('MACHARIA','MA05','Limpeza dos tanques de pintura','Limpeza semanal ou por necessidade.','ITF-PRO-015','SEMANAL',null,false,true,false),
 ('ACABAMENTO','A01','Máquinas de rebarbação','Inspeção do equipamento por posto.','ITF-PRO-019','INICIO_TURNO',null,false,true,false),
 ('ACABAMENTO','A02','Jatos 1 e 2','Inspeção operacional dos jatos turbinados.','ITF-PRO-018','INICIO_TURNO',null,false,true,false),
 ('ACABAMENTO','A03','Jato 3','Inspeção operacional do jato de gancheira.','ITF-PRO-018','INICIO_TURNO',null,false,true,false)
) model(area,codigo,nome,descricao,instrucao,frequencia,intervalo,produto,equipamento,corrida)
join public.areas_checklist area on area.codigo=model.area
on conflict(codigo) do update set
  nome=excluded.nome,descricao=excluded.descricao,instrucao_codigo=excluded.instrucao_codigo,
  frequencia_tipo=excluded.frequencia_tipo,intervalo_minutos=excluded.intervalo_minutos,
  produto_obrigatorio=excluded.produto_obrigatorio,
  equipamento_obrigatorio=excluded.equipamento_obrigatorio,
  corrida_obrigatoria=excluded.corrida_obrigatoria,ativo=true;

with item_data(modelo,codigo,secao,descricao,tipo,unidade,minimo,alvo,maximo,permite_na,critico,carta,reacao,ordem) as (values
 ('M01','01','Ferramental','Condição e identificação do ferramental','CONFORMIDADE',null,null,null,null,false,true,false,'Interditar o ferramental e acionar a modelação.',1),
 ('M01','02','Processo','Parâmetros da DISA conforme ficha técnica','CONFORMIDADE',null,null,null,null,false,true,false,'Ajustar os parâmetros e comunicar o responsável.',2),
 ('M01','03','Machos','Condição e posicionamento dos machos','CONFORMIDADE',null,null,null,null,true,true,false,'Rejeitar o lote afetado e acionar Macharia/Modelação.',3),
 ('M01','04','Processo','Condição da areia no silo','CONFORMIDADE',null,null,null,null,false,true,false,'Descartar areia parada e solicitar areia nova.',4),
 ('M01','05','Segurança do processo','Funcionamento do poka-yoke do filtro','CONFORMIDADE',null,null,null,null,true,true,false,'Parar a produção e acionar a manutenção.',5),
 ('M01','06','Processo','Cinco moldes da peça estrela realizados','SIM_NAO',null,null,null,null,false,true,false,'Bloquear a liberação até realizar a verificação.',6),
 ('M02','01','Molde','Condição do modelo','CONFORMIDADE',null,null,null,null,false,false,false,'Registrar e corrigir o desvio.',1),
 ('M02','02','Molde','Condição do molde','CONFORMIDADE',null,null,null,null,false,true,false,'Parar e avaliar o molde.',2),
 ('M02','03','Ferramental','Identificação dos ferramentais','CONFORMIDADE',null,null,null,null,false,false,false,'Corrigir a identificação.',3),
 ('M02','04','Medição','Compressibilidade encontrada','NUMERO','%',null,null,null,false,false,true,'Ajustar o processo conforme a ficha técnica.',4),
 ('V01','01','Comando','Painel, bomba hidráulica e carro de basculamento','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção e supervisor.',1),
 ('V01','02','Movimentação','Ponte rolante em condição normal','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção.',2),
 ('V01','03','Panela','Bicas, refratário, stopper e nozzle','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear a panela e corrigir o componente.',3),
 ('V01','04','Inoculação','Mastervolt, tubo e ponteira de grafite','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção e recalibrar.',4),
 ('V01','05','Segurança do processo','Pressão de nitrogênio, alarmes e bloqueios','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear a operação.',5),
 ('V01','06','Visão computacional','Sistema de visão disponível e sem obstruções','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção; usar contingência autorizada.',6),
 ('V02','01','Temperatura','Temperatura da OCU 55','NUMERO','°C',950,null,null,false,true,true,'Aguardar aquecimento ou realizar enxarque.',1),
 ('V02','02','Vazamento','Stopper e nozzle em condição de uso','CONFORMIDADE',null,null,null,null,false,true,false,'Ajustar ou substituir antes da liberação.',2),
 ('V02','03','Inoculação','Tipo e lote do inoculante conferidos','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir o material antes da liberação.',3),
 ('V02','04','Inoculação','Calibração vigente e aprovada','CONFORMIDADE',null,null,null,null,false,true,false,'Realizar nova calibração.',4),
 ('V02','05','Start-up','Cinco moldes mínimos de gusa realizados','SIM_NAO',null,null,null,null,false,true,false,'Não liberar as peças até completar o start-up.',5),
 ('V02','06','Visão computacional','Filtro, temperatura e inoculação detectados','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e acionar manutenção.',6),
 ('V03','01','Cálculo','Faixa esperada de inoculante','NUMERO','g/s',null,null,null,false,false,true,'Conferir cálculo e ficha técnica.',1),
 ('V03','02','Pesagens','Pesagem 1','NUMERO','g',null,null,null,false,false,false,'Repetir a medição se inválida.',2),
 ('V03','03','Pesagens','Pesagem 2','NUMERO','g',null,null,null,false,false,false,'Repetir a medição se inválida.',3),
 ('V03','04','Pesagens','Pesagem 3','NUMERO','g',null,null,null,false,false,false,'Repetir a medição se inválida.',4),
 ('V03','05','Resultado','Valor encontrado','NUMERO','g/s',null,null,null,false,true,true,'Recalibrar e acionar manutenção se persistir.',5),
 ('V04','01','Componentes','Condição das bicas e válvula','CONFORMIDADE',null,null,null,null,false,true,false,'Programar ou realizar a troca.',1),
 ('V04','02','Componentes','Condição da tampa e corpo da panela','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e avaliar o refratário.',2),
 ('V04','03','Componentes','Condição do stopper e nozzle','CONFORMIDADE',null,null,null,null,false,true,false,'Substituir o componente.',3),
 ('V05','01','Desvio','Motivo da segregação','TEXTO',null,null,null,null,false,true,false,'Informar o motivo.',1),
 ('V05','02','Rastreabilidade','Molde afetado','TEXTO',null,null,null,null,false,true,false,'Identificar o molde.',2),
 ('V05','03','Segregação','Três moldes anteriores segregados','SIM_NAO',null,null,null,null,false,true,false,'Segregar antes de prosseguir.',3),
 ('V05','04','Segregação','Três moldes posteriores segregados','SIM_NAO',null,null,null,null,false,true,false,'Segregar antes de prosseguir.',4),
 ('F01','01','Panelas','Desgaste, armazenamento, limpeza e camada de sacrifício','CONFORMIDADE',null,null,null,null,false,true,false,'Retirar a panela de uso.',1),
 ('F01','02','Transferência','Balanças, bacias e calhas em condição','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção.',2),
 ('F01','03','Forno','Corrente de fuga e isolação dos fornos','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear o forno e acionar manutenção.',3),
 ('F01','04','Instrumentos','Painel e instrumentos de temperatura','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção/instrumentação.',4),
 ('F01','05','Balanças','Aferição com pesos-padrão','CONFORMIDADE',null,null,null,null,false,true,false,'Não liberar a pesagem até aferição conforme.',5),
 ('F02','01','Operação','Nível de metal','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir o nível do processo.',1),
 ('F02','02','Operação','Liga 1 e sucata de cobertura posicionadas','CONFORMIDADE',null,null,null,null,false,false,false,'Corrigir o abastecimento.',2),
 ('F02','03','Limpeza','Limpeza do metal nos fornos','CONFORMIDADE',null,null,null,null,false,true,false,'Realizar limpeza.',3),
 ('F02','04','Limpeza','Limpeza do metal nas panelas','CONFORMIDADE',null,null,null,null,false,true,false,'Realizar limpeza.',4),
 ('F03','01','Corrida','Temperatura do forno','NUMERO','°C',null,null,null,false,true,true,'Ajustar temperatura e medir novamente.',1),
 ('F03','02','Corrida','Carbono equivalente','NUMERO','%',null,null,null,false,true,true,'Corrigir a carga conforme instrução.',2),
 ('F03','03','Corrida','Amostra coletada e laboratório liberou','CONFORMIDADE',null,null,null,null,false,true,false,'Aguardar análise e liberação.',3),
 ('F03','04','Tratamento','Materiais e lotes conferidos','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir materiais antes do tratamento.',4),
 ('F04','01','Preparação','Equipamento bloqueado e liberado para intervenção','CONFORMIDADE',null,null,null,null,false,true,false,'Não iniciar a intervenção.',1),
 ('F04','02','Refratário','Instalação do refratário concluída','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir antes de avançar.',2),
 ('F04','03','Sinterização','Temperatura do forno','NUMERO','°C',null,null,null,false,true,true,'Seguir plano da curva de sinterização.',3),
 ('F04','04','Sinterização','Corrente','NUMERO','A',null,null,null,false,true,true,'Avaliar antes de continuar.',4),
 ('F04','05','Sinterização','Isolação','NUMERO','kΩ',10,null,null,false,true,true,'Não liberar o forno.',5),
 ('MA01','01','Fluidos','Óleo, catalisador e resinas disponíveis','CONFORMIDADE',null,null,null,null,false,true,false,'Reabastecer/corrigir antes da operação.',1),
 ('MA01','02','Vazamentos','Ausência de vazamentos','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e acionar manutenção.',2),
 ('MA01','03','Segurança','Barreira e botoeira de emergência','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear a sopradora.',3),
 ('MA01','04','Ferramental','Caixa de machos sem avarias','CONFORMIDADE',null,null,null,null,false,true,false,'Interditar o ferramental.',4),
 ('MA02','01','Receita','Receita conforme ficha técnica','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir receita.',1),
 ('MA02','02','Ferramental','Ferramental identificado e sem avarias','CONFORMIDADE',null,null,null,null,false,true,false,'Interditar ferramental.',2),
 ('MA02','03','Máquina','Parâmetros da sopradora conforme ficha','CONFORMIDADE',null,null,null,null,false,true,false,'Ajustar parâmetros.',3),
 ('MA02','04','Produto','Primeiro macho aprovado','CONFORMIDADE',null,null,null,null,false,true,false,'Ajustar processo e produzir nova amostra.',4),
 ('MA03','01','Dosagem','Areia encontrada','NUMERO','kg',null,null,null,false,true,true,'Ajustar dosagem.',1),
 ('MA03','02','Dosagem','Resina Parte I encontrada','NUMERO','g',null,null,null,false,true,true,'Ajustar dosagem.',2),
 ('MA03','03','Dosagem','Resina Parte II encontrada','NUMERO','g',null,null,null,false,true,true,'Ajustar dosagem.',3),
 ('MA03','04','Dosagem','Óxido de ferro encontrado','NUMERO','g',null,null,null,true,false,true,'Ajustar dosagem.',4),
 ('MA03','05','Qualidade','Ensaio de tração aprovado','CONFORMIDADE',null,null,null,null,true,true,false,'Segregar e corrigir a mistura.',5),
 ('MA04','01','Equipamento','Painel, resfriamento e queimadores','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e acionar manutenção.',1),
 ('MA04','02','Segurança','Poka-yoke de temperatura','CONFORMIDADE',null,null,null,null,false,true,false,'Não liberar a estufa.',2),
 ('MA04','03','Processo','Temperatura da estufa','NUMERO','°C',null,null,null,false,true,true,'Ajustar temperatura e conter produto afetado.',3),
 ('MA04','04','Processo','Velocidade da transportadora','NUMERO','m/min',null,null,null,false,true,true,'Ajustar velocidade.',4),
 ('MA05','01','Limpeza','Tanque esvaziado e limpo internamente','CONFORMIDADE',null,null,null,null,false,true,false,'Concluir limpeza.',1),
 ('MA05','02','Resíduos','Resíduos acondicionados e identificados','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir destinação.',2),
 ('MA05','03','Liberação','Densidade ajustada após abastecimento','NUMERO','°Bé',null,null,null,false,true,true,'Ajustar a densidade.',3),
 ('A01','01','Condição','Ajuste da bancada e ausência de vibração anormal','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e acionar manutenção.',1),
 ('A01','02','Ferramenta','Disco, rebolo, ponta ou lima em condição','CONFORMIDADE',null,null,null,null,false,true,false,'Substituir a ferramenta.',2),
 ('A01','03','Segurança','Proteções, cabos e acionamentos','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear o equipamento.',3),
 ('A01','04','Exaustão','Sistema de exaustão funcionando','CONFORMIDADE',null,null,null,null,true,true,false,'Acionar manutenção.',4),
 ('A02','01','Abrasivo','Nível e ausência de vazamento de granalha','CONFORMIDADE',null,null,null,null,false,true,false,'Corrigir antes de operar.',1),
 ('A02','02','Segurança','Tela, calhas e borrachas em condição','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e acionar manutenção.',2),
 ('A02','03','Turbinas','Turbinas e palhetas em condição','CONFORMIDADE',null,null,null,null,false,true,false,'Acionar manutenção.',3),
 ('A02','04','Medição','Amperagem mínima das turbinas','NUMERO','A',30,null,null,false,true,true,'Parar e avaliar turbina/manutenção.',4),
 ('A02','05','Granalha','Mix de partículas grandes','NUMERO','%',40,null,null,false,true,true,'Corrigir o mix de granalha.',5),
 ('A02','06','Limpeza','Porão, coletor e entorno limpos','CONFORMIDADE',null,null,null,null,false,false,false,'Realizar limpeza.',6),
 ('A03','01','Movimentação','Talhas e gancheiras em condição','CONFORMIDADE',null,null,null,null,false,true,false,'Bloquear e acionar manutenção.',1),
 ('A03','02','Segurança','Portas alinhadas e vedadas','CONFORMIDADE',null,null,null,null,false,true,false,'Não operar até correção.',2),
 ('A03','03','Equipamento','Ausência de ruído, vazamento ou superaquecimento','CONFORMIDADE',null,null,null,null,false,true,false,'Parar e acionar manutenção.',3),
 ('A03','04','Medição','Amperagem mínima da turbina','NUMERO','A',12,null,null,false,true,true,'Parar e avaliar a turbina.',4),
 ('A03','05','Produto','Peças jateadas em condição','CONFORMIDADE',null,null,null,null,false,true,false,'Segregar e corrigir o processo.',5)
)
insert into public.itens_checklist(
  modelo_id,codigo,secao,descricao,tipo_resposta,unidade,valor_minimo,valor_alvo,
  valor_maximo,permite_na,critico,gera_carta,plano_reacao,ordem
)
select model.id,item.codigo,item.secao,item.descricao,item.tipo,item.unidade,
  item.minimo::numeric,item.alvo::numeric,item.maximo::numeric,
  item.permite_na,item.critico,item.carta,item.reacao,item.ordem
from item_data item join public.modelos_checklist model on model.codigo=item.modelo
on conflict(modelo_id,codigo) do update set
  secao=excluded.secao,descricao=excluded.descricao,tipo_resposta=excluded.tipo_resposta,
  unidade=excluded.unidade,valor_minimo=excluded.valor_minimo,valor_alvo=excluded.valor_alvo,
  valor_maximo=excluded.valor_maximo,permite_na=excluded.permite_na,
  critico=excluded.critico,gera_carta=excluded.gera_carta,
  plano_reacao=excluded.plano_reacao,ordem=excluded.ordem,ativo=true;

create or replace function public.salvar_execucao_checklist(
  p_modelo_id bigint,
  p_data_operacional date,
  p_turno text,
  p_produto_id bigint,
  p_equipamento text,
  p_corrida text,
  p_observacao text,
  p_respostas jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_modelo public.modelos_checklist%rowtype;
  v_execucao_id bigint;
  v_item public.itens_checklist%rowtype;
  v_resposta jsonb;
  v_resultado text;
  v_valor numeric;
  v_resposta_id bigint;
  v_total_itens integer;
  v_total_respostas integer;
  v_tem_desvio boolean:=false;
  v_tem_critico boolean:=false;
begin
  if not public.usuario_tem_permissao_checklist('checklist.preencher') then
    raise exception 'Usuário sem permissão para preencher checklists.';
  end if;
  if p_turno not in('MANHA','TARDE','NOITE') then
    raise exception 'Turno inválido.';
  end if;
  select * into v_modelo from public.modelos_checklist
  where id=p_modelo_id and ativo=true;
  if not found then raise exception 'Modelo de checklist não encontrado.'; end if;
  if v_modelo.produto_obrigatorio and p_produto_id is null then
    raise exception 'Informe o produto.';
  end if;
  if v_modelo.equipamento_obrigatorio and nullif(trim(p_equipamento),'') is null then
    raise exception 'Informe o equipamento.';
  end if;
  if v_modelo.corrida_obrigatoria and nullif(trim(p_corrida),'') is null then
    raise exception 'Informe a corrida.';
  end if;
  if jsonb_typeof(coalesce(p_respostas,'[]'::jsonb))<>'array' then
    raise exception 'Respostas inválidas.';
  end if;
  select count(*) into v_total_itens from public.itens_checklist
  where modelo_id=p_modelo_id and ativo=true;
  select count(distinct (answer->>'item_id')::bigint) into v_total_respostas
  from jsonb_array_elements(coalesce(p_respostas,'[]'::jsonb)) answer;
  if v_total_itens=0 or v_total_respostas<>v_total_itens then
    raise exception 'Responda todos os itens do checklist.';
  end if;

  insert into public.execucoes_checklist(
    modelo_id,data_operacional,turno,produto_id,equipamento,corrida,
    observacao,operador_id,modelo_versao,status
  ) values (
    p_modelo_id,coalesce(p_data_operacional,current_date),p_turno,p_produto_id,
    nullif(trim(p_equipamento),''),nullif(trim(p_corrida),''),
    nullif(trim(p_observacao),''),auth.uid(),v_modelo.versao,'EM_PREENCHIMENTO'
  ) returning id into v_execucao_id;

  for v_resposta in select value from jsonb_array_elements(p_respostas)
  loop
    select * into v_item from public.itens_checklist
    where id=(v_resposta->>'item_id')::bigint
      and modelo_id=p_modelo_id and ativo=true;
    if not found then raise exception 'Item de checklist inválido.'; end if;
    v_resultado:=nullif(v_resposta->>'resultado','');
    v_valor:=nullif(v_resposta->>'valor_numero','')::numeric;
    if v_item.tipo_resposta='NUMERO' then
      if v_valor is null then raise exception 'Informe o valor de %.',v_item.descricao; end if;
      if v_item.valor_minimo is not null or v_item.valor_maximo is not null then
        v_resultado:=case when
          (v_item.valor_minimo is null or v_valor>=v_item.valor_minimo) and
          (v_item.valor_maximo is null or v_valor<=v_item.valor_maximo)
          then 'CONFORME' else 'NAO_CONFORME' end;
      elsif v_resultado not in('CONFORME','NAO_CONFORME') then
        raise exception 'Informe o resultado da avaliação de %.',v_item.descricao;
      end if;
    elsif v_item.tipo_resposta='TEXTO' then
      if nullif(trim(v_resposta->>'valor_texto'),'') is null then
        raise exception 'Preencha o item %.',v_item.descricao;
      end if;
      v_resultado:='CONFORME';
    elsif v_resultado not in('CONFORME','NAO_CONFORME','NAO_APLICAVEL') then
      raise exception 'Selecione o resultado de %.',v_item.descricao;
    end if;
    if v_resultado='NAO_APLICAVEL' and not v_item.permite_na then
      raise exception 'O item % não permite Não aplicável.',v_item.descricao;
    end if;
    if v_resultado='NAO_CONFORME' and (
      nullif(trim(v_resposta->>'observacao'),'') is null or
      nullif(trim(v_resposta->>'acao_imediata'),'') is null
    ) then raise exception 'Informe desvio e ação imediata de %.',v_item.descricao;
    end if;

    insert into public.respostas_checklist(
      execucao_id,item_id,resultado,valor_numero,valor_texto,observacao,
      acao_imediata,respondido_por
    ) values(
      v_execucao_id,v_item.id,v_resultado,v_valor,
      nullif(trim(v_resposta->>'valor_texto'),''),
      nullif(trim(v_resposta->>'observacao'),''),
      nullif(trim(v_resposta->>'acao_imediata'),''),auth.uid()
    ) returning id into v_resposta_id;

    if v_item.tipo_resposta='NUMERO' and v_item.gera_carta then
      insert into public.medicoes_checklist(
        execucao_id,resposta_id,item_id,produto_id,equipamento,valor,
        limite_minimo,valor_alvo,limite_maximo,conforme
      ) values(
        v_execucao_id,v_resposta_id,v_item.id,p_produto_id,
        nullif(trim(p_equipamento),''),v_valor,v_item.valor_minimo,
        v_item.valor_alvo,v_item.valor_maximo,v_resultado='CONFORME'
      );
    end if;
    if v_resultado='NAO_CONFORME' then
      v_tem_desvio:=true;
      if v_item.critico then v_tem_critico:=true; end if;
    end if;
  end loop;

  update public.execucoes_checklist set
    status=case when v_tem_critico then 'AGUARDANDO_SUPERVISOR'
                when v_tem_desvio then 'NAO_CONFORME' else 'CONFORME' end,
    concluido_em=now()
  where id=v_execucao_id;
  return v_execucao_id;
end;
$$;

create or replace function public.decidir_execucao_checklist(
  p_execucao_id bigint,
  p_decisao text,
  p_justificativa text
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_checklist('checklist.aprovar') then
    raise exception 'Somente o supervisor pode decidir esta liberação.';
  end if;
  if p_decisao not in('LIBERADO','MANTIDO_BLOQUEADO') then
    raise exception 'Decisão inválida.';
  end if;
  if length(trim(coalesce(p_justificativa,'')))<3 then
    raise exception 'Informe a justificativa da decisão.';
  end if;
  if not exists(select 1 from public.execucoes_checklist
    where id=p_execucao_id and status in('AGUARDANDO_SUPERVISOR','BLOQUEADO')) then
    raise exception 'Checklist não está aguardando decisão.';
  end if;
  insert into public.liberacoes_checklist(
    execucao_id,decisao,justificativa,supervisor_id
  ) values(p_execucao_id,p_decisao,trim(p_justificativa),auth.uid());
  update public.execucoes_checklist set
    status=case when p_decisao='LIBERADO' then 'LIBERADO' else 'BLOQUEADO' end
  where id=p_execucao_id;
  return p_execucao_id;
end;
$$;

revoke all on function public.salvar_execucao_checklist(
  bigint,date,text,bigint,text,text,text,jsonb
) from public,anon;
grant execute on function public.salvar_execucao_checklist(
  bigint,date,text,bigint,text,text,text,jsonb
) to authenticated;
revoke all on function public.decidir_execucao_checklist(bigint,text,text)
from public,anon;
grant execute on function public.decidir_execucao_checklist(bigint,text,text)
to authenticated;

notify pgrst, 'reload schema';
commit;
