begin;

-- ==========================================================================
-- Permissões
-- ==========================================================================
insert into public.permissoes(codigo,nome,descricao,modulo,ativo)
select codigo,nome,descricao,'PRODUCAO',true from (values
  ('producao_acabamento.visualizar','Visualizar produção de acabamento','Consulta produção, paradas e indicadores do acabamento.'),
  ('producao_acabamento.lancar','Lançar produção de acabamento','Registra produção e paradas do acabamento.'),
  ('producao_acabamento.editar','Editar produção de acabamento','Corrige registros de produção e paradas do acabamento.'),
  ('producao_acabamento.excluir_turno','Excluir turno de acabamento','Exclui integralmente um turno fechado de acabamento e seus apontamentos.')
) permission(codigo,nome,descricao)
where not exists(select 1 from public.permissoes current_permission
  where current_permission.codigo=permission.codigo);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select profile.id,permission.id from public.perfis profile
cross join public.permissoes permission
where (upper(profile.codigo) in ('ADMIN','ADMINISTRADOR')
  or upper(profile.nome)='ADMINISTRADOR')
and permission.codigo like 'producao_acabamento.%'
and not exists(select 1 from public.perfil_permissoes relation
  where relation.perfil_id=profile.id and relation.permissao_id=permission.id);

insert into public.perfil_permissoes(perfil_id,permissao_id)
select perfil.id,permissao.id from public.perfis perfil
join public.permissoes permissao on permissao.codigo='producao_acabamento.excluir_turno'
where upper(coalesce(perfil.codigo,'')) in ('GERENTE_PRODUCAO','COORDENADOR_PRODUCAO')
on conflict do nothing;

create or replace function public.usuario_tem_permissao_producao_acabamento(p_codigo text)
returns boolean language sql stable security definer
set search_path=pg_catalog,public as $$
  select auth.uid() is not null and coalesce(
    (select user_permission.permitido
     from public.usuario_permissoes user_permission
     join public.permissoes permission on permission.id=user_permission.permissao_id
     where user_permission.usuario_id=auth.uid()
       and permission.codigo=p_codigo limit 1),
    exists(select 1 from public.usuario_perfis user_profile
      join public.perfil_permissoes profile_permission
        on profile_permission.perfil_id=user_profile.perfil_id
      join public.permissoes permission
        on permission.id=profile_permission.permissao_id
      where user_profile.usuario_id=auth.uid() and permission.codigo=p_codigo)
  );
$$;
grant execute on function public.usuario_tem_permissao_producao_acabamento(text) to authenticated;

-- ==========================================================================
-- Tabelas
-- ==========================================================================
create table if not exists public.turnos_producao_acabamento (
  id bigint generated by default as identity primary key,
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  linha_maquina_id bigint not null references public.linhas_maquinas_producao(id),
  status text not null default 'ABERTO' check (status in ('ABERTO','FECHADO')),
  operadores_planejados integer,
  operadores_presentes integer check (operadores_presentes>=0),
  fechado_por uuid references public.usuarios(id),
  fechado_em timestamptz,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  rascunho_producoes jsonb not null default '[]'::jsonb,
  rascunho_paradas jsonb not null default '[]'::jsonb,
  versao bigint not null default 0,
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz,
  unique (data_operacional, turno, linha_maquina_id),
  check ((status='ABERTO' and fechado_em is null) or
         (status='FECHADO' and fechado_em is not null and fechado_por is not null))
);

do $$ begin
  if not exists(select 1 from pg_catalog.pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='turnos_producao_acabamento') then
    alter publication supabase_realtime add table public.turnos_producao_acabamento;
  end if;
end $$;

create table if not exists public.registros_producao_acabamento (
  id bigint generated by default as identity primary key,
  turno_producao_id bigint not null references public.turnos_producao_acabamento(id),
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  produto_id bigint not null references public.produtos(id),
  quantidade_liberada integer not null default 0 check (quantidade_liberada>=0),
  quantidade_rejeitada integer not null default 0 check (quantidade_rejeitada>=0),
  quantidade_retrabalhada integer not null default 0 check (quantidade_retrabalhada>=0),
  quantidade_refugada integer not null default 0 check (quantidade_refugada>=0),
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now()
);

create index if not exists registros_acabamento_turno_idx
  on public.registros_producao_acabamento(turno_producao_id);
create index if not exists registros_acabamento_data_turno_idx
  on public.registros_producao_acabamento(data_operacional desc, turno);

create table if not exists public.paradas_producao_acabamento (
  id bigint generated by default as identity primary key,
  turno_producao_id bigint not null references public.turnos_producao_acabamento(id),
  data_operacional date not null,
  turno text not null check (turno in ('MANHA','TARDE','NOITE')),
  setor_origem_id bigint not null references public.setores_responsaveis_parada(id),
  categoria_id bigint not null references public.categorias_parada_producao(id),
  inicio timestamptz not null,
  fim timestamptz not null,
  duracao_minutos integer not null check (duracao_minutos>=0),
  observacao text,
  criado_por uuid not null default auth.uid() references public.usuarios(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references public.usuarios(id),
  atualizado_em timestamptz not null default now(),
  check (fim>=inicio),
  check (duracao_minutos=round(extract(epoch from (fim-inicio))/60))
);

create index if not exists paradas_acabamento_turno_idx
  on public.paradas_producao_acabamento(turno_producao_id);
create index if not exists paradas_acabamento_data_turno_idx
  on public.paradas_producao_acabamento(data_operacional desc, turno);

create table if not exists public.historico_edicoes_turno_acabamento (
  id bigint generated by default as identity primary key,
  turno_producao_id bigint not null references public.turnos_producao_acabamento(id) on delete cascade,
  descricao text not null check (length(trim(descricao)) between 1 and 1000),
  dados_anteriores jsonb not null default '{}'::jsonb,
  dados_novos jsonb not null default '{}'::jsonb,
  alterado_por uuid not null default auth.uid() references public.usuarios(id),
  alterado_em timestamptz not null default now()
);

create index if not exists historico_edicoes_turno_acabamento_idx
  on public.historico_edicoes_turno_acabamento(turno_producao_id, alterado_em desc);

-- ==========================================================================
-- Triggers
-- ==========================================================================
-- validar_horario_turno_producao() já existe (genérica, usada por Moldagem) e só
-- referencia new.data_operacional/new.turno/new.inicio/new.fim — reaproveitada aqui.
drop trigger if exists validar_horario_parada_acabamento on public.paradas_producao_acabamento;
create trigger validar_horario_parada_acabamento before insert or update of
  data_operacional,turno,inicio,fim on public.paradas_producao_acabamento
for each row execute function public.validar_horario_turno_producao();

create or replace function public.validar_acesso_producao_acabamento()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if not public.usuario_pode_acessar_area_codigo('ACABAMENTO') then
    raise exception 'Usuário sem acesso à área de Acabamento.';
  end if;
  return new;
end $$;

drop trigger if exists validar_area_turno_acabamento on public.turnos_producao_acabamento;
create trigger validar_area_turno_acabamento before insert or update on public.turnos_producao_acabamento
for each row execute function public.validar_acesso_producao_acabamento();
drop trigger if exists validar_area_registro_acabamento on public.registros_producao_acabamento;
create trigger validar_area_registro_acabamento before insert or update on public.registros_producao_acabamento
for each row execute function public.validar_acesso_producao_acabamento();
drop trigger if exists validar_area_parada_acabamento on public.paradas_producao_acabamento;
create trigger validar_area_parada_acabamento before insert or update on public.paradas_producao_acabamento
for each row execute function public.validar_acesso_producao_acabamento();

-- ==========================================================================
-- RLS
-- ==========================================================================
alter table public.turnos_producao_acabamento enable row level security;
alter table public.registros_producao_acabamento enable row level security;
alter table public.paradas_producao_acabamento enable row level security;
alter table public.historico_edicoes_turno_acabamento enable row level security;

drop policy if exists turnos_acabamento_select on public.turnos_producao_acabamento;
create policy turnos_acabamento_select on public.turnos_producao_acabamento for select to authenticated using(
  public.usuario_tem_permissao_producao_acabamento('producao_acabamento.visualizar')
  and public.usuario_pode_acessar_area_codigo('ACABAMENTO'));
grant select on public.turnos_producao_acabamento to authenticated;

drop policy if exists registros_acabamento_select on public.registros_producao_acabamento;
create policy registros_acabamento_select on public.registros_producao_acabamento for select to authenticated using(
  public.usuario_tem_permissao_producao_acabamento('producao_acabamento.visualizar')
  and public.usuario_pode_acessar_area_codigo('ACABAMENTO'));
drop policy if exists registros_acabamento_insert on public.registros_producao_acabamento;
create policy registros_acabamento_insert on public.registros_producao_acabamento for insert to authenticated with check(
  criado_por=auth.uid() and public.usuario_tem_permissao_producao_acabamento('producao_acabamento.lancar'));
drop policy if exists registros_acabamento_update on public.registros_producao_acabamento;
create policy registros_acabamento_update on public.registros_producao_acabamento for update to authenticated using(
  public.usuario_tem_permissao_producao_acabamento('producao_acabamento.editar'))
with check(public.usuario_tem_permissao_producao_acabamento('producao_acabamento.editar'));
grant select,insert,update on public.registros_producao_acabamento to authenticated;

drop policy if exists paradas_acabamento_select on public.paradas_producao_acabamento;
create policy paradas_acabamento_select on public.paradas_producao_acabamento for select to authenticated using(
  public.usuario_tem_permissao_producao_acabamento('producao_acabamento.visualizar')
  and public.usuario_pode_acessar_area_codigo('ACABAMENTO'));
drop policy if exists paradas_acabamento_insert on public.paradas_producao_acabamento;
create policy paradas_acabamento_insert on public.paradas_producao_acabamento for insert to authenticated with check(
  criado_por=auth.uid() and public.usuario_tem_permissao_producao_acabamento('producao_acabamento.lancar'));
drop policy if exists paradas_acabamento_update on public.paradas_producao_acabamento;
create policy paradas_acabamento_update on public.paradas_producao_acabamento for update to authenticated using(
  public.usuario_tem_permissao_producao_acabamento('producao_acabamento.editar'))
with check(public.usuario_tem_permissao_producao_acabamento('producao_acabamento.editar'));
grant select,insert,update on public.paradas_producao_acabamento to authenticated;

drop policy if exists historico_edicoes_acabamento_select on public.historico_edicoes_turno_acabamento;
create policy historico_edicoes_acabamento_select on public.historico_edicoes_turno_acabamento for select to authenticated using(
  public.usuario_tem_permissao_producao_acabamento('producao_acabamento.visualizar'));
grant select on public.historico_edicoes_turno_acabamento to authenticated;

grant usage,select on sequence
  public.turnos_producao_acabamento_id_seq,
  public.registros_producao_acabamento_id_seq,
  public.paradas_producao_acabamento_id_seq,
  public.historico_edicoes_turno_acabamento_id_seq
to authenticated;

-- ==========================================================================
-- RPCs
-- ==========================================================================
create or replace function public.salvar_rascunho_turno_producao_acabamento(
  p_data_operacional date,
  p_turno text,
  p_linha_maquina_id bigint,
  p_operadores_presentes integer default null,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_acabamento%rowtype;
  v_area_id bigint;
begin
  if not public.usuario_tem_permissao_producao_acabamento('producao_acabamento.lancar') then
    raise exception 'Usuário sem permissão para lançar produção de acabamento.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_typeof(coalesce(p_producoes,'[]'::jsonb))<>'array' or jsonb_typeof(coalesce(p_paradas,'[]'::jsonb))<>'array' then
    raise exception 'Rascunho inválido.';
  end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))>100 or jsonb_array_length(coalesce(p_paradas,'[]'::jsonb))>200 then
    raise exception 'O rascunho excede o limite de linhas.';
  end if;

  select id into v_area_id from public.areas_checklist where codigo='ACABAMENTO';

  insert into public.turnos_producao_acabamento(data_operacional,turno,linha_maquina_id,status,operadores_planejados,criado_por)
  values(p_data_operacional,p_turno,p_linha_maquina_id,'ABERTO',
    public.meta_vigente(v_area_id,p_linha_maquina_id,p_turno,'OPERADORES_PLANEJADOS',p_data_operacional),
    auth.uid())
  on conflict(data_operacional,turno,linha_maquina_id) do nothing;

  select * into v_turno from public.turnos_producao_acabamento
  where data_operacional=p_data_operacional and turno=p_turno and linha_maquina_id=p_linha_maquina_id for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if (p_versao is null and v_turno.versao<>0) or (p_versao is not null and p_versao<>v_turno.versao) then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  update public.turnos_producao_acabamento set
    rascunho_producoes=coalesce(p_producoes,'[]'::jsonb),
    rascunho_paradas=coalesce(p_paradas,'[]'::jsonb),
    operadores_presentes=coalesce(p_operadores_presentes,operadores_presentes),
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id
  returning * into v_turno;

  return jsonb_build_object('id',v_turno.id,'versao',v_turno.versao,'operadores_planejados',v_turno.operadores_planejados,'atualizado_por',v_turno.atualizado_por,'atualizado_em',v_turno.atualizado_em);
end;
$$;
revoke all on function public.salvar_rascunho_turno_producao_acabamento(date,text,bigint,integer,jsonb,jsonb,bigint) from public,anon;
grant execute on function public.salvar_rascunho_turno_producao_acabamento(date,text,bigint,integer,jsonb,jsonb,bigint) to authenticated;

create or replace function public.fechar_turno_producao_acabamento(
  p_data_operacional date,
  p_turno text,
  p_linha_maquina_id bigint,
  p_operadores_presentes integer,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb,
  p_versao bigint default null
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_acabamento%rowtype;
  v_area_id bigint;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_acabamento('producao_acabamento.lancar') then
    raise exception 'Usuário sem permissão para fechar o turno.';
  end if;
  if p_turno not in ('MANHA','TARDE','NOITE') then raise exception 'Turno inválido.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos uma linha de produção.'; end if;
  if p_operadores_presentes is null or p_operadores_presentes<0 then raise exception 'Informe a quantidade de operadores presentes.'; end if;

  select id into v_area_id from public.areas_checklist where codigo='ACABAMENTO';

  insert into public.turnos_producao_acabamento(data_operacional,turno,linha_maquina_id,status,operadores_planejados,criado_por)
  values(p_data_operacional,p_turno,p_linha_maquina_id,'ABERTO',
    public.meta_vigente(v_area_id,p_linha_maquina_id,p_turno,'OPERADORES_PLANEJADOS',p_data_operacional),
    auth.uid())
  on conflict(data_operacional,turno,linha_maquina_id) do nothing;

  select * into v_turno from public.turnos_producao_acabamento
  where data_operacional=p_data_operacional and turno=p_turno and linha_maquina_id=p_linha_maquina_id for update;
  if v_turno.status='FECHADO' then raise exception 'Este turno já foi fechado.'; end if;
  if p_versao is not null and p_versao<>v_turno.versao then
    raise exception 'CONFLITO_RASCUNHO: o turno foi atualizado por outro usuário.' using errcode='40001';
  end if;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_acabamento(turno_producao_id,data_operacional,turno,produto_id,quantidade_liberada,quantidade_rejeitada,quantidade_retrabalhada,quantidade_refugada,criado_por)
  select v_turno.id,p_data_operacional,p_turno,item.produto_id,item.quantidade_liberada,item.quantidade_rejeitada,item.quantidade_retrabalhada,item.quantidade_refugada,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(produto_id bigint,quantidade_liberada integer,quantidade_rejeitada integer,quantidade_retrabalhada integer,quantidade_refugada integer)
  join public.produtos produto on produto.id=item.produto_id
  where coalesce(item.quantidade_liberada,0)>=0 and coalesce(item.quantidade_rejeitada,0)>=0
    and coalesce(item.quantidade_retrabalhada,0)>=0 and coalesce(item.quantidade_refugada,0)>=0;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais linhas de produção são inválidas ou possuem produto inexistente.'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_acabamento(turno_producao_id,data_operacional,turno,setor_origem_id,categoria_id,inicio,fim,duracao_minutos,observacao,criado_por)
  select v_turno.id,p_data_operacional,p_turno,item.setor_id,item.categoria_id,item.inicio,item.fim,round(extract(epoch from(item.fim-item.inicio))/60)::integer,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,observacao text)
  join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  join public.setores_responsaveis_parada setor on setor.id=item.setor_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais paradas possuem dados ou horários inválidos.'; end if;

  update public.turnos_producao_acabamento set
    status='FECHADO',fechado_por=auth.uid(),fechado_em=now(),
    operadores_presentes=p_operadores_presentes,
    rascunho_producoes='[]'::jsonb,rascunho_paradas='[]'::jsonb,
    versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id;
  return v_turno.id;
end;
$$;
revoke all on function public.fechar_turno_producao_acabamento(date,text,bigint,integer,jsonb,jsonb,bigint) from public,anon;
grant execute on function public.fechar_turno_producao_acabamento(date,text,bigint,integer,jsonb,jsonb,bigint) to authenticated;

create or replace function public.editar_turno_producao_acabamento(
  p_turno_id bigint,
  p_operadores_presentes integer,
  p_producoes jsonb default '[]'::jsonb,
  p_paradas jsonb default '[]'::jsonb
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_turno public.turnos_producao_acabamento%rowtype;
  v_anteriores jsonb;
  v_novos jsonb;
  v_esperado integer;
  v_inserido integer;
begin
  if not public.usuario_tem_permissao_producao_acabamento('producao_acabamento.editar') then
    raise exception 'Usuário sem permissão para editar turnos fechados.';
  end if;
  select * into v_turno from public.turnos_producao_acabamento where id=p_turno_id and status='FECHADO' for update;
  if not found then raise exception 'Turno fechado não encontrado.'; end if;
  if jsonb_array_length(coalesce(p_producoes,'[]'::jsonb))=0 then raise exception 'Informe ao menos uma linha de produção.'; end if;

  select jsonb_build_object(
    'operadores_presentes',v_turno.operadores_presentes,
    'productions',coalesce((select jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by produto_id) from public.registros_producao_acabamento registro where turno_producao_id=p_turno_id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(parada)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by inicio) from public.paradas_producao_acabamento parada where turno_producao_id=p_turno_id),'[]'::jsonb)
  ) into v_anteriores;

  delete from public.paradas_producao_acabamento where turno_producao_id=p_turno_id;
  delete from public.registros_producao_acabamento where turno_producao_id=p_turno_id;

  v_esperado:=jsonb_array_length(coalesce(p_producoes,'[]'::jsonb));
  insert into public.registros_producao_acabamento(turno_producao_id,data_operacional,turno,produto_id,quantidade_liberada,quantidade_rejeitada,quantidade_retrabalhada,quantidade_refugada,criado_por)
  select v_turno.id,v_turno.data_operacional,v_turno.turno,item.produto_id,item.quantidade_liberada,item.quantidade_rejeitada,item.quantidade_retrabalhada,item.quantidade_refugada,auth.uid()
  from jsonb_to_recordset(coalesce(p_producoes,'[]'::jsonb)) as item(produto_id bigint,quantidade_liberada integer,quantidade_rejeitada integer,quantidade_retrabalhada integer,quantidade_refugada integer)
  join public.produtos produto on produto.id=item.produto_id
  where coalesce(item.quantidade_liberada,0)>=0 and coalesce(item.quantidade_rejeitada,0)>=0
    and coalesce(item.quantidade_retrabalhada,0)>=0 and coalesce(item.quantidade_refugada,0)>=0;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais linhas de produção são inválidas ou possuem produto inexistente.'; end if;

  v_esperado:=jsonb_array_length(coalesce(p_paradas,'[]'::jsonb));
  insert into public.paradas_producao_acabamento(turno_producao_id,data_operacional,turno,setor_origem_id,categoria_id,inicio,fim,duracao_minutos,observacao,criado_por)
  select v_turno.id,v_turno.data_operacional,v_turno.turno,item.setor_id,item.categoria_id,item.inicio,item.fim,round(extract(epoch from(item.fim-item.inicio))/60)::integer,nullif(trim(item.observacao),''),auth.uid()
  from jsonb_to_recordset(coalesce(p_paradas,'[]'::jsonb)) as item(inicio timestamptz,fim timestamptz,setor_id bigint,categoria_id bigint,observacao text)
  join public.categorias_parada_producao categoria on categoria.id=item.categoria_id
  join public.setores_responsaveis_parada setor on setor.id=item.setor_id
  where item.inicio is not null and item.fim is not null and item.fim>=item.inicio;
  get diagnostics v_inserido=row_count;
  if v_inserido<>v_esperado then raise exception 'Uma ou mais paradas possuem dados ou horários inválidos.'; end if;

  update public.turnos_producao_acabamento set
    operadores_presentes=coalesce(p_operadores_presentes,operadores_presentes),
    atualizado_por=auth.uid(),atualizado_em=now()
  where id=v_turno.id;

  select jsonb_build_object(
    'operadores_presentes',coalesce(p_operadores_presentes,v_turno.operadores_presentes),
    'productions',coalesce((select jsonb_agg(to_jsonb(registro)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by produto_id) from public.registros_producao_acabamento registro where turno_producao_id=p_turno_id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(parada)-'id'-'turno_producao_id'-'criado_por'-'criado_em'-'atualizado_por'-'atualizado_em' order by inicio) from public.paradas_producao_acabamento parada where turno_producao_id=p_turno_id),'[]'::jsonb)
  ) into v_novos;

  if v_anteriores = v_novos then
    raise exception 'Nenhuma alteração foi identificada.';
  end if;

  insert into public.historico_edicoes_turno_acabamento(
    turno_producao_id,descricao,dados_anteriores,dados_novos,alterado_por
  ) values (
    p_turno_id,'os apontamentos do turno',v_anteriores,v_novos,auth.uid()
  );
  return p_turno_id;
end;
$$;
grant execute on function public.editar_turno_producao_acabamento(bigint,integer,jsonb,jsonb) to authenticated;

create or replace function public.excluir_turno_producao_acabamento(p_turno_id bigint)
returns void language plpgsql security definer
set search_path=pg_catalog,public as $$
begin
  if not public.usuario_tem_permissao_producao_acabamento('producao_acabamento.excluir_turno') then
    raise exception 'Usuário sem permissão para excluir turnos de acabamento.';
  end if;
  if not exists(select 1 from public.turnos_producao_acabamento where id=p_turno_id and status='FECHADO') then
    raise exception 'Turno fechado não encontrado.';
  end if;
  delete from public.paradas_producao_acabamento where turno_producao_id=p_turno_id;
  delete from public.registros_producao_acabamento where turno_producao_id=p_turno_id;
  delete from public.historico_edicoes_turno_acabamento where turno_producao_id=p_turno_id;
  delete from public.turnos_producao_acabamento where id=p_turno_id;
end;
$$;
grant execute on function public.excluir_turno_producao_acabamento(bigint) to authenticated;

notify pgrst,'reload schema';

commit;
