begin;

-- A correia do Acabamento (antes "Correia 3") passa a se chamar "Correia 1".
update public.postos_equipamentos_acabamento
set codigo='CORREIA_1', nome='Correia 1'
where codigo='CORREIA_3';

-- Catálogo genérico de equipamentos por setor, usado só na tela de Paradas
-- Programadas (Metas Gerenciais) para setores que ainda não têm apontamento
-- de produção próprio (Macharia, Fusão) e para setores que já têm (Moldagem,
-- Acabamento). Não substitui os catálogos operacionais reais quando eles
-- existem (ex.: postos_equipamentos_acabamento) — é usado só para configurar
-- os horários de parada programada.
create table if not exists public.equipamentos_planejamento (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.areas_checklist(id),
  codigo text not null,
  nome text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  unique(area_id,codigo)
);

alter table public.equipamentos_planejamento enable row level security;
drop policy if exists equipamentos_planejamento_select on public.equipamentos_planejamento;
create policy equipamentos_planejamento_select on public.equipamentos_planejamento
for select to authenticated using(auth.uid() is not null);
grant select on public.equipamentos_planejamento to authenticated;

insert into public.equipamentos_planejamento(area_id,codigo,nome)
select area.id,equipamento.codigo,equipamento.nome
from public.areas_checklist area
join (values
  ('MACHARIA','HV3_1','HV3-1'),
  ('MACHARIA','HV3_2','HV3-2'),
  ('MACHARIA','HV3_3','HV3-3'),
  ('MACHARIA','HV3_4','HV3-4'),
  ('MACHARIA','SPM20_5','SPM20-5'),
  ('MOLDAGEM','DISA','DISA'),
  ('FUSAO','PONTE_10','Ponte 10'),
  ('FUSAO','PONTE_40','Ponte 40'),
  ('FUSAO','F1','F1'),
  ('FUSAO','F2','F2'),
  ('FUSAO','H1','H1'),
  ('FUSAO','H2','H2'),
  ('ACABAMENTO','JATO_1','Jato 1'),
  ('ACABAMENTO','JATO_2','Jato 2'),
  ('ACABAMENTO','JATO_GANCHEIRA','Jato Gancheira'),
  ('ACABAMENTO','CORREIA_1','Correia 1'),
  ('ACABAMENTO','VS_AUTOMATICA','VS Automática')
) equipamento(area_codigo,codigo,nome) on equipamento.area_codigo=area.codigo
on conflict(area_id,codigo) do nothing;

-- Parada programada pode ser da área toda ("Geral"), de uma linha específica
-- ou de um equipamento específico — nunca linha e equipamento ao mesmo tempo.
alter table public.paradas_programadas
  add column if not exists equipamento_planejamento_id bigint references public.equipamentos_planejamento(id);

alter table public.paradas_programadas drop constraint if exists paradas_programadas_unidade_unica_chk;
alter table public.paradas_programadas add constraint paradas_programadas_unidade_unica_chk
  check (linha_maquina_id is null or equipamento_planejamento_id is null);

drop index if exists public.paradas_programadas_vigente_uidx;
create unique index if not exists paradas_programadas_vigente_uidx
  on public.paradas_programadas(area_id, coalesce(linha_maquina_id,-1), coalesce(equipamento_planejamento_id,-1), coalesce(turno,'-'), tipo_parada_codigo)
  where vigencia_fim is null;

create or replace function public.definir_parada_programada(
  p_area_id bigint,
  p_linha_maquina_id bigint,
  p_equipamento_planejamento_id bigint,
  p_turno text,
  p_tipo_parada_codigo text,
  p_horario_inicial time,
  p_horario_final time,
  p_dias_semana smallint[],
  p_vigencia_inicio date
) returns bigint
language plpgsql security definer
set search_path=pg_catalog,public as $$
declare
  v_id bigint;
begin
  if not public.usuario_tem_permissao_metas('metas.gerenciar') then
    raise exception 'Usuário sem permissão para gerenciar paradas programadas.';
  end if;
  if p_turno is not null and p_turno not in ('MANHA','TARDE','NOITE') then
    raise exception 'Turno inválido.';
  end if;
  if p_linha_maquina_id is not null and p_equipamento_planejamento_id is not null then
    raise exception 'Selecione apenas uma unidade de trabalho: linha ou equipamento.';
  end if;
  if p_dias_semana is null or array_length(p_dias_semana,1) is null then
    raise exception 'Selecione ao menos um dia da semana.';
  end if;

  update public.paradas_programadas set vigencia_fim = p_vigencia_inicio - 1
  where area_id=p_area_id
    and coalesce(linha_maquina_id,-1)=coalesce(p_linha_maquina_id,-1)
    and coalesce(equipamento_planejamento_id,-1)=coalesce(p_equipamento_planejamento_id,-1)
    and coalesce(turno,'-')=coalesce(p_turno,'-')
    and tipo_parada_codigo=p_tipo_parada_codigo
    and vigencia_fim is null
    and vigencia_inicio < p_vigencia_inicio;

  insert into public.paradas_programadas(
    area_id,linha_maquina_id,equipamento_planejamento_id,turno,tipo_parada_codigo,horario_inicial,horario_final,dias_semana,vigencia_inicio,criado_por
  ) values (
    p_area_id,p_linha_maquina_id,p_equipamento_planejamento_id,p_turno,p_tipo_parada_codigo,p_horario_inicial,p_horario_final,p_dias_semana,p_vigencia_inicio,auth.uid()
  ) returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.definir_parada_programada(bigint,bigint,bigint,text,text,time,time,smallint[],date) from public,anon;
grant execute on function public.definir_parada_programada(bigint,bigint,bigint,text,text,time,time,smallint[],date) to authenticated;
drop function if exists public.definir_parada_programada(bigint,bigint,text,text,time,time,smallint[],date);

notify pgrst,'reload schema';

commit;
